/* Fictional, in-memory preview. No accounts, storage, network writes or activation. */
(function(){'use strict';
const P=window.RedaPlanner,F=window.RedaFigures,$=id=>document.getElementById(id);
let stop=null,plan=null,selected=0,view='plan',counts=[],profile='daily';
const profiles={hyrox:{title:'Mot nästa startlinje.',intro:'En del av rehabiliteringen för en träningsvan person med Hyrox som mål.',options:{capacity:'high',stage:'higher',trainingHistory:'rehab_experienced',equipment:'gym',goalProfile:'hyrox'}},daily:{title:'Starkare i vardagen.',intro:'En tydlig start med stöd där det behövs.',options:{capacity:'supported',stage:'protected',trainingHistory:'new',equipment:'home',goalProfile:'daily'}},gym:{title:'Tillbaka till styrkan.',intro:'En annan plan för den som redan har träningsvana.',options:{capacity:'high',stage:'build',trainingHistory:'rehab_experienced',equipment:'gym',goalProfile:'strength'}},run:{title:'Mot löpningen igen.',intro:'Övningar valda med ett mer krävande mål i sikte.',options:{capacity:'high',stage:'higher',trainingHistory:'rehab_experienced',equipment:'gym',goalProfile:'run'}}};
function renderBasis(){const o=window.RedaIntelligence.overview(plan),host=$('example-basis-body');host.replaceChildren();const p=document.createElement('p');p.textContent=o.focus;host.append(p);const dl=document.createElement('dl');dl.className='ei-axes';for(const axis of o.axes){const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=axis.label;dd.textContent=axis.value;row.append(dt,dd);dl.append(row)}host.append(dl)}
function renderResponsePreview(){const session={id:'fictional-example',plan_id:'fictional-plan',plan_version:1,status:'completed',completed_at:new Date(Date.now()-36*3600000).toISOString()};const form=window.RedaResponseForm.create($('example-response'),{demo:true,submit:async(sid,rid,answers)=>({id:'fictional-response',session_id:sid,plan_id:session.plan_id,plan_version:1,created_at:new Date().toISOString(),answers})});form.render({userId:'fictional-example',sessions:[session],responses:[]})}
function pause(){stop?.();stop=null;$('play-motion').textContent='Visa rörelsen'}
function frame(phase){pause();const x=plan.exercises[selected];$('example-motion').innerHTML=F.svg(x.motionKey,phase,x.side,x.name);document.querySelectorAll('[data-frame]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.frame)===phase)))}
function total(x){return Number(x.dose.sets||1)*(x.side==='both'?2:1)}
function progress(){const x=plan.exercises[selected],n=counts[selected]||0,t=total(x);$('mark-round').disabled=n>=t;$('mark-round').textContent=n>=t?'Övningen är markerad som klar':'Markera en omgång';$('round-status').textContent=`${n} av ${t} omgångar markerade i exemplet${x.side==='both'?' · vänster och höger räknas separat':''}.`;const sum=counts.reduce((a,b)=>a+b,0),done=counts.filter((v,i)=>v===total(plan.exercises[i])).length;$('demo-progress').textContent=sum?`${sum} ${sum===1?'omgång registrerad':'omgångar registrerade'}`:'Inget registrerat ännu';$('demo-progress-detail').textContent=sum?`${done} av ${plan.exercises.length} övningar helt genomförda i visningsexemplet.`:'Prova att markera en omgång under steg 2.'}
function showExercise(index){selected=index;const x=plan.exercises[index];$('example-title').textContent=x.name;$('example-dose').textContent=x.dose.label+(x.side==='both'?' per sida':'');$('example-why').textContent=x.instruction||x.why;frame(0);progress()}
function changeView(next){pause();view=next;['plan','exercise','follow'].forEach(v=>$('view-'+v).hidden=v!==next);document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===next)));if(next==='exercise')showExercise(selected);if(next==='follow')progress()}
function render(key){pause();profile=key;const p=profiles[key];plan=P.buildProgram({blueprintId:'knee_pf',floorOK:true,band:true,...p.options});counts=plan.exercises.map(()=>0);selected=0;renderBasis();renderResponsePreview();$('example-goal').textContent=p.title;$('follow-goal').textContent=p.title;$('example-intro').textContent=p.intro;$('example-count').textContent=plan.exercises.length+' övningar';$('example-exercises').replaceChildren(...plan.exercises.map((x,i)=>{const b=document.createElement('button');b.type='button';b.dataset.example=i;const n=document.createElement('span');n.className='n';n.textContent=String(i+1).padStart(2,'0');const name=document.createElement('span');name.className='name';name.textContent=x.name;const dose=document.createElement('small');dose.textContent=x.dose.label;name.append(dose);const arrow=document.createElement('span');arrow.className='arrow';arrow.textContent='›';arrow.setAttribute('aria-hidden','true');b.append(n,name,arrow);b.onclick=()=>{selected=i;changeView('exercise');$('back-plan').focus({preventScroll:true})};return b}));document.querySelectorAll('[data-profile]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.profile===key)));showExercise(0);changeView('plan')}
$('play-motion').onclick=()=>{if(stop){pause();return}const x=plan.exercises[selected];document.querySelectorAll('[data-frame]').forEach(b=>b.setAttribute('aria-pressed','false'));stop=F.animate($('example-motion'),x.motionKey,{seconds:9});$('play-motion').textContent='Pausa rörelsen'};
document.querySelectorAll('[data-profile]').forEach(b=>b.onclick=()=>render(b.dataset.profile));document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>changeView(b.dataset.view));document.querySelectorAll('[data-frame]').forEach(b=>b.onclick=()=>frame(Number(b.dataset.frame)));$('back-plan').onclick=()=>changeView('plan');$('mark-round').onclick=()=>{counts[selected]=Math.min(total(plan.exercises[selected]),counts[selected]+1);progress()};$('reset-demo').onclick=()=>render(profile);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});new IntersectionObserver(entries=>{if(!entries[0].isIntersecting)pause()}).observe($('example-motion'));
try{render('daily')}catch(e){$('example-exercises').textContent='Exemplet kunde inte laddas. Läs om Reda nedan.';document.querySelectorAll('[data-view]').forEach(b=>b.disabled=true);console.error(e)}
})();
