-- Isolated fictional records only. No external sends or production users.
\ir ../../reda-2/secure/barrier-loop.sql
insert into auth.users(id,email,email_confirmed_at)values(tests.id(960001),'barrier@example.test',now());
insert into auth.sessions values(tests.id(960101),tests.id(960001));
insert into reda_patients(id,organization_id,clinician_id,display_name,auth_user_id)values(tests.id(960000),tests.org('dashboard-test'),tests.id(1),'Fictional barrier',tests.id(960001));
insert into private.reda_patient_profiles(patient_id,focus)values(tests.id(960000),'Fictional goal');
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)values(tests.id(960010),tests.id(960000),tests.id(1),1,'active',jsonb_set(jsonb_set(tests.plan(8),'{exercises,0,dose,sets}','2'),'{exercises,0,dose,label}','"2 x 8"'));
create function tests.barrier_session(n int,plan uuid)returns void language sql as $$insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,completed_at,payload)select tests.id(n),tests.id(n),patient_id,id,version,'completed',now(),now(),'{"exercises":[{"exerciseId":"extension","status":"completed","roundsDone":1,"feedback":"okay"}]}'::jsonb from reda_plans where id=plan$$;
select tests.barrier_session(960020,tests.id(960010));
set role authenticated;select tests.login(960001,'aal1',960101);
select reda_submit_session_reflection(tests.id(960020),tests.id(960021),'{"barrier":"time","support":"no","exerciseId":null}');
select set_config('tests.loop',reda_patient_barriers(tests.id(960000))->0->>'id',false);
select tests.ok(reda_patient_barriers(tests.id(960000))->0->>'phase'='needs_context','time signal opens specific quick question');
select tests.denied('select reda_publish_barrier(current_setting(''tests.loop'')::uuid,tests.id(960022),''token'',tests.plan(8),''Patient cannot approve'',''A clinical change'',current_date+7)','42501','patient cannot approve a plan');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select set_config('tests.loop_token',reda_dashboard_patient(tests.id(960000))->>'token',false);
select tests.ok(reda_dashboard_patient(tests.id(960000))->'workflow'->>'phase'='barrier_question','overview identifies the next actor as patient');
select tests.login(950002,'aal1',950102);
select tests.denied('select reda_patient_barriers(tests.id(960000))','42501','another patient cannot read barrier history');
select tests.denied('select reda_answer_barrier(current_setting(''tests.loop'')::uuid,tests.id(960023),''{"minutes":10}'')','42501','another patient cannot answer');
select tests.login(960001,'aal1',960101);
select tests.denied('select reda_answer_barrier(current_setting(''tests.loop'')::uuid,tests.id(960023),''{"minutes":10,"approved":true}'')','22023','extra fields cannot smuggle approval');
select reda_answer_barrier(current_setting('tests.loop')::uuid,tests.id(960023),'{"minutes":10}');
select tests.ok(reda_answer_barrier(current_setting('tests.loop')::uuid,tests.id(960023),'{"minutes":10}')->>'phase'='ready','lost context receipt is safe to retry');
select tests.denied('select reda_answer_barrier(current_setting(''tests.loop'')::uuid,tests.id(960023),''{"minutes":20}'')','23505','saved answer is immutable');
select tests.login(1,'aal2',103);
select tests.ok(reda_dashboard_patient(tests.id(960000))->>'token'<>current_setting('tests.loop_token'),'quick reply invalidates previously viewed evidence');
select tests.denied('select reda_publish_barrier(current_setting(''tests.loop'')::uuid,tests.id(960024),reda_dashboard_patient(tests.id(960000))->>''token'',tests.plan(8),''Reviewed fewer rounds'',''Your reviewed shorter plan'',current_date+7)','42501','publication gate also blocks linked intervention');
reset role;update reda_organizations set patient_delivery_enabled=true where id=tests.org('dashboard-test');
set role authenticated;select tests.login(1,'aal2',103);
select tests.denied('select reda_publish_barrier(current_setting(''tests.loop'')::uuid,tests.id(960024),current_setting(''tests.loop_token''),tests.plan(8),''Reviewed fewer rounds'',''Your reviewed shorter plan'',current_date+7)','40001','stale clinical evidence cannot approve the loop');
select set_config('tests.loop_token2',reda_dashboard_patient(tests.id(960000))->>'token',false);
select set_config('tests.loop_publish',reda_publish_barrier(current_setting('tests.loop')::uuid,tests.id(960024),current_setting('tests.loop_token2'),tests.plan(8),'Reviewed fewer rounds','Your reviewed shorter plan',current_date+7)::text,false);
select tests.ok(reda_publish_barrier(current_setting('tests.loop')::uuid,tests.id(960024),current_setting('tests.loop_token2'),tests.plan(8),'Reviewed fewer rounds','Your reviewed shorter plan',current_date+7)::text=current_setting('tests.loop_publish'),'lost publication receipt cannot create two versions');
select tests.ok(reda_dashboard_patient(tests.id(960000))->'workflow'->>'phase'='barrier_trial','overview follows trial rather than claiming clinical completion');
select tests.login(960001,'aal1',960101);
select tests.ok(reda_patient_barriers(tests.id(960000))->0->>'phase'='trying','a published plan is not evidence it was tried');
select tests.denied('select reda_barrier_outcome(current_setting(''tests.loop'')::uuid,tests.id(960026),''helped'',tests.id(960020))','22023','old-plan training cannot close new intervention');
reset role;select tests.barrier_session(960025,(current_setting('tests.loop_publish')::jsonb->>'plan_id')::uuid);
set role authenticated;select tests.login(960001,'aal1',960101);
select tests.ok(reda_patient_barriers(tests.id(960000))->0->>'phase'='check_result','actual new-plan exercise unlocks targeted result');
select tests.ok(reda_barrier_outcome(current_setting('tests.loop')::uuid,tests.id(960026),'helped',tests.id(960025))->>'phase'='helped','positive outcome closes only practical barrier');
select tests.ok(reda_barrier_outcome(current_setting('tests.loop')::uuid,tests.id(960026),'helped',tests.id(960025))->>'phase'='helped','lost outcome receipt is idempotent');
select tests.denied('select reda_barrier_outcome(current_setting(''tests.loop'')::uuid,tests.id(960026),''no'',tests.id(960025))','23505','outcome history cannot be rewritten');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_activity_log(tests.id(960000),'feedback')->'events')e where e->>'title'='Praktiskt hinder avslutat'),'patient has a dated outcome receipt');
reset role;
select tests.ok((select count(*)=2 from reda_plans where patient_id=tests.id(960000)),'reply never adds a clinical plan');
select tests.ok((select status='completed' from private.reda_followups where patient_id=tests.id(960000)),'untouched system followup completed after measured outcome');
-- Explicit help request prevents automatic closure even when the practical change helps.
select tests.barrier_session(960030,(current_setting('tests.loop_publish')::jsonb->>'plan_id')::uuid);
set role authenticated;select tests.login(960001,'aal1',960101);
select reda_submit_session_reflection(tests.id(960030),tests.id(960031),'{"barrier":"equipment","support":"yes","exerciseId":null}');
select set_config('tests.loop2',reda_patient_barriers(tests.id(960000))->0->>'id',false);
select reda_answer_barrier(current_setting('tests.loop2')::uuid,tests.id(960032),'{"equipment":"home","band":false,"floorOK":true}');
select tests.login(1,'aal2',103);
select set_config('tests.loop_publish2',reda_publish_barrier(current_setting('tests.loop2')::uuid,tests.id(960033),reda_dashboard_patient(tests.id(960000))->>'token',tests.plan(8),'Reviewed equipment change','Your reviewed equipment plan',current_date+7)::text,false);
reset role;select tests.barrier_session(960034,(current_setting('tests.loop_publish2')::jsonb->>'plan_id')::uuid);
set role authenticated;select tests.login(960001,'aal1',960101);
select tests.ok(reda_barrier_outcome(current_setting('tests.loop2')::uuid,tests.id(960035),'helped',tests.id(960034))->>'phase'='needs_review','success does not silently close an explicit request for clinician help');
select tests.login(1,'aal2',103);
select tests.ok((reda_dashboard_patient(tests.id(960000))->'patient'->>'open_count')::int=1,'case returns to clinician with original request and new outcome');
select tests.workspace('clinic-b');
select tests.denied('select reda_dashboard_patient(tests.id(960000))','42501','barrier projections do not cross clinical workspaces');
select tests.workspace('dashboard-test');select tests.login(960001,'aal1',999);
select tests.denied('select reda_patient_barriers(tests.id(960000))','42501','revoked patient session has no access');
reset role;
select tests.ok(not has_table_privilege('authenticated','private.reda_barrier_loops','select'),'internal receipt and approvals are not directly exposed');
select tests.ok(not has_function_privilege('authenticated','private.reda_barrier_state(uuid)','execute'),'unchecked projection stays private');
select tests.ok(not has_function_privilege('anon','public.reda_answer_barrier(uuid,uuid,jsonb)','execute'),'anonymous answers denied');
select tests.ok((select relrowsecurity from pg_class where oid='private.reda_barrier_loops'::regclass),'barrier table has RLS');
select tests.ok((select not automatic_enabled and not ai_enabled from private.reda_engine_settings),'clinical engine and external AI stay off');
update reda_organizations set patient_delivery_enabled=false where id=tests.org('dashboard-test');
