const {test}=require('node:test'),assert=require('node:assert/strict'),C=require('../../reda-2/care-path.js');
const remote=()=>({mode:'remote',weeks:6,startDate:'2026-09-10',assessment:{confirmed:true,date:'2026-09-09',method:'video'},checkpoints:C.suggest('2026-09-10',6,'video')});
test('six and eight week suggestions preserve ordered explicit contact types across DST',()=>{const six=C.suggest('2026-09-10',6,'video');assert.deepEqual(six.map(x=>x.date),['2026-09-24','2026-10-08','2026-10-22']);const eight=C.suggest('2026-10-01',8,'phone');assert.equal(eight[2].date,'2026-11-26');assert.ok(eight.every(x=>x.method==='phone'))});
test('remote activation checklist requires an actual assessment and dated checkpoints',()=>{const p=remote();assert.deepEqual(C.issues(p,'2026-09-10'),[]);p.assessment.confirmed=false;assert.match(C.issues(p,'2026-09-10').join(' '),/Bekräfta/);p.assessment.confirmed=true;p.assessment.date='2026-09-11';assert.match(C.issues(p,'2026-09-10').join(' '),/bedömning/i);p.checkpoints[0].date='';assert.match(C.issues(p,'2026-09-10').join(' '),/första avstämningen/)});
test('impossible dates, wrong order and dates outside period are rejected',()=>{assert.equal(C.validDate('2026-02-30'),false);const p=remote();p.checkpoints[1].date='2026-09-20';assert.match(C.issues(p,'2026-09-10').join(' '),/ordning/);p.checkpoints[2].date='2026-12-01';assert.match(C.issues(p,'2026-09-10').join(' '),/inom/)});
test('contact changes never mutate exercise dosage or previous plan version',()=>{const p={schema:6,goal:'Fiktivt mål',exercises:[{id:'x',dose:{sets:3,reps:17},prescribedLoad:'12 kg'}]},next=C.attach(p,remote());assert.deepEqual(next.exercises,p.exercises);assert.equal(p.careJourney,undefined);assert.equal(next.reviewDate,'2026-09-24');const copy=JSON.parse(JSON.stringify(next));assert.deepEqual(C.read(copy),next.careJourney)});
test('legacy plans and plans without dates remain readable',()=>{const p=C.read({reviewDate:'2026-09-20'});assert.equal(p.mode,'clinic');assert.equal(p.checkpoints[0].id,'review');assert.equal(C.overview({},'2026-09-10').next,null);assert.deepEqual(C.issues({},'2026-09-10'),[])});
test('elapsed dates never imply completed contact or automatic progression',()=>{const p=C.attach({exercises:[]},remote()),before=JSON.stringify(p),v=C.overview(p,'2026-10-30');assert.equal(v.next,null);assert.equal(v.unconfirmedPast,3);assert.ok(v.points.every(x=>x.passed));assert.equal(JSON.stringify(p),before);assert.ok(v.points.every(x=>!Object.hasOwn(x,'completed')))});
test('unknown contact types, duplicated checkpoints and unsupported package lengths fail closed',()=>{assert.throws(()=>C.normalize({mode:'automated'}));assert.throws(()=>C.normalize({weeks:52}));const p=remote();p.checkpoints.push(p.checkpoints[0]);assert.throws(()=>C.normalize(p))});
