"""Fictional clinical workflow; browser network restricted to the CI fixture server."""
from runtime_browser_test import RuntimeTests as Base,DYNAMIC,EXTRA
from playwright.sync_api import expect
import unittest
INBOX="""
window.inboxCases=Array.from({length:28},(_,i)=>({id:'inbox-'+i,patient_id:'patient-1',display_name:'Fiktiv testperson '+i,patient_status:'active',status:i===0?'acknowledged':'open',code:i===1?'changed_symptoms':'requested_contact',created_at:'2026-09-09T10:00:00Z',response:{plan_version:1,answers:{nextDay:'unknown',function:'stable',recovery:'ready',otherTraining:'usual',quality:'controlled',environment:'same',contact:'yes'}}}));
window.inboxLoads=[];
export async function clinicInbox(status,code,offset){window.inboxLoads.push({status,code,offset});if(window.inboxFailure)throw Error('Fiktivt nätverksfel');const rows=inboxCases.filter(c=>(status==='unresolved'?c.status!=='resolved':c.status===status)&&(code==='all'||c.code===code));return {total:rows.length,cases:rows.slice(offset,offset+25),counts:{open:27,acknowledged:1,resolved:0},reviews:{agree:0,disagree:0,uncertain:0}}}
export async function reviewDecision(id,verdict,note){if(!verdict||note.trim().length<5)throw Error('Ange din bedömning');const d=window.runtimeDecisions.find(d=>d.id===id);d.review={verdict,note};return d.review}
"""
class IntelligenceTests(Base):
 def setUp(self):
  super().setUp();self.c.route('**/secure-browser.mjs*',lambda r:r.fulfill(status=200,content_type='text/javascript',body=DYNAMIC+EXTRA.replace("const c=window.runtimeCases.find(x=>x.id===id)","const c=[...window.runtimeCases,...window.inboxCases].find(x=>x.id===id)")+INBOX))
 def test_build_three_step_path_retains_explicit_rules_and_does_not_publish(self):
  self.p.goto(self.o+'/reda-2/klinik-live.html');self.p.locator('[data-patient]').click();h=self.p.locator('#progressionEditor');expect(h).to_contain_text('Sparat ramutkast');h.locator('#path-prescribedLoad').fill('Fiktiv vikt');h.locator('#pathLabel').fill('Belastning');h.locator('#pathReason').fill('Fiktivt skäl till nästa steg.');h.locator('[data-save-path]').click();expect(h.locator('[data-path-error]')).to_contain_text('påbörjade steget');h.locator('[data-add-step]').click();expect(h.locator('[data-path-steps]>li')).to_have_count(3);h.locator('#path-prescribedRange').fill('Fiktivt rörelseomfång');h.locator('#pathLabel').fill('Rörelseomfång');h.locator('#pathReason').fill('Fiktiv klinisk riktning.');h.locator('[data-add-step]').click();expect(h.locator('[data-path-steps]>li')).to_have_count(4);h.locator('[data-save-path]').click();expect(h).to_contain_text('Sparat ramutkast · 4 steg');expect(h.locator('#pathDays')).to_have_value('3');expect(h.locator('#pathEffort')).to_have_value('easy,okay');self.assertEqual(self.p.evaluate('runtimeActions.length'),0);self.p.locator('[data-worktab=followup]').click();self.p.locator('.runtime-frame summary').click();expect(self.p.locator('.runtime-frame')).to_contain_text('Fiktivt rörelseomfång');expect(self.p.locator('[data-approve]')).to_be_disabled();self.shot('reda-intelligence-paths.png')
 def test_inbox_pages_filters_error_and_case_resolution(self):
  self.p.goto(self.o+'/reda-2/klinik-live.html');h=self.p.locator('#clinicInbox');expect(h.locator('[data-inbox-page]')).to_have_text('1–25 av 28');h.locator('[data-page-next]').click();expect(h.locator('[data-inbox-page]')).to_have_text('26–28 av 28');h.locator('[data-inbox-status]').select_option('acknowledged');expect(h.locator('[data-inbox-page]')).to_have_text('1–1 av 1');h.locator('.inbox-case summary').click();h.locator('[data-state=resolved]').click();expect(h.locator('[data-inbox-message]')).to_contain_text('Ange bedömning');h.locator('[data-inbox-note]').fill('Fiktiv bedömning dokumenterad.');h.locator('[data-state=resolved]').click();expect(h.locator('[data-inbox-page]')).to_have_text('0 ärenden');h.locator('[data-inbox-status]').select_option('unresolved');self.p.evaluate('inboxFailure=true');h.locator('[data-inbox-refresh]').click();expect(h.locator('[data-inbox-message]')).to_contain_text('kunde inte hämtas');expect(h.locator('.inbox-case')).to_have_count(0);self.p.evaluate('inboxFailure=false');h.locator('[data-inbox-refresh]').click();expect(h.locator('[data-inbox-page]')).to_have_text('1–25 av 27');self.shot('reda-clinic-inbox-mobile.png')
 def test_motor_judgment_never_applies_progression_or_resolves_cases(self):
  self.p.goto(self.o+'/reda-2/klinik-live.html');self.p.locator('[data-patient]').click();self.p.evaluate("runtimeDecisions=[{id:'decision-1',code:'ready',applied:false,metrics:{successfulDays:3,requiredDays:3,daysAtStep:7},created_at:'2026-09-11T10:00:00Z'}]");self.p.locator('[data-worktab=followup]').click();h=self.p.locator('.runtime-decisions');h.locator('summary').click();h.locator('[data-verdict]').select_option('disagree');h.locator('[data-decision-note]').fill('Fiktiv bedömning: underlaget behöver följas upp.');h.locator('[data-review-decision]').click();expect(h).to_contain_text('Avvikande bedömning');self.assertEqual(self.p.evaluate('runtimeDecisions[0].applied'),False);self.assertEqual(self.p.evaluate('runtimeCases[0].status'),'open');self.assertEqual(self.p.evaluate('runtimeActions.length'),0)
 def test_step_help_and_conversation_followup_do_not_store_answers(self):
  self.p.goto(self.o+'/reda-2/patient.html');self.p.evaluate('runtimeAI=true');self.p.locator('[data-tab=program]').click();h=self.p.locator('#planHelp');h.locator('summary').first.click();h.locator('[data-help=clarify]').click();expect(h.locator('[data-answer]')).to_contain_text('Sitt med stöd');h.get_by_role('button',name='Nästa instruktion',exact=True).click();expect(h.locator('[data-answer]')).to_contain_text('Sträck knät');h.locator('[data-help=too_easy]').click();expect(h.locator('[data-answer]')).to_contain_text('en ny planversion');h.locator('[data-open-ai]').click();h.locator('[data-question]').fill('Jag är trött idag.');h.locator('[type=submit]').click();expect(h.locator('[data-ai-status]')).to_contain_text('nätverksfel');h.locator('[type=submit]').click();expect(h.locator('[data-question]')).to_have_value('');expect(h.locator('[data-history]')).to_be_visible();h.locator('[data-question]').fill('Vad menas med återhämtad?');h.locator('[type=submit]').click();expect(h.locator('[data-conversation] article')).to_have_count(2);self.assertEqual(self.p.evaluate('runtimeAIQuestions.at(-1).conversation.previousQuestions'),['Jag är trött idag.']);self.assertEqual(self.p.evaluate('runtimeAIQuestions.at(-1).conversation.exerciseIndex'),0);h.locator('[data-clear-dialogue]').click();expect(h.locator('[data-history]')).to_be_hidden();self.assertEqual(self.p.evaluate('eiCalls.length'),0);self.assertFalse(self.p.evaluate("Object.keys(localStorage).some(k=>/dialogue|question|chat/i.test(k))"));self.shot('reda-dialogue-help.png')
del Base
if __name__=='__main__':unittest.main(verbosity=2)
