-- Ephemeral fixtures only. Installation must leave execution and external AI off.
\ir ../../reda-2/supabase/migrations/20260919165540_clinical_ei_mandates.sql
select tests.ok((select not automatic_enabled and not ai_enabled from private.reda_engine_settings),'mandate installation preserves closed rollout');
insert into reda_patients(id,organization_id,clinician_id,display_name)values(tests.id(850001),tests.org('dashboard-test'),tests.id(1),'Fictional mandate patient');
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)values(tests.id(850002),tests.id(850001),tests.id(1),1,'active',tests.plan(8));
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(reda_clinical_ei_settings()->>'enabled'='false','clinical mandate defaults off');
select tests.ok(reda_clinical_ei_settings()->>'revision'='0','new mandate starts at revision zero');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,12)','22023','step bounds enforced');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,null)','22023','missing limit rejected');
select tests.denied('update private.reda_clinical_ei_mandates set enabled=true','42501','raw mandate writes denied');
select tests.login(4,'aal2',104);
select tests.ok(reda_clinical_ei_settings()->>'can_manage'='false','member sees read-only mandate');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)','42501','member cannot authorize clinic');
select tests.login(1,'aal1',103);
select tests.denied('select reda_clinical_ei_settings()','42501','MFA required for read');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)','42501','MFA required for write');
select tests.login(1,'aal2',103);
select set_config('tests.clinical_receipt',reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)::text,false);
select tests.ok(reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)=current_setting('tests.clinical_receipt')::jsonb,'identical lost-receipt retry is stable');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,false,1)','23505','changed retry refused');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851002),0,true,2)','40001','stale concurrent revision refused');
select tests.ok(reda_clinical_ei_settings()->>'execution_open'='false','prepared mandate cannot open global execution');
select tests.denied('select reda_approve_frame(tests.id(850002),tests.policy(),''automatic'')','42501','closed global execution blocks approval');
select set_config('tests.clinical_frame',reda_approve_frame(tests.id(850002),tests.policy(),'shadow')->>'id',false);
reset role;
select tests.ok((select mandate_revision is null from reda_progression_frames where id=current_setting('tests.clinical_frame')::uuid),'shadow does not borrow automatic authority');
update reda_progression_frames set started_at=now()-interval '10 days'where patient_id=tests.id(850001)and status='approved';
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,created_at,completed_at,payload)
 select tests.id(852000+i),tests.id(853000+i),tests.id(850001),tests.id(850002),1,'completed',now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),'{"exercises":[{"exerciseId":"extension","status":"completed","roundsDone":1,"feedback":"okay"}]}'::jsonb from generate_series(1,3)i;
insert into reda_training_responses(request_id,session_id,patient_id,plan_id,plan_version,reported_by,created_at,answers)
 select tests.id(854000+i),tests.id(852000+i),tests.id(850001),tests.id(850002),1,tests.id(2),now()-make_interval(days=>9-2*i),tests.answer()||'{"environment":"same"}'::jsonb from generate_series(1,3)i;
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855001))->>'code'='ready','closed gate preserves shadow evaluation');
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855001))->>'applied'='false','shadow cannot apply');
reset role;update private.reda_engine_settings set automatic_enabled=true;
set role authenticated;
select set_config('tests.clinical_frame',reda_approve_frame(tests.id(850002),tests.policy(),'automatic')->>'id',false);
reset role;
select tests.ok((select mandate_revision=1 and mandate_organization_id=tests.org('dashboard-test')from reda_progression_frames where id=current_setting('tests.clinical_frame')::uuid),'automatic approval bound to exact clinic and mandate revision');
update reda_progression_frames set started_at=now()-interval '10 days'where id=current_setting('tests.clinical_frame')::uuid;
set role authenticated;
select reda_save_clinical_ei_mandate(tests.id(851002),1,false,1);
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855002))->>'code'='mandate_disabled','revocation stops existing approved frame');
select tests.denied('select reda_approve_frame(tests.id(850002),tests.policy(),''automatic'')','42501','revoked mandate blocks new automatic approval');
select reda_save_clinical_ei_mandate(tests.id(851003),2,true,1);
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855003))->>'code'='mandate_changed','reenabling does not resurrect old authority');
select set_config('tests.clinical_frame',reda_approve_frame(tests.id(850002),tests.policy(),'automatic')->>'id',false);
reset role;
update reda_progression_frames set started_at=now()-interval '10 days'where id=current_setting('tests.clinical_frame')::uuid;
-- A legacy unbound approval fails closed, and same revision in another clinic is insufficient.
update reda_progression_frames set mandate_organization_id=null,mandate_revision=null where id=current_setting('tests.clinical_frame')::uuid;
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855004))->>'code'='mandate_changed','legacy automatic approval needs new review');
reset role;
update reda_progression_frames set mandate_organization_id=tests.org('clinic-b'),mandate_revision=3 where id=current_setting('tests.clinical_frame')::uuid;
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855005))->>'code'='mandate_changed','foreign clinic revision cannot authorize plan');
reset role;
update reda_progression_frames set mandate_organization_id=tests.org('dashboard-test') where id=current_setting('tests.clinical_frame')::uuid;
update private.reda_engine_settings set automatic_enabled=false;
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855006))->>'code'='execution_closed','global kill switch stops existing authority');
reset role;update private.reda_engine_settings set automatic_enabled=true;
set role authenticated;
select set_config('tests.clinical_next',reda_evaluate_progression(tests.id(850001),tests.id(855007))->>'result_plan_id',false);
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855007))->>'applied'='true','authorized step applies once');
reset role;
select tests.ok((select payload=tests.plan(10)from reda_plans where id=current_setting('tests.clinical_next')::uuid),'only exact next approved plan applied');
select tests.ok((select count(*)=2 from reda_plans where patient_id=tests.id(850001)),'retry cannot duplicate advancement');
update reda_progression_frames set started_at=now()-interval '10 days'where id=current_setting('tests.clinical_frame')::uuid;
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,created_at,completed_at,payload)
 select tests.id(852010+i),tests.id(853010+i),tests.id(850001),current_setting('tests.clinical_next')::uuid,2,'completed',now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),'{"exercises":[{"exerciseId":"extension","status":"completed","roundsDone":1,"feedback":"okay"}]}'::jsonb from generate_series(1,3)i;
insert into reda_training_responses(request_id,session_id,patient_id,plan_id,plan_version,reported_by,created_at,answers)
 select tests.id(854010+i),tests.id(852010+i),tests.id(850001),current_setting('tests.clinical_next')::uuid,2,tests.id(2),now()-make_interval(days=>9-2*i),tests.answer()||'{"environment":"same"}'::jsonb from generate_series(1,3)i;
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855008))->>'code'='mandate_limit','second eligible increase stops at one-step limit');
select tests.ok(reda_evaluate_progression(tests.id(850001),tests.id(855008))->>'applied'='false','limit never mutates plan');
select tests.workspace('clinic-b');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)','23505','receipt cannot cross clinic scope');
reset role;
update reda_memberships set status='revoked'where organization_id=tests.org('dashboard-test')and user_id=tests.id(1);
set role authenticated;select tests.workspace('dashboard-test');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851001),0,true,1)','42501','revoked owner cannot replay successful receipt');
reset role;
update reda_memberships set status='active'where organization_id=tests.org('dashboard-test')and user_id=tests.id(1);
update private.reda_engine_settings set automatic_enabled=false;
select tests.ok((select count(*)=3 from private.reda_clinical_mandate_receipts),'one audited before-and-after receipt per real change');
set role anon;
select tests.denied('select reda_clinical_ei_settings()','42501','anonymous read denied');
select tests.denied('select reda_save_clinical_ei_mandate(tests.id(851004),3,false,1)','42501','anonymous write denied');
reset role;
