const {test}=require('node:test'),assert=require('node:assert/strict');
require('../../reda-2/data.js');require('../../reda-2/core.js');const C=global.RedaCore,D=global.RedaData;
test('all 3 templates validate and contain fictitious programs only',()=>D.templates.forEach(t=>assert.equal(C.validatePlan(C.template(t.id)).demo,true)));
test('all 16 variants survive a unicode program-link round trip',()=>D.exercises.forEach(e=>e.variants.forEach(v=>{const p=C.template();p.items=[C.makeItem(e.id,v.id)];p.title='Övning för höft & båda sidor';assert.deepEqual(C.decodePlan(C.encodePlan(p)),C.validatePlan(p));})));
test('hand-supported chair owns supported instructions',()=>{const {v}=C.lookup('chair','support');assert(v.steps.join(' ').includes('Använd händerna'));assert(!v.steps.join(' ').includes('utan hjälp'));});
test('unsupported chair owns independent instructions',()=>assert(C.lookup('chair','free').v.steps.join(' ').includes('utan hjälp')));
test('one-sided chair is refused',()=>{const p=C.template();p.items[0].side='left';assert.throws(()=>C.validatePlan(p));});
test('both-legged calf variant cannot claim single side',()=>{const p=C.template();p.items=[C.makeItem('calf','both')];p.items[0].side='left';assert.throws(()=>C.validatePlan(p));});
test('single calf accepts either prescribed side',()=>{const p=C.template();p.items=[C.makeItem('calf','single','left')];assert.equal(C.validatePlan(p).items[0].side,'left');});
test('no universal first-pass halving',()=>{const p=C.template();assert.equal(C.newSession(p,true).items[0].dose.sets,p.items[0].dose.sets);});
test('explicit start dose consistently reduces counter and label',()=>{const p=C.template();p.adjustment.enabled=true;p.adjustment.sets=1;const s=C.newSession(p,true);assert(s.firstAdjusted);assert.equal(s.items[0].dose.sets,1);assert.equal(C.rounds(s.items[0]),1);assert(C.doseLabel(s.items[0]).startsWith('1 omgång'));assert.equal(C.newSession(p,false).items[0].dose.sets,2);});
test('start dose can never increase prescription',()=>{const p=C.template();p.adjustment.enabled=true;p.adjustment.sets=3;assert.throws(()=>C.validatePlan(p));});
test('dose counters are numeric, not parsed from prose',()=>{const p=C.template();p.items[0].note='99 set, detta är testtext';assert.equal(C.rounds(C.newSession(p).items[0]),2);});
test('bilateral dose is explicitly left then right per set',()=>{const i=C.makeItem('extension','easy','both');assert.equal(C.rounds(i),4);assert.deepEqual(C.roundInfo(i,0),{set:1,side:'Vänster'});assert.deepEqual(C.roundInfo(i,1),{set:1,side:'Höger'});assert.deepEqual(C.roundInfo(i,2),{set:2,side:'Vänster'});});
test('first mark persists a partial round without completing exercise',()=>{const s=C.markRound(C.newSession(C.template()),0);assert.equal(s.items[0].done,1);assert.equal(C.progress(s).done,0);assert(C.progress(s).started);assert.equal(C.finish(s).status,'partial');});
test('skipping is never counted as completion',()=>{let s=C.newSession(C.template());for(let i=0;i<s.items.length;i++)s=C.skip(s,i,'Annan anledning');assert.equal(C.progress(s).done,0);assert.equal(C.finish(s).status,'not-done');});
test('pain flag never changes dosage',()=>{const s=C.newSession(C.template());const a=C.skip(s,0,'Besvär under övningen');assert(a.issue);assert.deepEqual(a.items.map(i=>i.dose),s.items.map(i=>i.dose));});
test('complete only after all required rounds',()=>{let s=C.newSession(C.template());for(let n=0;n<s.items.length;n++)for(let r=0;r<C.rounds(s.items[n]);r++)s=C.markRound(s,n);assert.equal(C.finish(s).status,'complete');});
test('extra clicks cannot exceed dose',()=>{let s=C.newSession(C.template());for(let n=0;n<20;n++)s=C.markRound(s,0);assert.equal(s.items[0].done,C.rounds(s.items[0]));});
test('finished sessions are immutable to round markers',()=>{const s=C.finish(C.newSession(C.template()));assert.deepEqual(C.markRound(s,0),s);});
test('historical dosage is snapshotted',()=>{const p=C.template(),s=C.newSession(p);p.items[0].dose.sets=6;assert.equal(s.items[0].dose.sets,2);});
test('partial sessions do not count as full weekly training',()=>{const p=C.template(),s=C.finish(C.markRound(C.newSession(p),0));assert.equal(C.weekSummary([s],p).done,0);});
test('multiple completed sessions on one date do not inflate weekly days',()=>{const p=C.template();let s=C.newSession(p);s.items.forEach(i=>i.done=C.rounds(i));s=C.finish(s);assert.equal(C.weekSummary([s,{...s,id:'another'}],p).done,1);});
test('rest day is recognized without assigning a failed session',()=>{const p=C.template();p.days=[1];const w=C.weekSummary([],p,new Date('2026-09-09T12:00:00'));assert.equal(w.days.find(d=>d.today).scheduled,false);assert.equal(w.days.find(d=>d.today).status,'empty');});
test('bad links and legacy patient codes are not guessed',()=>['ABC-12','x'.repeat(30001),'%%%',''].forEach(x=>assert.throws(()=>C.decodePlan(x))));
test('non-prototype or unknown schema refused',()=>{for(const value of [false,undefined]){const p=C.template();p.demo=value;assert.throws(()=>C.validatePlan(p));}});
test('duplicate IDs refused',()=>{const p=C.template();p.items[1].key=p.items[0].key;assert.throws(()=>C.validatePlan(p));});
test('out-of-range dose refused',()=>{for(const n of [0,-1,NaN,9,Infinity,1.5]){const p=C.template();p.items[0].dose.sets=n;assert.throws(()=>C.validatePlan(p));}});
test('blank plan and empty schedule refused',()=>{const p=C.template();p.title='';assert.throws(()=>C.validatePlan(p));p.title='Test';p.days=[];assert.throws(()=>C.validatePlan(p));});
test('all real session states validate',()=>{let s=C.newSession(C.template());C.validateSession(s);s=C.markRound(s,0);C.validateSession(s);C.validateSession(C.finish(s));});
test('falsely labelled complete sessions are refused during import',()=>{const s=C.newSession(C.template());s.status='complete';assert.throws(()=>C.validateSession(s));});
test('required data fields reject oversized values',()=>{const p=C.template();p.message='x'.repeat(601);assert.throws(()=>C.validatePlan(p));});
