-- Fictional sessions only. New source, ownership, current-session and retry boundaries.
\ir ../../reda-2/secure/exercise-help.sql
insert into auth.users(id,email,email_confirmed_at)values(tests.id(970001),'exercise-help@example.test',now());
insert into auth.sessions values(tests.id(970101),tests.id(970001));
insert into reda_patients(id,organization_id,clinician_id,display_name,auth_user_id)values(tests.id(970000),tests.org('dashboard-test'),tests.id(1),'Fictional exercise help',tests.id(970001));
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)values(tests.id(970010),tests.id(970000),tests.id(1),1,'active',tests.plan(8));
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,payload)values(tests.id(970020),tests.id(970120),tests.id(970000),tests.id(970010),1,'started',now(),'{"exercises":[{"exerciseId":"extension","status":"pending","roundsDone":0}]}');
select tests.ok((select relrowsecurity from pg_class where oid='public.reda_exercise_help'::regclass),'help has row security');
select tests.ok(not has_table_privilege('authenticated','public.reda_exercise_help','INSERT'),'patients cannot forge source snapshots');
select tests.ok(not has_function_privilege('anon','public.reda_submit_exercise_help(uuid,text,uuid,jsonb)','EXECUTE'),'anonymous help submission denied');
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select set_config('tests.help_token',reda_dashboard_patient(tests.id(970000))->>'token',false);
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["side"],"outcome":"clear","note":"","version":1}'')','42501','clinician cannot report patient understanding');
select tests.login(950002,'aal1',950102);
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["side"],"outcome":"clear","note":"","version":1}'')','42501','another patient cannot report on a session');
select tests.login(970001,'aal1',970101);
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''wrong-exercise'',tests.id(970030),''{"topics":["side"],"outcome":"clear","note":"","version":1}'')','22023','exercise must belong to saved session');
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["side","side"],"outcome":"clear","note":"","version":1}'')','22023','duplicate topics rejected');
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["diagnosis"],"outcome":"clear","note":"","version":1}'')','22023','unknown help topic rejected');
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["side"],"outcome":"clear","note":"","version":1,"approved":true}'')','22023','no clinical approval field');
select set_config('tests.clear_receipt',reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970030),'{"topics":["side"],"outcome":"clear","note":"","version":1}')::text,false);
select tests.ok(reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970030),'{"topics":["side"],"outcome":"clear","note":"","version":1}')::text=current_setting('tests.clear_receipt'),'same request returns exact saved receipt');
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970030),''{"topics":["range"],"outcome":"clear","note":"","version":1}'')','23505','same request cannot change the answer');
select tests.ok((select count(*)from reda_exercise_help where patient_id=tests.id(970000))=1,'one event after retry');
select tests.ok((select count(*)from reda_review_cases where patient_id=tests.id(970000))=0,'understood instruction is not a clinical case');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_activity_log(tests.id(970000),'feedback')->'events')e where e->>'title'='Övningsinstruktionen upplevs tydlig'),'patient history includes own response');
select tests.login(1,'aal2',103);
select tests.ok(reda_dashboard_patient(tests.id(970000))->>'token'<>current_setting('tests.help_token'),'patient understanding invalidates old approval context');
select tests.login(970001,'aal1',970101);
select reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970031),'{"topics":["side","range"],"outcome":"needs_help","note":"Please clarify the movement","version":1}');
select tests.ok((select count(*)from reda_review_cases where patient_id=tests.id(970000)and code='execution_help'and status='open')=1,'request creates a real open execution case');
select tests.login(1,'aal2',103);
select tests.ok(reda_dashboard_patient(tests.id(970000))->'cases'->0->'exercise_help'->>'exercise_name'='Fictional knee extension','dashboard has authoritative exercise name');
select tests.ok(reda_dashboard_patient(tests.id(970000))->'cases'->0->'exercise_help'->'exercise'->>'side'='right','dashboard has authoritative saved side');
select tests.ok(reda_dashboard_patient(tests.id(970000))->'workflow'->>'phase'='needs_review','saved request needs clinician review');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_clinic_inbox('unresolved','execution_help',0)->'cases')c where c->>'patient_id'=tests.id(970000)::text and c->'exercise_help'->>'note'='Please clarify the movement'),'global inbox includes the same source and question');
select tests.login(1,'aal1',103);
select tests.ok((select count(*)from reda_exercise_help where patient_id=tests.id(970000))=0,'clinician AAL1 cannot read help history');
select tests.login(970001,'aal1',970101);
select reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970032),'{"topics":["execution"],"outcome":"clear","note":"","version":1}');
select tests.ok((select count(*)from reda_review_cases where patient_id=tests.id(970000)and status='open')=1,'later clear answer does not silently close an existing request');
reset role;
select tests.ok(exists(select 1 from private.reda_followups where patient_id=tests.id(970000)and status='waiting'),'existing EI mandate queues the clinical request');
select tests.denied('insert into reda_review_cases(patient_id,plan_id,code)values(tests.id(970000),tests.id(970010),''execution_help'')','23514','case must still have exactly one source');
select tests.denied('insert into reda_review_cases(patient_id,plan_id,code,exercise_help_id,reflection_id)select tests.id(970000),tests.id(970010),''execution_help'',(select id from reda_exercise_help where request_id=tests.id(970030)),(select id from reda_session_reflections limit 1)','23514','case cannot mix help with another source');
-- Keep an unfinished session on its original plan while the active plan changes.
update reda_plans set status='superseded' where id=tests.id(970010);
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)values(tests.id(970011),tests.id(970000),tests.id(1),2,'active',tests.plan(10));
set role authenticated;select tests.login(970001,'aal1',970101);
select reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970033),'{"topics":["dose"],"outcome":"clear","note":"","version":1}');
select tests.ok((select plan_version=1 and exercise->'dose'->>'reps'='8' from reda_exercise_help where request_id=tests.id(970033)),'ongoing historical session keeps its actual prescription');
reset role;update reda_sessions set status='partial',completed_at=now()where id=tests.id(970020);
set role authenticated;select tests.login(970001,'aal1',970101);
select tests.ok(reda_submit_exercise_help(tests.id(970120),'extension',tests.id(970030),'{"topics":["side"],"outcome":"clear","note":"","version":1}')::text=current_setting('tests.clear_receipt'),'receipt survives session completion and plan replacement');
select tests.denied('select reda_submit_exercise_help(tests.id(970120),''extension'',tests.id(970034),''{"topics":["side"],"outcome":"clear","note":"","version":1}'')','40001','no new report on a closed session');
reset role;
-- Use the approved option, not the base exercise dose.
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)
select tests.id(970012),tests.id(970000),tests.id(1),3,'draft',tests.plan(8)||jsonb_build_object('planOptions',jsonb_build_object('schema',1,'approved',true,'source',private.reda_options_binding(tests.plan(8)),'items',jsonb_build_array(jsonb_build_object('id','less-rounds','reason','time','label','Fictional approved option','context','{}'::jsonb,'exercises',jsonb_set(tests.plan(8)->'exercises','{0,dose,reps}','4')))));
update reda_plans set status='superseded'where id=tests.id(970011);update reda_plans set status='active'where id=tests.id(970012);
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,payload)values(tests.id(970021),tests.id(970121),tests.id(970000),tests.id(970012),3,'started',now(),'{"optionId":"less-rounds","exercises":[{"exerciseId":"extension","status":"pending","roundsDone":0}]}');
set role authenticated;select tests.login(970001,'aal1',970101);
select reda_submit_exercise_help(tests.id(970121),'extension',tests.id(970035),'{"topics":["dose"],"outcome":"needs_help","note":"Option question","version":1}');
select tests.ok((select exercise->'dose'->>'reps'='4' and option_label='Fictional approved option'from reda_exercise_help where request_id=tests.id(970035)),'option source is bound on server');
select tests.login(950002,'aal1',950102);
select tests.ok((select count(*)from reda_exercise_help where patient_id=tests.id(970000))=0,'other patient has no help visibility');
reset role;delete from auth.sessions where id=tests.id(970101);
set role authenticated;select tests.login(970001,'aal1',970101);
select tests.denied('select reda_submit_exercise_help(tests.id(970121),''extension'',tests.id(970036),''{"topics":["side"],"outcome":"clear","note":"","version":1}'')','42501','revoked session cannot write');
reset role;
