"""A fast clinician's complete journey, with fictional data only."""
import unittest
from playwright.sync_api import expect
from plan_authoring_browser_test import T as AuthoringBase,MOCK,ROOT
MOCK=MOCK.replace('export async function dashboard(', 'async function baseDashboard(').replace('export async function dashboardPatient(', 'async function basePatient(').replace('export async function patientProfile()', 'async function baseProfile()')+"""
window.created=[];window.starts=[];
export async function dashboard(search='',filter='all',offset=0){let r=await baseDashboard(search,filter,offset);const added=window.created.filter(x=>x.org===current);if(filter==='ei'||filter==='symptoms'||filter==='replies'||filter==='reviews'){r.patients=r.patients.filter(x=>x.needs_review);r.total=r.patients.length}if(filter==='no_plan'){r.patients=[];r.total=0}if(['all','no_plan'].includes(filter)&&offset===0&&!search){r.patients=[...added,...r.patients].slice(0,25);r.total+=added.length}r.counts={...r.counts,all:1000+added.length,no_plan:600+added.length,ei:2,symptoms:1,replies:1,reviews:1};return r}
export async function dashboardPatient(id){const p=window.created.find(x=>x.patient_id===id);return p?{patient:p,token:'fresh',today:'2026-09-11',plan:null,cases:[],history:[]}:basePatient(id)}
export async function patientProfile(id){const p=window.created.find(x=>x.patient_id===id);return p?p.profile:baseProfile()}
export async function savePatientProfile(input){return savePatientStart(input)}
export async function savePatientStart(input){window.starts.push(structuredClone(input));const id='new-'+(window.created.length+1),profile={...input.profile,clinical_context:input.clinicalContext,delivery_mode:input.delivery,revision:1},p={patient_id:id,org:current,display_name:profile.name,patient_status:'active',connected:false,care_focus:profile.focus,care_goal:profile.goal,profile,plan_id:null};window.created.push(p);return {status:'saved',patient:{id,display_name:profile.name,status:'active'},profile}}
"""
class T(AuthoringBase):
 def setUp(self):
  self.c=self.browser.new_context(viewport={'width':1440,'height':1000});self.c.route('**/*',lambda r:r.continue_()if r.request.url.startswith(self.origin)else r.abort());self.c.route('**/secure-browser.mjs*',lambda r:r.fulfill(status=200,content_type='text/javascript',body=MOCK));self.p=self.c.new_page();self.errors=[];self.p.on('pageerror',lambda e:self.errors.append(str(e)));self.p.goto(self.origin+'/reda-2/klinik-live.html');self.p.locator('[data-detail="a-2"]').wait_for()
 def test_dense_overview_and_ei_queues_keep_the_registry_visible(self):
  expect(self.p.locator('[data-filter]')).to_have_value('all');expect(self.p.locator('.dash-row')).to_have_count(25);expect(self.p.locator('[data-metric="active"] strong')).to_have_text('400');self.assertLess(self.p.locator('.dash-row').nth(1).bounding_box()['height'],110);self.assertLess(self.p.locator('.dash-row').nth(6).bounding_box()['y'],1000);self.p.locator('[data-stream="ei"]').click();expect(self.p.locator('.dash-row')).to_have_count(2);self.p.locator('[data-detail="a-2"]').click();expect(self.p.locator('.dash-detail')).to_be_visible();expect(self.p.locator('.dash-list')).to_be_visible();effect=self.p.locator('.dash-effect').bounding_box();approve=self.p.locator('[data-approve]').bounding_box();self.assertGreaterEqual(approve['y'],effect['y']+effect['height']);expect(self.p.locator('#decisionDashboard')).to_be_visible();self.p.locator('[data-close]').click();expect(self.p.locator('.dash-detail')).not_to_be_visible();self.p.locator('[data-stream="all"]').click();expect(self.p.locator('.dash-row')).to_have_count(25)
 def test_name_only_is_not_a_normal_patient_start_and_quick_choices_transfer_to_ei(self):
  self.p.locator('[data-new]').click();d=self.p.locator('dialog');d.locator('[name="name"]').fill('Fiktiv Snabbstart');d.locator('[data-save]').click();expect(d.locator('[data-message]')).to_contain_text('Komplettera');self.assertEqual(self.p.evaluate('window.starts.length'),0);d.locator('[name="email"]').fill('fast@example.test');d.locator('[data-area]').select_option('Knä');d.locator('[data-start-side]').select_option('left');d.locator('[data-goal]').select_option('Gå och klara trappor');d.locator('[data-start-profile]').select_option('supported');d.locator('[data-start-included]').check();d.locator('[data-save]').click();expect(d).to_have_count(0);expect(self.p.locator('#decisionDashboard')).to_be_visible();expect(self.p.locator('.dash-detail h3')).to_have_text('Fiktiv Snabbstart');self.p.locator('[data-start-ei]').click();expect(self.p.locator('[data-mode="suggest"]')).to_have_attribute('aria-pressed','true');expect(self.p.locator('[data-generate]')).to_be_disabled();self.p.locator('[data-direction="knee_pf"]').click();expect(self.p.locator('[data-generate]')).to_be_enabled();self.p.locator('[data-generate]').click();expect(self.p.locator('[data-choice]')).to_have_count(3);self.p.locator('[data-choice="0"]').click();self.p.locator('[data-apply]').click();p=self.save();self.assertEqual(p['context']['capacity'],'supported');self.assertFalse(p['context']['floorOK']);self.assertTrue(p['authoring']['includedInVisit']);self.assertTrue(all(x['side']=='left'for x in p['exercises']if x['id']=='extension'))
 def test_existing_manual_work_does_not_reset_the_selected_ei_direction(self):
  self.open_patient();self.add('bridge');self.p.locator('[data-mode="suggest"]').click();self.p.locator('[data-profile="supported"]').click();self.p.locator('[data-direction="knee_pf"]').click();self.p.locator('[data-generate]').click();expect(self.p.locator('[data-choice]')).to_have_count(3);expect(self.p.locator('#planMeta')).to_have_text('1 övningar');self.p.locator('[data-choice="1"]').click();self.p.locator('[data-profile="home"]').click();expect(self.p.locator('[data-candidate]')).not_to_be_visible();expect(self.p.locator('[data-choice]')).to_have_count(0);self.p.locator('[data-generate]').click();self.p.locator('[data-choice="1"]').click();self.p.locator('[data-apply]').click();self.assertEqual(self.save()['context']['blueprintId'],'knee_pf')
 def test_worksheet_printing_does_not_create_a_patient_or_draft(self):
  self.p.locator('[data-worksheet]').click();expect(self.p.locator('#patientTitle')).to_have_text('Övningsblad');self.add('chair');self.p.evaluate('window.print=()=>{window.printed=true;dispatchEvent(new Event("afterprint"))}');self.p.locator('#saveDraft').click();self.p.locator('[data-review-confirm]').check();self.p.get_by_role('button',name='Skriv ut',exact=True).click();self.assertTrue(self.p.evaluate('window.printed'));self.assertEqual(self.p.evaluate('window.created.length'),0);self.assertEqual(self.p.evaluate('window.drafts.length'),0);self.p.locator('[data-close-preview]').click();self.p.locator('#backToDashboard').click();expect(self.p.locator('#decisionDashboard')).to_be_visible()
 def test_clinic_handover_explicitly_allows_no_electronic_contact(self):
  self.p.locator('[data-new]').click();d=self.p.locator('dialog');d.locator('[name="name"]').fill('Fiktiv Pappersplan');d.locator('[data-area]').select_option('Axel');d.locator('[data-delivery]').select_option('clinic');d.locator('[data-save]').click();expect(d).to_have_count(0);self.assertEqual(self.p.evaluate('window.starts[0].delivery'),'clinic');self.assertEqual(self.p.evaluate('window.starts[0].profile.email'),'')
 def test_dashboard_intake_and_suggestion_layouts(self):
  out=ROOT/'reda2-test-results';out.mkdir(exist_ok=True);self.p.screenshot(path=str(out/'fast-dashboard-desktop.png'),full_page=False);self.p.locator('[data-detail="a-2"]').click();self.p.locator('.dash-detail h3').wait_for();self.p.screenshot(path=str(out/'fast-dashboard-detail.png'),full_page=False);self.p.set_viewport_size({'width':390,'height':844});self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.p.screenshot(path=str(out/'fast-dashboard-mobile.png'),full_page=False);self.p.locator('[data-close]').click();self.p.set_viewport_size({'width':1440,'height':1000});self.p.locator('[data-new]').click();self.p.locator('dialog [data-area]').select_option('Knä');self.p.screenshot(path=str(out/'fast-intake-desktop.png'),full_page=False);self.p.set_viewport_size({'width':390,'height':844});self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.p.screenshot(path=str(out/'fast-intake-mobile.png'),full_page=False);self.p.locator('dialog [data-close]').click();self.p.set_viewport_size({'width':1440,'height':1000});self.open_patient();self.p.locator('[data-mode="suggest"]').click();self.p.locator('[data-direction="knee_pf"]').click();self.p.locator('[data-generate]').click();self.p.locator('[data-plan-choices]').scroll_into_view_if_needed();self.p.screenshot(path=str(out/'fast-ei-choices.png'),full_page=False)
for name in dir(AuthoringBase):
 if name.startswith('test_')and name not in T.__dict__:setattr(T,name,None)
del AuthoringBase
if __name__=='__main__':unittest.main()
