-- Ephemeral test identities only. No real mail is sent.
alter table auth.users add column email_confirmed_at timestamptz;
\ir ../../reda-2/secure/clinical-handover.sql
insert into auth.users(id,email,email_confirmed_at)values(tests.id(950001),'handover@example.test',now()),(tests.id(950002),'other-handover@example.test',now()),(tests.id(950003),'unconfirmed@example.test',null);
insert into auth.sessions values(tests.id(950101),tests.id(950001)),(tests.id(950102),tests.id(950002)),(tests.id(950103),tests.id(950003));
insert into reda_patients(id,organization_id,clinician_id,display_name) values(tests.id(950000),tests.org('dashboard-test'),tests.id(1),'Fictional handover');
insert into private.reda_patient_profiles(patient_id,focus)values(tests.id(950000),'Fictional knee');
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select set_config('tests.handover_token',reda_dashboard_patient(tests.id(950000))->>'token',false);
select tests.denied('select reda_publish_reviewed(tests.id(950000),tests.id(950010),current_setting(''tests.handover_token''),null,tests.plan(8),''Reviewed fictional plan'',''Your first fictional plan'',''handover@example.test'')','42501','release gate blocks publication');
reset role;update reda_organizations set patient_delivery_enabled=true where id=tests.org('dashboard-test');
set role authenticated;select tests.login(1,'aal1',103);
select tests.denied('select reda_publish_reviewed(tests.id(950000),tests.id(950010),current_setting(''tests.handover_token''),null,tests.plan(8),''Reviewed fictional plan'',''Your first fictional plan'',''handover@example.test'')','42501','publication requires clinician MFA');
select tests.login(1,'aal2',103);
select set_config('tests.handover',reda_publish_reviewed(tests.id(950000),tests.id(950010),current_setting('tests.handover_token'),null,tests.plan(8),'Reviewed fictional plan','Your first fictional plan','handover@example.test')::text,false);
select tests.ok(reda_publish_reviewed(tests.id(950000),tests.id(950010),current_setting('tests.handover_token'),null,tests.plan(8),'Reviewed fictional plan','Your first fictional plan','handover@example.test')=current_setting('tests.handover')::jsonb,'lost publication receipt does not duplicate version');
select tests.denied('select reda_publish_reviewed(tests.id(950000),tests.id(950010),current_setting(''tests.handover_token''),null,tests.plan(10),''Reviewed fictional plan'',''Your first fictional plan'',''handover@example.test'')','23505','retry cannot change approved prescription');
select tests.ok(reda_dashboard_patient(tests.id(950000))->'handover'->>'delivery_state'='pending','unsent invitation is not represented as delivery');
select set_config('tests.invite',reda_reserve_invitation((current_setting('tests.handover')::jsonb->>'id')::uuid)::text,false);
select tests.denied('select reda_reserve_invitation((current_setting(''tests.handover'')::jsonb->>''id'')::uuid)','54000','parallel and immediate email retries throttled');
select tests.denied('select reda_finish_invitation((current_setting(''tests.invite'')::jsonb->>''id'')::uuid,(current_setting(''tests.invite'')::jsonb->>''lease'')::uuid,true)','42501','browser cannot forge provider acceptance');
select tests.login(950002,'aal1',950102);select tests.ok(reda_claim_patient_access()->>'status'='unavailable','wrong verified email cannot claim');
select tests.login(950003,'aal1',950103);select tests.ok(reda_claim_patient_access()->>'status'='unavailable','unconfirmed email cannot claim');
select tests.login(950001,'aal1',950101);select tests.ok(reda_claim_patient_access()->>'status'='linked','verified invited email claims only assigned patient');
select tests.ok(reda_claim_patient_access()->>'status'='linked','claim retry is harmless');
select tests.ok((select id=tests.id(950000) from reda_patients),'new patient sees own record only');
select tests.ok(reda_open_patient_plan((current_setting('tests.handover')::jsonb->>'plan_id')::uuid)->>'message'='Your first fictional plan','patient receives reviewed public message');
select tests.denied('select reda_dashboard_patient(tests.id(950000))','42501','patient cannot see internal review note');
select tests.login(1,'aal2',103);
select tests.ok(reda_dashboard_patient(tests.id(950000))->'handover'->>'opened_at' is not null,'clinician can distinguish opened from email accepted');
select tests.denied('select reda_publish_reviewed(tests.id(950000),tests.id(950011),current_setting(''tests.handover_token''),null,tests.plan(10),''Reviewed fictional update'',''Your updated fictional plan'')','40001','stale baseline cannot publish');
select set_config('tests.second',reda_publish_reviewed(tests.id(950000),tests.id(950012),reda_dashboard_patient(tests.id(950000))->>'token',(current_setting('tests.handover')::jsonb->>'plan_id')::uuid,tests.plan(10),'Reviewed fictional update','Your updated fictional plan')::text,false);
select tests.ok(current_setting('tests.second')::jsonb->>'version'='2','manual approval makes one new version');
select tests.login(950001,'aal1',950101);select tests.ok((select count(*)=1 from reda_plans),'patient only sees active version');
select tests.denied('select reda_open_patient_plan((current_setting(''tests.handover'')::jsonb->>''plan_id'')::uuid)','40001','old open receipt cannot mark replacement as read');
select tests.ok(reda_open_patient_plan((current_setting('tests.second')::jsonb->>'plan_id')::uuid)->>'message'='Your updated fictional plan','new message follows exact new plan');
select tests.login(950001,'aal1',999);select tests.denied('select reda_claim_patient_access()','42501','revoked session cannot claim');
reset role;
select tests.ok((select count(*)=2 from reda_plans where patient_id=tests.id(950000)),'exactly two immutable plan versions');
select tests.ok((select payload=tests.plan(8) and status='superseded' from reda_plans where id=(current_setting('tests.handover')::jsonb->>'plan_id')::uuid),'previous plan payload preserved');
select tests.ok(not has_function_privilege('anon','public.reda_claim_patient_access()','execute'),'anonymous claim denied');
select tests.ok(not has_table_privilege('authenticated','private.reda_handovers','select'),'internal approvals never directly exposed');
select tests.ok((select not automatic_enabled and not ai_enabled from private.reda_engine_settings),'clinical automation and external AI remain off');
set role authenticated;select tests.login(1,'aal2',103);
select set_config('tests.handover_frame',reda_approve_frame((current_setting('tests.second')::jsonb->>'plan_id')::uuid,jsonb_set(tests.policy(),'{steps}',jsonb_build_array(jsonb_build_object('id','a','label','Start','plan',tests.plan(10)),jsonb_build_object('id','b','label','Next','plan',tests.plan(12)),jsonb_build_object('id','c','label','Final','plan',tests.plan(14)))))->>'id',false);
reset role;
update reda_progression_frames set started_at=now()-interval '10 days' where id=current_setting('tests.handover_frame')::uuid;
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,created_at,completed_at,payload)
select tests.id(950200+i),tests.id(950300+i),tests.id(950000),(current_setting('tests.second')::jsonb->>'plan_id')::uuid,2,'completed',now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),'{"exercises":[{"exerciseId":"extension","status":"completed","roundsDone":1,"feedback":"okay"}]}'::jsonb from generate_series(1,3)i;
insert into reda_training_responses(request_id,session_id,patient_id,plan_id,plan_version,reported_by,created_at,answers)
select tests.id(950400+i),tests.id(950200+i),tests.id(950000),(current_setting('tests.second')::jsonb->>'plan_id')::uuid,2,tests.id(950001),now()-make_interval(days=>9-2*i),tests.answer()||'{"environment":"same"}'::jsonb from generate_series(1,3)i;
set role authenticated;select tests.login(1,'aal2',103);
select set_config('tests.handover_decision',reda_evaluate_progression(tests.id(950000),tests.id(950450))::text,false);
select tests.ok(current_setting('tests.handover_decision')::jsonb->>'action'='advance','actual saved evidence prepares a next step');
select set_config('tests.third',reda_publish_reviewed(tests.id(950000),tests.id(950451),reda_dashboard_patient(tests.id(950000))->>'token',(current_setting('tests.second')::jsonb->>'plan_id')::uuid,tests.plan(12),'Reviewed the next step','Your next reviewed step',null,(current_setting('tests.handover_decision')::jsonb->>'id')::uuid)::text,false);
select tests.ok(current_setting('tests.third')::jsonb->>'frame_continued'='true','exact approved next step retains remaining reviewed pathway');
select tests.ok((select current_step=1 and status='approved' and execution='shadow' from reda_progression_frames where id=current_setting('tests.handover_frame')::uuid),'manual approval advances one step without enabling automatic execution');
select tests.denied('select reda_publish_reviewed(tests.id(950000),tests.id(950452),reda_dashboard_patient(tests.id(950000))->>''token'',(current_setting(''tests.third'')::jsonb->>''plan_id'')::uuid,tests.plan(14),''Reviewed next step'',''Your next reviewed step'',null,(current_setting(''tests.handover_decision'')::jsonb->>''id'')::uuid)','40001','old eligible decision cannot advance a second time');
reset role;
update reda_organizations set patient_delivery_enabled=false where id=tests.org('dashboard-test');
