import test from 'node:test';import assert from 'node:assert/strict';
import {planCandidates,changeRows,handoverHTML} from '../../reda-2/plan-review.mjs';
import {firstSteps,startHTML} from '../../reda-2/first-patient-steps.mjs';
const x={id:'chair',name:'Uppresning',variantLabel:'Med stöd',side:'both',instructions:['Res dig'],dose:{sets:2,reps:8,hold:0,rest:60,tempo:4,label:'2 × 8'}};
test('EI next step preserves handover context and removes obsolete progression',()=>{const base={schema:6,goal:'Gå',careJourney:{mode:'clinic'},clinicianNote:'Råd',exercises:[x],progressionDraft:{}};const d={patient:{plan_id:'p'},cases:[],decision:{id:'d',action:'advance'},frame:{current_step:0,policy:{steps:[{}, {label:'Nästa',plan:{schema:6,exercises:[{...x,dose:{...x.dose,reps:10,label:'2 × 10'}}]}}]}}};const c=planCandidates(d,base);assert.equal(c[0].decisionId,'d');assert.equal(c[0].plan.clinicianNote,'Råd');assert.deepEqual(c[0].plan.careJourney,base.careJourney);assert.equal(c[0].plan.progressionDraft,undefined);assert.equal(base.exercises[0].dose.reps,8)});
test('changed symptoms override a previous advance decision',()=>assert.deepEqual(planCandidates({cases:[{code:'changed_symptoms'}],decision:{action:'advance'}},{exercises:[x]}),[]));
test('comparison includes side, removed exercise and new goal',()=>{const r=changeRows({goal:'A',exercises:[x,{...x,id:'other',name:'Annan'}]},{goal:'B',exercises:[{...x,side:'left'}]});assert.ok(r.some(x=>x.label==='Sida'));assert.ok(r.some(x=>x.after==='Tas bort'));assert.ok(r.some(x=>x.label==='Mål'))});
test('first steps use only current-plan sessions and their actual feedback',()=>{const state={plan:{id:'new',version:2},sessions:[{id:'old-s',plan_id:'old',completed_at:'today'}],reflections:[{session_id:'old-s'}]};assert.equal(firstSteps(state)[1].done,false);assert.equal(firstSteps(state)[2].done,false);state.sessions.push({id:'s',plan_id:'new',completed_at:'today'});assert.equal(firstSteps(state)[1].done,true);assert.equal(firstSteps(state)[2].done,false)});
test('email provider acceptance never claims opened or started',()=>{const s=handoverHTML({delivery_state:'accepted'});assert.ok(s.includes('e-posttjänsten'));assert.ok(s.includes('inte öppnat'));assert.ok(s.includes('återstår'))});
test('patient message is escaped',()=>assert.ok(startHTML({plan:{id:'p',version:1}},'<img src=x>').includes('&lt;img')));

test('reordered exercises and changed instructions are explicit in the comparison',()=>{const a={...x,id:'second',name:'Nästa övning'};const rows=changeRows({exercises:[x,a]},{exercises:[a,{...x,instructions:['Ny instruktion']}]});assert.ok(rows.some(r=>r.label==='Övningsordning'));assert.ok(rows.some(r=>r.label==='Instruktion'&&r.after==='Ny instruktion'))});
