import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
// Execute the deployed handler with fictional Supabase clients. No network or real credentials.
const source=fs.readFileSync(new URL('../../reda-2/supabase/functions/invite-patient/index.ts',import.meta.url),'utf8').replace(/^import .*\n/gm,'').replaceAll(':unknown','').replaceAll(':Request','').replace(/(get\('[^']+'\))!/g,'$1').replace('export default','globalThis.edge =');
async function run({gateError=null,accepted=false,inviteError=null,otpError=null,receiptError=null}={}){
 const calls=[];const context={Request,Response,console,Deno:{env:{get:key=>key}},corsHeaders:{},withSupabase:(_,fn)=>fn,createClient:(url,key,options)=>{calls.push({type:'client',key,options});return {rpc:async(name,args)=>{calls.push({type:name,args});return name==='reda_reserve_invitation'?{data:{id:'h',lease:'l',email:'reviewed@example.test',accepted},error:gateError}:{error:receiptError}},auth:{admin:{inviteUserByEmail:async(email,options)=>{calls.push({type:'invite',email,options});return {error:inviteError}}},signInWithOtp:async input=>{calls.push({type:'otp',input});return {error:otpError}}}}}};
 vm.createContext(context);vm.runInContext(source,context);
 const response=await context.edge.fetch(new Request('https://example.test',{method:'POST',headers:{Authorization:'Bearer fictional'},body:JSON.stringify({handover_id:'h',organization_id:'workspace',email:'unreviewed@example.test'})}));return {calls,response,body:await response.json()};
}
test('closed gate or unauthorized clinician cannot initialize the privileged mail client',async()=>{const r=await run({gateError:{code:'42501',message:'Closed'}});assert.equal(r.response.status,403);assert.equal(r.calls.filter(c=>c.type==='client').length,1);assert.ok(!r.calls.some(c=>c.type==='invite'))});
test('only reserved recipient and fixed redirect are sent to provider',async()=>{const r=await run();assert.equal(r.response.status,200);const invite=r.calls.find(c=>c.type==='invite');assert.equal(invite.email,'reviewed@example.test');assert.equal(invite.options.redirectTo,'https://www.kansei.se/reda-2/patient.html');assert.ok(r.calls.find(c=>c.type==='reda_finish_invitation').args.p_accepted)});
test('accepted receipt retry does not send again',async()=>{const r=await run({accepted:true});assert.equal(r.response.status,200);assert.ok(!r.calls.some(c=>c.type==='invite'||c.type==='otp'))});
test('existing account gets passwordless sign-in without public signup',async()=>{const r=await run({inviteError:{code:'email_exists'}});assert.equal(r.response.status,200);const otp=r.calls.find(c=>c.type==='otp');assert.equal(otp.input.email,'reviewed@example.test');assert.equal(otp.input.options.shouldCreateUser,false)});
test('provider rejection is recorded as failure and never as accepted',async()=>{const r=await run({inviteError:{code:'unexpected_failure'}});assert.equal(r.response.status,502);assert.equal(r.calls.find(c=>c.type==='reda_finish_invitation').args.p_accepted,false)});
test('lost provider receipt remains explicitly unknown',async()=>{const r=await run({receiptError:{message:'offline'}});assert.equal(r.response.status,503);assert.ok(r.body.error.includes('kvitto'))});
