const test=require('node:test'),assert=require('node:assert/strict');
global.RedaFigures={svg:()=>'<svg>fallback</svg>',animate(){},stills(){}};
require('../../reda-2/motion-specs.js');require('../../reda-2/reference-motion.js');require('../../reda-2/motion-v4.js');
const M=RedaMotionV4,dist=(a,b)=>Math.hypot(a[0]-b[0],a[1]-b[1]);
test('all fourteen movements retain fixed anatomical segment lengths and finite artwork',()=>{assert.equal(M.keys.length,14);for(const key of M.keys)for(let i=0;i<=100;i++){const p=M.pose(key,i/100);for(const [a,b,len] of [[p.hip,p.knee,72],[p.knee,p.ankle,72],[p.shoulder,p.hip,80],[p.shoulder,p.elbow,p.armLengths?.[0]||38],[p.elbow,p.hand,p.armLengths?.[1]||38]])assert.ok(Math.abs(dist(a,b)-len)<.001,key+' '+i);assert.doesNotMatch(M.svg(key,i/100),/NaN|Infinity/);}});
test('support release is continuous and advanced contact points do not slide',()=>{let old;for(let i=0;i<=1000;i++){const p=M.pose('sit-to-stand.support',i/1000);if(old)assert.ok(dist(p.hand,old)<1,'hand cannot jump at release');old=p.hand;const b=M.pose('split-squat.rfess-loaded',i/1000);assert.deepEqual(b.ankle,[345,364]);assert.deepEqual(b.back.ankle,[208,306]);const l=M.pose('leg-press.bilateral',i/1000);assert.deepEqual(l.hip,[230,290]);}});
test('side stays explicit without mirroring equipment; gradient IDs do not collide between cards',()=>{const a=M.svg('bridge.pause',1,'right'),b=M.svg('bridge.pause',1,'right');assert.doesNotMatch(a,/scale\(-1/);assert.match(a,/data-side="right"/);assert.match(a,/Höger sida/);assert.notEqual(a.match(/data-paint="([^"]+)/)[1],b.match(/data-paint="([^"]+)/)[1]);assert.equal(M.svg('bridge.single'),'<svg>fallback</svg>');});
test('knee extension retains a rigid ankle angle and calf toe contacts stay above the floor',()=>{const angle=(a,b)=>Math.atan2(b[1]-a[1],b[0]-a[0]);for(let i=0;i<=100;i++){const t=i/100,k=M.pose('knee-extension.seated',t),c=M.pose('calf-raise.bilateral',t);assert.ok(Math.abs((angle(k.knee,k.ankle)-angle(k.heel,k.toe))-Math.PI/2)<1e-8);assert.ok(c.heel[1]<=378);assert.equal(c.toe[1],378);assert.ok(Math.abs(dist(c.ankle,c.toe)-dist(M.pose('calf-raise.bilateral',0).ankle,c.toe))<1e-8)}});
test('bridge endpoint stays close to the shoulder hip knee line',()=>{const q=M.pose('bridge.pause',1),a=[q.hip[0]-q.shoulder[0],q.hip[1]-q.shoulder[1]],b=[q.knee[0]-q.hip[0],q.knee[1]-q.hip[1]];assert.ok(Math.acos((a[0]*b[0]+a[1]*b[1])/(80*72))*180/Math.PI<5)});
test('all five reference families keep head and feet inside their camera throughout the motion',()=>{for(const key of ['sit-to-stand.support','knee-extension.pause','calf-raise.bilateral','bridge.pause','step-up.supported'])for(let i=0;i<=100;i++){const q=M.pose(key,i/100),[x,y,w,h]=M.camera(key);for(const p of [q.head,q.hip,q.heel,q.toe,q.back.heel,q.back.toe]){assert.ok(p[0]>=x&&p[0]<=x+w,key);assert.ok(p[1]>=y&&p[1]<=y+h,key)}if(!q.mat)assert.ok(q.head[1]-30>=y,key+' head')}});

test('step-up trailing foot clears the riser before entering the step surface',()=>{for(let i=0;i<=1000;i++){const q=M.pose('step-up.supported',i/1000);for(const p of [q.back.heel,q.back.toe])if(p[0]>=302)assert.ok(p[1]<=330,'foot intersects step at '+i)}});

test('pause and slow-return variants have distinct, continuous demonstration timing',()=>{assert.equal(M.phaseState(.6,'bridge.pause').phase,'end');assert.equal(M.phaseState(.6,'bridge.bilateral').phase,'back');assert.equal(M.phaseState(.44,'sit-to-stand.tempo').phase,'back');assert.equal(M.phaseState(.44,'sit-to-stand.free').phase,'out');for(const k of M.keys){let prev=0;for(let i=0;i<=1000;i++){const f=M.phaseState(i/1000,k);assert.ok(f.position>=0&&f.position<=1);assert.ok(Math.abs(f.position-prev)<.01);prev=f.position}}});

test('chair rise arms retain adult reach and supported elbows stay behind the wrist at the start',()=>{for(const k of ['sit-to-stand.support','sit-to-stand.free','sit-to-stand.tempo']){const start=M.pose(k,0),end=M.pose(k,1);assert.ok(end.hand[1]>end.hip[1]+5,k+' wrist must reach below hip');assert.deepEqual(end.armLengths,[45,45]);if(k.endsWith('support'))assert.ok(start.elbow[0]<start.hand[0]);}});
