import test from 'node:test';import assert from 'node:assert/strict';
import {patientHistory} from '../../reda-2/patient-history.mjs';
const event=(id,extra={})=>({id,occurred_at:'2026-09-13T10:00:00Z',category:'training',title:id.startsWith('end:')?'Pass genomfört':'Pass påbörjat',detail:'Dagens pass',plan_id:'p',plan_version:1,...extra});
const context={sessions:[{id:'s',plan_id:'p',plan_version:1,status:'completed',completed_at:'2026-09-13T10:00:00Z',payload:{exercises:[{status:'completed'},{status:'skipped'}]}}],reflections:[{id:'r',session_id:'s',plan_id:'p',plan_version:1,created_at:'2026-09-13T10:01:00Z',answers:{barrier:'execution',support:'yes'}}],responses:[{id:'a',session_id:'s',plan_id:'p',plan_version:1}]};
test('one pass combines start, end and only replies linked to its exact plan version',()=>{const xs=[event('end:s'),event('start:s'),event('reflection:r',{category:'feedback'}),event('response:a',{category:'feedback'})],before=JSON.stringify(xs);const result=patientHistory(xs,context);assert.equal(result.length,1);assert.equal(result[0].id,'session:s');assert.match(result[0].detail,/1 av 2/);assert.match(result[0].detail,/Osäker på utförandet/);assert.match(result[0].detail,/bett om hjälp/);assert.match(result[0].detail,/Uppföljning efter passet/);assert.equal(JSON.stringify(xs),before)});
test('pagination and overlapping pages do not duplicate a session',()=>{const page=[event('end:s')];assert.equal(patientHistory(page).length,1);assert.equal(patientHistory([...page,event('start:s'),event('end:s')]).length,1)});
test('same-day passes and plan versions remain separate',()=>{assert.equal(patientHistory([event('end:s'),event('end:s2')]).length,2);assert.equal(patientHistory([event('end:s'),event('start:s',{plan_version:2})]).length,2)});
test('unlinked feedback is kept; mismatched versions are never attached',()=>{const result=patientHistory([event('end:s'),event('reflection:unknown',{category:'feedback'}),event('reflection:r',{category:'feedback',plan_version:2})],context);assert.equal(result.length,3);assert.equal(result.find(e=>e.plan_version===2).detail,'Dagens pass')});
test('plan changes and contact are preserved and time ordered',()=>{const result=patientHistory([event('start:s'),event('plan:new',{category:'plans',occurred_at:'2026-09-14T10:00:00Z'}),event('message:new',{category:'contact',occurred_at:'2026-09-15T10:00:00Z'})]);assert.deepEqual(result.map(e=>e.id),['message:new','plan:new','session:s']);assert.equal(result[2].title,'Påbörjat pass')});
