"""Reviewed fictional import, duplicate and clinical handoff journeys."""
import unittest
from pathlib import Path
from playwright.sync_api import expect
from dashboard_browser_test import T as DashboardBase,MOCK,ROOT
EXTRA="""
window.intakes=[];window.intakeFail=false;window.duplicateMode=false;window.profileReadFail=false;
export async function savePatientProfile(input){window.intakes.push(input);await new Promise(r=>setTimeout(r,150));if(window.intakeFail)throw Error('Fiktivt nätverksfel');if(window.duplicateMode&&!input.duplicateToken)return {status:'duplicates',duplicate_token:'confirmed-match',matches:[{patient_id:'a-2',display_name:'Fiktiv patient 0002',email:'family@example.test',patient_status:'active',connected:true,exact_source:false}]};window.lastProfile=input.profile;return {status:'saved',patient:{id:'a-1001',display_name:input.profile.name,status:'active'},profile:{...input.profile,revision:1}}}
export async function patientProfile(id){if(window.profileReadFail)throw Error('Fiktivt läsfel');return {...(window.lastProfile||{name:'Fiktiv patient 0002',focus:'Vänster knä',goal:'Gå till arbetet',email:'fictional@example.test'}),revision:1}}
"""
class T(DashboardBase):
 def setUp(self):
  self.c=self.browser.new_context(viewport={'width':1440,'height':1000});self.c.route('**/*',lambda r:r.continue_()if r.request.url.startswith(self.origin)else r.abort());self.c.route('**/secure-browser.mjs*',lambda r:r.fulfill(status=200,content_type='text/javascript',body=MOCK+EXTRA));self.p=self.c.new_page();self.errors=[];self.p.on('pageerror',lambda e:self.errors.append(str(e)));self.p.goto(self.origin+'/reda-2/klinik-live.html');self.p.locator('[data-new]').wait_for()
 def test_intake_contact_and_goal_follow_patient_into_plan(self):
  self.p.locator('[data-new]').click();d=self.p.locator('dialog');expect(d).to_be_visible();expect(self.p.locator('#workspaceSelect')).to_be_disabled();d.locator('[name="name"]').fill('Fiktiv Åsa');d.locator('[name="email"]').fill('asa@example.test');d.locator('[name="phone"]').fill('070 123 45 67');d.locator('[name="focus"]').fill('Vänster knä');d.locator('[name="goal"]').fill('Gå i trappor');d.locator('[data-save]').click();expect(self.p.locator('dialog')).to_have_count(0);expect(self.p.locator('#patientTitle')).to_have_text('Fiktiv Åsa');expect(self.p.locator('#goal')).to_have_value('Gå i trappor');expect(self.p.locator('#patientEmail')).to_have_value('asa@example.test');expect(self.p.locator('#activate')).to_be_disabled();self.assertEqual(self.p.evaluate('window.intakes.length'),1)
 def test_import_selects_only_reviewed_person_and_keeps_retry_identity(self):
  self.p.locator('[data-new]').click();self.p.locator('[data-mode="file"]').click();content='Förnamn;Efternamn;E-post;Telefon;Kund-ID\nÅsa;Fiktiv;asa@example.test;0701234567;00042\nBo;Fiktiv;bo@example.test;0701234568;00043';self.p.locator('[data-file]').set_input_files({'name':'fictional.csv','mimeType':'text/csv','buffer':content.encode()});expect(self.p.locator('[data-file-row]')).to_have_count(2);self.assertEqual(self.p.evaluate('window.intakes.length'),0);self.p.locator('[data-file-search]').fill('00043');expect(self.p.locator('[data-file-row]')).to_have_count(1);self.p.locator('[data-file-row]').click();expect(self.p.locator('dialog [name="name"]')).to_have_value('Bo Fiktiv');expect(self.p.locator('[name="external_id"]')).to_have_value('00043');self.p.evaluate('window.intakeFail=true');self.p.locator('[data-save]').click();expect(self.p.locator('dialog [role="alert"]')).to_contain_text('nätverksfel');self.p.evaluate('window.intakeFail=false');self.p.locator('[data-save]').click();expect(self.p.locator('dialog')).to_have_count(0);self.assertEqual(self.p.evaluate('window.intakes[0].requestId'),self.p.evaluate('window.intakes[1].requestId'));self.assertEqual(self.p.evaluate('window.intakes[1].profile.name'),'Bo Fiktiv');self.assertFalse(self.p.evaluate("JSON.stringify(window.intakes).includes('asa@example.test')"));self.assertEqual(self.p.evaluate('localStorage.length'),0)
 def test_duplicate_requires_review_and_existing_patient_can_be_opened(self):
  self.p.locator('[data-new]').click();self.p.locator('dialog [name="name"]').fill('Fiktiv person');self.p.locator('dialog [name="email"]').fill('family@example.test');self.p.evaluate('window.duplicateMode=true');self.p.locator('[data-save]').click();expect(self.p.locator('.intake-duplicate')).to_be_visible();self.p.locator('[data-distinct]').check();expect(self.p.locator('[data-distinct]')).to_be_checked();self.p.locator('[data-save]').click();expect(self.p.locator('dialog')).to_have_count(0);self.assertEqual(self.p.evaluate('window.intakes[1].duplicateToken'),'confirmed-match')
 def test_edit_profile_and_intake_mobile_layout(self):
  self.p.locator('[data-detail="a-2"]').click();self.p.locator('[data-edit-profile]').click();expect(self.p.locator('dialog [name="focus"]')).to_have_value('Vänster knä');self.p.locator('dialog [name="handover"]').fill('Fiktiv notering inför kontakten');out=ROOT/'reda2-test-results';out.mkdir(exist_ok=True);self.p.screenshot(path=str(out/'patient-intake-desktop.png'),full_page=True);self.p.set_viewport_size({'width':390,'height':844});self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.p.screenshot(path=str(out/'patient-intake-mobile.png'),full_page=True);self.p.locator('[data-save]').click();expect(self.p.locator('dialog')).to_have_count(0);expect(self.p.locator('.dash-message')).to_contain_text('sparade');self.assertEqual(self.p.evaluate('window.intakes[0].patientId'),'a-2');self.assertEqual(self.p.evaluate('window.intakes[0].revision'),1)
for name in list(DashboardBase.__dict__):
 if name.startswith('test_')and name not in T.__dict__:setattr(T,name,None)
del DashboardBase
if __name__=='__main__':unittest.main()
