\ir ../../reda-2/secure/patient-basis.sql
\ir ../../reda-2/secure/ei-mandates.sql
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(799001),'resolve_cases','Fictional support flow closed before measuring the goal.');
select tests.ok(reda_dashboard_patient(tests.id(700003))?'basis','clinical overview has the source-bound patient basis');
select tests.ok((reda_ei_settings()->>'auto_followup')::boolean,'existing automatic task mandate defaults on');
select set_config('tests.basis_token',reda_dashboard_patient(tests.id(700003))->>'token',false);
select tests.login(9,'aal1',109);
select tests.ok(not(reda_my_checkins(tests.id(700003))?'profile'),'patient cannot read internal patient profile notes');
select set_config('tests.basis_answers','{"ability":5,"minutes":20,"equipment":"home","band":false,"floorOK":true}',false);
select set_config('tests.basis_report',reda_submit_checkin(tests.id(796000),tests.id(799002),current_setting('tests.basis_answers')::jsonb)::text,false);
select tests.ok(reda_submit_checkin(tests.id(796000),tests.id(799002),current_setting('tests.basis_answers')::jsonb)::text=current_setting('tests.basis_report'),'lost report receipt is idempotent');
select tests.denied('select reda_submit_checkin(tests.id(796000),tests.id(799002),jsonb_set(current_setting(''tests.basis_answers'')::jsonb,''{ability}'',''6''))','23505','retry cannot rewrite a saved goal score');
select tests.denied('select reda_submit_checkin(tests.id(796000),tests.id(799099),current_setting(''tests.basis_answers'')::jsonb||''{"ability":11}'')','22023','out of range score rejected');
select tests.denied('select reda_submit_checkin(tests.id(796000),tests.id(799099),current_setting(''tests.basis_answers'')::jsonb||''{"approved":true}'')','22023','patient cannot add clinical approval fields');
select tests.ok(reda_my_checkins(tests.id(700003))->'baseline'->'answers'->>'ability'='5','first score anchors the same goal');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.denied('select reda_dashboard_act(tests.id(700003),current_setting(''tests.basis_token''),tests.id(799003),''follow_up'',''Stale input must not be approved.'',current_date+1)','40001','even neutral new context invalidates old approval');
select tests.login(9,'aal1',109);
select reda_submit_checkin(tests.id(796000),tests.id(799004),jsonb_set(current_setting('tests.basis_answers')::jsonb,'{ability}','3'));
select tests.ok(reda_my_checkins(tests.id(700003))->'latest'->'answers'->>'ability'='3','latest score follows the actual saved report');
select tests.ok(reda_my_checkins(tests.id(700003))->'baseline'->'answers'->>'ability'='5','later scores retain baseline');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_dashboard_patient(tests.id(700003))->'cases')c where c->'checkin'->'answers'->>'ability'='3' and c->>'plan_version'='50'),'clinical decision includes original score and plan version');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_clinic_inbox()->'cases')c where c->'checkin'->'answers'->>'ability'='3'),'secondary inbox retains source evidence');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_activity_log(tests.id(700003),'feedback')->'events')e where e->>'title'='Målskattning och vardagsförutsättningar sparade'),'goal measurement appears in activity log');
select set_config('tests.mandate_off',reda_save_ei_mandate(tests.id(799010),0,false)::text,false);
select tests.ok(reda_save_ei_mandate(tests.id(799010),0,false)::text=current_setting('tests.mandate_off'),'lost mandate receipt does not duplicate change');
select tests.denied('select reda_save_ei_mandate(tests.id(799011),0,true)','40001','stale owner setting rejected');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(799012),'resolve_cases','Fictional goal response reviewed and handled.');
select tests.login(9,'aal1',109);
select reda_submit_checkin(tests.id(796000),tests.id(799013),jsonb_set(current_setting('tests.basis_answers')::jsonb,'{ability}','2'));
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'patient'->>'followup_status'='completed','disabled task mandate does not auto-schedule');
select tests.ok((reda_dashboard_patient(tests.id(700003))->'patient'->>'open_count')::int>0,'disabled scheduling never hides new patient signals');
select reda_save_ei_mandate(tests.id(799014),1,true);
select tests.login(9,'aal1',109);
select reda_submit_checkin(tests.id(796000),tests.id(799015),jsonb_set(current_setting('tests.basis_answers')::jsonb,'{ability}','1'));
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'patient'->>'followup_status'='waiting','restored mandate auto-schedules new signals');
select tests.login(2,'aal1',101);select tests.denied('select reda_my_checkins(tests.id(700003))','42501','other patient cannot read goal history');
select tests.denied('select reda_submit_checkin(tests.id(796000),tests.id(799099),current_setting(''tests.basis_answers'')::jsonb)','42501','other patient cannot submit a goal score');
select tests.login(9,'aal1',999);select tests.denied('select reda_my_checkins(tests.id(700003))','42501','revoked patient session denied');
select tests.login(9,'aal1',109);select tests.denied('select reda_save_ei_mandate(tests.id(799099),2,false)','42501','patient cannot change clinic mandate');
select tests.login(1,'aal1',103);select tests.denied('select reda_ei_settings()','42501','mandates require MFA');
select tests.login(1,'aal2',103);select tests.workspace('clinic-b');select tests.denied('select reda_dashboard_patient(tests.id(700003))','42501','basis cannot cross workspaces');
reset role;
select tests.ok((select count(*)=1 from reda_patient_checkins where request_id=tests.id(799002)),'report idempotency preserves one row');
select tests.ok(not has_function_privilege('anon','public.reda_my_checkins(uuid)','execute'),'anonymous goal access denied');
select tests.ok(not has_function_privilege('authenticated','private.reda_patient_basis(uuid)','execute'),'internal source aggregate denied');
select tests.ok((select not automatic_enabled and not ai_enabled from private.reda_engine_settings),'clinical progression and external AI unchanged');
-- New goal must start a separate comparison even for the same patient.
update reda_plans set status='superseded'where id=tests.id(796000);
insert into reda_plans(id,patient_id,clinician_id,version,status,payload)values(tests.id(799100),tests.id(700003),tests.id(1),51,'active',jsonb_set(tests.plan(8),'{goal}','"Ett annat fiktivt mål"'));
set role authenticated;select tests.login(9,'aal1',109);
select tests.ok(reda_my_checkins(tests.id(700003))->'baseline'='null'::jsonb,'changed goal never reuses old baseline');
select reda_submit_checkin(tests.id(799100),tests.id(799101),current_setting('tests.basis_answers')::jsonb);
select tests.ok(reda_my_checkins(tests.id(700003))->'baseline'->'answers'->>'ability'='5','new goal has its own first score');
select tests.denied('select reda_submit_checkin(tests.id(796000),tests.id(799102),current_setting(''tests.basis_answers'')::jsonb)','40001','superseded plan cannot accept new goal report');
reset role;
update reda_memberships set role='admin'where organization_id=(select id from reda_organizations where slug='dashboard-test')and user_id=tests.id(1);
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.denied('select reda_save_ei_mandate(tests.id(799103),2,false)','42501','clinical admin cannot change owner mandate');
reset role;
update reda_memberships set role='owner'where organization_id=(select id from reda_organizations where slug='dashboard-test')and user_id=tests.id(1);
