-- Fictional records only; follows dashboard and conversation fixtures.
\ir ../../reda-2/secure/patient-intake.sql
set role authenticated;
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select set_config('tests.intake',jsonb_build_object('name','Fiktiv Åsa Import','email','ASA@example.test','phone','070 123 45 67','focus','Vänster knä','goal','Gå i trappor','handover','Arbetar natt','next_contact',(current_date+2)::text,'source','bokadirekt','external_id','00042')::text,false);
select set_config('tests.intake_result',reda_save_patient_profile(null,tests.id(780001),current_setting('tests.intake')::jsonb)::text,false);
select set_config('tests.intake_pid',current_setting('tests.intake_result')::jsonb->'patient'->>'id',false);
select tests.ok(current_setting('tests.intake_result')::jsonb->>'status'='saved','reviewed intake creates patient and profile atomically');
select tests.ok(reda_save_patient_profile(null,tests.id(780001),current_setting('tests.intake')::jsonb)=current_setting('tests.intake_result')::jsonb,'retry returns same patient');
select tests.denied('select reda_save_patient_profile(null,tests.id(780001),jsonb_build_object(''name'',''Another person''))','23505','request id cannot create a different patient');
select tests.ok(reda_patient_profile(current_setting('tests.intake_pid')::uuid)->>'email'='asa@example.test','contacts normalized and available to assigned clinician');
select tests.ok(reda_dashboard('ASA@EXAMPLE.TEST','all')->>'total'='1','search by imported email');
select tests.ok(reda_dashboard('1234567','all')->>'total'='1','phone search ignores formatting');
select tests.ok(reda_dashboard('trappor','all')->'patients'->0->>'care_goal'='Gå i trappor','goal visible and searchable without opening chart');
select tests.ok(reda_dashboard('00042','no_plan')->>'total'='1','new imported patient enters preparation queue');
select tests.ok(reda_dashboard('00042','upcoming')->>'total'='1','planned contact is visible before a plan exists');
select tests.ok(reda_dashboard('00042','all')->'patients'->0->>'connected'='false','intake does not invite or connect patient');
select set_config('tests.dup',reda_save_patient_profile(null,tests.id(780002),current_setting('tests.intake')::jsonb)::text,false);
select tests.ok(current_setting('tests.dup')::jsonb->>'status'='duplicates','repeat import stops before creating duplicate');
select tests.ok(reda_save_patient_profile(null,tests.id(780002),current_setting('tests.intake')::jsonb,0,current_setting('tests.dup')::jsonb->>'duplicate_token')->>'status'='duplicates','exact source id cannot be overridden');
select set_config('tests.family',jsonb_build_object('name','Fiktiv Bo Import','email','asa@example.test')::text,false);
select set_config('tests.dup',reda_save_patient_profile(null,tests.id(780003),current_setting('tests.family')::jsonb)::text,false);
select tests.ok(current_setting('tests.dup')::jsonb->>'status'='duplicates','shared email asks clinician to distinguish people');
select tests.ok(reda_save_patient_profile(null,tests.id(780003),current_setting('tests.family')::jsonb,0,current_setting('tests.dup')::jsonb->>'duplicate_token')->>'status'='saved','reviewed different family member can share contact address');
select set_config('tests.old_token',reda_dashboard_patient(current_setting('tests.intake_pid')::uuid)->>'token',false);
select set_config('tests.edit',jsonb_build_object('name','Fiktiv Åsa Import','email','asa.new@example.test','phone','070 123 45 67','focus','Vänster knä','goal','Gå i trappor','next_contact',current_date::text,'source','bokadirekt','external_id','00042')::text,false);
select tests.ok(reda_save_patient_profile(current_setting('tests.intake_pid')::uuid,tests.id(780004),current_setting('tests.edit')::jsonb,1)->>'status'='saved','profile update preserves patient identity');
select tests.ok(reda_dashboard_patient(current_setting('tests.intake_pid')::uuid)->>'token'<>current_setting('tests.old_token'),'profile update invalidates old decision context');
select tests.ok(reda_dashboard('00042','priority')->>'total'='1','contact due today needs attention even without active plan');
select tests.denied('select reda_save_patient_profile(current_setting(''tests.intake_pid'')::uuid,tests.id(780005),current_setting(''tests.edit'')::jsonb,1)','40001','concurrent stale edit cannot overwrite newer profile');
select tests.denied('select reda_patient_profile(tests.id(799999))','42501','other assignment is private');
select tests.denied('select reda_save_patient_profile(tests.id(799999),tests.id(780006),jsonb_build_object(''name'',''Intrusion''))','42501','other assignment cannot be edited');
select tests.denied('select * from private.reda_patient_profiles','42501','raw contact table unavailable');
select tests.denied('select private.reda_intake_matches(jsonb_build_object(''email'',''asa.new@example.test''))','42501','duplicate helper cannot bypass ownership');
select tests.denied('select reda_save_patient_profile(null,tests.id(780007),jsonb_build_object(''name'',''Bad contact'',''email'',''broken''))','22023','invalid contact rejected');
select tests.denied('select reda_save_patient_profile(null,tests.id(780007),jsonb_build_object(''name'',''Bad date'',''next_contact'',''2026-02-31''))','22023','invalid date rejected');
select tests.workspace('clinic-b');
select tests.denied('select reda_patient_profile(current_setting(''tests.intake_pid'')::uuid)','42501','same clinician other workspace cannot read profile');
select tests.ok(reda_dashboard('asa.new@example.test','all')->>'total'='0','search does not reveal other workspace contact');
select tests.workspace('reda-direct');
select tests.denied('select reda_save_patient_profile(null,tests.id(780008),jsonb_build_object(''name'',''Direct account''))','42501','nonclinical role cannot create patient');
select tests.workspace('dashboard-test');select tests.login(1,'aal1',103);
select tests.denied('select reda_save_patient_profile(null,tests.id(780008),jsonb_build_object(''name'',''No MFA''))','42501','MFA required for intake');
select tests.login(4,'aal2',104);
select tests.ok(reda_dashboard('asa.new@example.test','all')->>'total'='0','other clinician cannot search contacts');
select tests.denied('select reda_patient_profile(current_setting(''tests.intake_pid'')::uuid)','42501','profile cannot leak to another clinician');
reset role;
select tests.ok((select auth_user_id is null from reda_patients where id=current_setting('tests.intake_pid')::uuid),'patient activation gate untouched');
select tests.ok(not exists(select 1 from reda_plans where patient_id=current_setting('tests.intake_pid')::uuid),'intake alone never assigns a clinical plan');
