"""Both authoring paths, with fictional services and no patient-side delivery."""
import unittest
from playwright.sync_api import expect
from dashboard_browser_test import T as DashboardBase,MOCK,ROOT
MOCK=MOCK.replace("export async function patientSummary(id){return {plans:[],sessions:[],responses:[]}}", "export async function patientSummary(id){return {plans:window.drafts.filter(p=>p.patient_id===id),sessions:[],responses:[]}}")+"""
window.drafts=[];window.templates=[];window.favorites=[];window.librarySlow=false;window.templateCalls=[];
export async function patientProfile(){return {focus:'Vänster knä',goal:'Kunna gå i trappor',email:'fictional@example.test'}}
export async function authoringLibrary(favorites=null){const org=current;await new Promise(r=>setTimeout(r,window.librarySlow?700:10));if(favorites)window.favorites=favorites;return {favorites:window.favorites,templates:window.templates.filter(t=>t.org===org&&!t.archived)}}
export async function savePlanTemplate(input){window.templateCalls.push(input);const t={...input,org:current,revision:input.revision+1};window.templates=[t,...window.templates.filter(x=>x.id!==t.id)];return t}
export async function createDraft(patientId,payload){const p={id:'draft-'+(window.drafts.length+1),patient_id:patientId,payload:structuredClone(payload),status:'draft',version:window.drafts.length+1};window.drafts.push(p);return p}
"""
class T(DashboardBase):
 def setUp(self):
  self.c=self.browser.new_context(viewport={'width':1440,'height':1000});self.c.route('**/*',lambda r:r.continue_()if r.request.url.startswith(self.origin)else r.abort());self.c.route('**/secure-browser.mjs*',lambda r:r.fulfill(status=200,content_type='text/javascript',body=MOCK));self.p=self.c.new_page();self.errors=[];self.p.on('pageerror',lambda e:self.errors.append(str(e)));self.p.goto(self.origin+'/reda-2/klinik-live.html');self.open_patient()
 def open_patient(self):
  self.p.locator('[data-detail="a-2"]').click();self.p.locator('[data-full]').click();expect(self.p.locator('[data-add="chair"]')).to_be_visible(timeout=6000)
 def add(self,id):
  name=self.p.evaluate('(id)=>RedaData.exercises.find(x=>x.id===id).name',id);self.p.locator('#planAuthoring [data-search]').fill(name);self.p.locator('[data-add="'+id+'"]').click()
 def save(self):
  self.p.locator('#saveDraft').click();expect(self.p.locator('#deliveryStatus')).to_contain_text('Utkast sparat');return self.p.evaluate('window.drafts.at(-1).payload')
 def test_manual_three_exercises_edit_side_schedule_save_and_resume(self):
  expect(self.p.locator('#planMeta')).to_have_text('0 övningar');expect(self.p.locator('[data-included]')).not_to_be_checked();expect(self.p.locator('#blueprint')).to_have_value('');expect(self.p.locator('#goal')).to_have_value('Kunna gå i trappor');expect(self.p.locator('#saveDraft')).to_be_disabled()
  for id in ['chair','extension','bridge']:self.add(id)
  self.p.locator('[data-side]').select_option('left');self.p.locator('[data-day="2"]').click();self.p.locator('[data-included]').check();self.p.locator('.prescription-edit').nth(1).locator('summary').click();self.p.locator('[data-edit="reps"][data-index="1"]').fill('7');self.p.locator('[data-edit="reps"][data-index="1"]').press('Tab')
  p=self.save();self.assertEqual(len(p['exercises']),3);self.assertEqual(p['exercises'][1]['side'],'left');self.assertEqual(p['exercises'][0]['side'],'simultaneous');self.assertEqual(p['exercises'][1]['dose']['reps'],7);self.assertIn(2,p['schedule']['days']);self.assertTrue(p['authoring']['includedInVisit']);expect(self.p.locator('#activate')).to_be_disabled()
  self.p.locator('#backToDashboard').click();self.open_patient();expect(self.p.locator('#planMeta')).to_have_text('3 övningar');self.assertEqual(self.save()['exercises'][1]['dose']['reps'],7)
 def test_switching_paths_preserves_work_and_ei_proposal_requires_apply(self):
  self.add('extension');self.p.locator('[data-mode="suggest"]').click();expect(self.p.locator('#planMeta')).to_have_text('1 övningar');expect(self.p.locator('[data-generate]')).to_be_disabled();expect(self.p.locator('[data-ready]')).to_contain_text('Välj klinisk riktning');self.p.locator('[data-profile="home"]').click();self.p.locator('[data-direction="knee_pf"]').click();self.p.locator('[data-generate]').click();expect(self.p.locator('[data-choice]')).to_have_count(3);self.p.locator('[data-choice="0"]').click();expect(self.p.locator('[data-candidate]')).to_be_visible();expect(self.p.locator('#planMeta')).to_have_text('1 övningar');self.p.locator('[data-apply]').click();self.assertGreater(self.p.locator('.plan-exercise').count(),1);expect(self.p.locator('[data-mode="manual"]')).to_have_attribute('aria-pressed','true');p=self.save();self.assertEqual(p['context']['blueprintId'],'knee_pf');self.assertEqual(p['context']['equipment'],'home')
 def test_adaptation_never_hides_unresolved_exercise_and_removal_clears_warning(self):
  self.add('chair');self.add('bridge');self.p.locator('[data-adapt="floor"]').click();expect(self.p.locator('[data-candidate]')).to_contain_text('välj en ersättning');self.p.locator('[data-apply]').click();expect(self.p.locator('#saveDraft')).to_be_disabled();self.p.locator('[data-remove="1"]').click();expect(self.p.locator('#saveDraft')).to_be_enabled();self.assertEqual(self.save()['warnings'],[])
 def test_stale_proposal_does_not_overwrite_a_new_manual_edit_and_undo_works(self):
  self.add('chair');self.p.locator('[data-adapt="band"]').click();self.p.locator('[data-day="2"]').click();expect(self.p.locator('[data-candidate]')).not_to_be_visible();self.p.locator('[data-undo]').click();expect(self.p.locator('[data-day="2"]')).to_have_attribute('aria-pressed','false');self.p.locator('[data-adapt="band"]').click();self.p.locator('#goal').fill('Ett nytt mål');self.p.locator('[data-apply]').click();expect(self.p.locator('#planAuthoring [role="alert"]')).to_contain_text('Planen har ändrats');self.add('extension');self.p.locator('[data-up="1"]').click();expect(self.p.locator('.plan-exercise b').first).to_have_text('Benspark från stol');self.p.locator('[data-undo]').click();expect(self.p.locator('.plan-exercise b').first).to_have_text('Uppresning från stol')
 def test_template_and_favorite_reuse_without_patient_load_or_note(self):
  self.add('extension');self.p.locator('[data-star="extension"]').click();expect(self.p.locator('[data-star="extension"]')).to_have_attribute('aria-pressed','true');self.p.locator('.prescription-edit summary').click();self.p.locator('[data-edit="prescribedLoad"]').fill('INDIVIDUAL LOAD');self.p.locator('[data-edit="prescribedLoad"]').press('Tab');self.p.locator('#note').fill('PRIVATE NOTE');self.p.locator('.authoring-reuse summary').click();self.p.locator('[data-template-title]').fill('Min testmall');self.p.locator('[data-template-save]').click();expect(self.p.locator('[data-template]')).to_have_count(1);payload=self.p.evaluate('JSON.stringify(window.templateCalls[0].payload)');self.assertNotIn('INDIVIDUAL',payload);self.assertNotIn('PRIVATE',payload);self.assertNotIn('trappor',payload);self.p.locator('[data-remove="0"]').click();self.p.locator('[data-template]').click();self.p.locator('[data-apply]').click();self.assertEqual(len(self.save()['exercises']),1);self.assertNotIn('prescribedLoad',self.p.evaluate('window.drafts.at(-1).payload.exercises[0]'))
 def test_motion_patient_preview_and_responsive_layout(self):
  self.add('chair');self.add('extension');out=ROOT/'reda2-test-results';out.mkdir(exist_ok=True);self.p.evaluate('scrollTo({top:0,behavior:"instant"})');self.p.screenshot(path=str(out/'plan-authoring-desktop.png'),full_page=True);self.p.locator('[data-row-preview="0"]').click();expect(self.p.locator('dialog svg')).to_have_count(1);self.p.locator('[data-play]').click();expect(self.p.locator('[data-play]')).to_have_text('Pausa');self.p.locator('[data-close-preview]').click();self.p.locator('[data-preview]').click();expect(self.p.locator('dialog')).to_contain_text('Kunna gå i trappor');self.p.locator('[data-close-preview]').click();self.p.set_viewport_size({'width':900,'height':1000});self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.assertLess(abs(self.p.locator('.plan-panel').bounding_box()['x']-self.p.locator('.work-main').bounding_box()['x']),2);self.p.set_viewport_size({'width':390,'height':844});self.p.evaluate('scrollTo({top:0,behavior:"instant"})');self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.p.screenshot(path=str(out/'plan-authoring-mobile.png'),full_page=True);self.p.locator('[data-plan-jump]').click();expect(self.p.locator('#planMeta')).to_be_in_viewport();self.p.locator('[data-mode="suggest"]').click();self.p.locator('[data-profile="home"]').click();self.p.locator('[data-direction="knee_pf"]').click();self.p.locator('[data-generate]').click();self.p.set_viewport_size({'width':1440,'height':1000});self.p.evaluate('scrollTo({top:0,behavior:"instant"})');self.p.screenshot(path=str(out/'plan-authoring-ei.png'),full_page=True)
for name in list(DashboardBase.__dict__):
 if name.startswith('test_')and name not in T.__dict__:setattr(T,name,None)
del DashboardBase
if __name__=='__main__':unittest.main()
