"""Adaptive, evidence-based process indicators using fictional API fixtures."""
import unittest
from playwright.sync_api import expect
from plan_authoring_browser_test import T as AuthoringBase,ROOT
class T(AuthoringBase):
 def test_complete_preparation_and_changes_invalidate_review_and_saved_state(self):
  panel=self.p.locator('#patientProcess');expect(panel).to_be_visible();panel.locator('[data-process-step="context"] button').click();self.p.locator('[data-context-profile="home"]').click();expect(panel.locator('[data-process-step="context"]')).to_have_attribute('data-state','done');self.add('chair');panel.locator('[data-process-step="followup"] button').click();self.p.locator('[data-review-days="14"]').click();expect(panel.locator('[data-process-step="followup"]')).to_have_attribute('data-state','done');self.save();expect(panel.locator('[data-process-step="saved"]')).to_have_attribute('data-state','done');expect(panel.locator('[data-process-step="review"]')).to_have_attribute('data-state','todo');panel.locator('[data-process-step="review"] button').click();self.p.locator('[data-review-confirm]').check();self.p.locator('[data-close-preview]').click();expect(panel.locator('[data-process-count]')).to_have_text('6/6 klart');panel.locator('.process-after summary').click();expect(panel.locator('[data-process-step="handover"]')).to_have_attribute('data-state','blocked');self.p.locator('#goal').fill('Klara promenaden');expect(panel.locator('[data-process-step="review"]')).to_have_attribute('data-state','todo');expect(panel.locator('[data-process-step="saved"]')).to_have_attribute('data-state','todo');self.p.locator('#backToDashboard').click();self.open_patient();expect(panel.locator('[data-process-step="saved"]')).to_have_attribute('data-state','done');expect(panel.locator('[data-process-step="review"]')).to_have_attribute('data-state','todo')
 def test_worksheet_has_shorter_requirements_and_print_review_is_explicit(self):
  self.p.locator('#backToDashboard').click();self.p.locator('[data-worksheet]').click();panel=self.p.locator('#patientProcess');expect(panel.locator('[data-process-count]')).to_have_text('0/2 klart');self.add('chair');expect(panel.locator('[data-process-count]')).to_have_text('1/2 klart');self.p.locator('#saveDraft').click();expect(self.p.get_by_role('button',name='Skriv ut',exact=True)).to_be_disabled();self.p.locator('[data-review-confirm]').check();expect(self.p.get_by_role('button',name='Skriv ut',exact=True)).to_be_enabled();self.p.locator('[data-close-preview]').click();expect(panel.locator('[data-process-count]')).to_have_text('2/2 klart');self.assertEqual(self.p.evaluate('window.drafts.length'),0)
 def test_self_preview_uses_shared_rules_resets_on_change_and_pauses_rehab(self):
  self.p.locator('#backToDashboard').click();self.p.locator('[data-worksheet]').click();self.p.locator('[data-self-preview]').click();d=self.p.locator('.self-preview');expect(d.locator('[data-self-generate]')).to_be_disabled();d.locator('[data-self-goal]').select_option('daily');d.locator('[data-self-profile]').select_option('supported');d.locator('[data-self-generate]').click();expect(d.locator('[data-self-review]')).to_be_visible();d.locator('[data-self-review]').check();expect(d.locator('[data-process-count]')).to_have_text('3/3 klart');d.locator('[data-self-floor]').select_option('yes');expect(d.locator('[data-self-review]')).to_have_count(0);expect(d.locator('[data-process-count]')).to_have_text('1/3 klart');d.locator('[data-self-purpose]').select_option('rehab');expect(d.locator('[data-self-generate]')).to_be_disabled();expect(d.locator('[data-process-step="context"]')).to_have_attribute('data-state','blocked');self.assertEqual(self.p.evaluate('window.drafts.length'),0)
 def test_process_and_self_preview_responsive_screens(self):
  self.add('chair');out=ROOT/'reda2-test-results';out.mkdir(exist_ok=True);self.p.evaluate('scrollTo({top:0,behavior:"instant"})');self.p.screenshot(path=str(out/'process-desktop.png'),full_page=False);self.p.set_viewport_size({'width':390,'height':844});self.p.locator('#patientProcess').scroll_into_view_if_needed();self.assertTrue(self.p.evaluate('document.documentElement.scrollWidth<=innerWidth+1'));self.p.screenshot(path=str(out/'process-mobile.png'),full_page=False);self.p.locator('#backToDashboard').click();self.p.locator('[data-worksheet]').click();self.p.locator('[data-self-preview]').click();d=self.p.locator('.self-preview');d.locator('[data-self-goal]').select_option('daily');d.locator('[data-self-profile]').select_option('supported');expect(d.locator('[data-self-generate]')).to_be_enabled();self.p.screenshot(path=str(out/'self-process-mobile.png'),full_page=False);self.p.set_viewport_size({'width':1440,'height':1000});d.locator('[data-self-generate]').click();d.locator('[data-self-process]').scroll_into_view_if_needed();self.p.screenshot(path=str(out/'self-process-desktop.png'),full_page=False)
for name in dir(AuthoringBase):
 if name.startswith('test_')and name not in T.__dict__:setattr(T,name,None)
del AuthoringBase
if __name__=='__main__':unittest.main()
