-- Continue in the ephemeral database created by response_database_test.sql.
\set ON_ERROR_STOP on
create role service_role bypassrls;
\ir ../../reda-2/secure/progression-runtime.sql
\ir ../../reda-2/secure/dialogue-runtime.sql
grant usage on schema public,private,auth,tests to service_role;
grant all on reda_patients,reda_plans,reda_sessions,reda_audit_events,reda_progression_frames to service_role;
grant usage,select on all sequences in schema public to service_role;
create function tests.plan(reps integer) returns jsonb language sql immutable as $$select jsonb_build_object('schema',6,'context',jsonb_build_object('goalProfile','daily','stage','build','capacity','standard'),'goal','Fictional function goal','schedule',jsonb_build_object('days',jsonb_build_array(1,3,5)),'exercises',jsonb_build_array(jsonb_build_object('id','extension','variantId','seated','name','Fictional knee extension','instructions',jsonb_build_array('Saved instruction'),'side','right','dose',jsonb_build_object('sets',1,'reps',reps,'hold',0,'rest',60,'tempo',5,'label','1 x '||reps))))$$;
create function tests.policy() returns jsonb language sql stable as $$select jsonb_build_object('schema',1,'mode','simulation-only','id','fictional-policy','revision',1,'validFrom',((now() at time zone 'Europe/Stockholm')::date-20)::text,'validUntil',((now() at time zone 'Europe/Stockholm')::date+30)::text,'rules',jsonb_build_object('minSuccessfulDays',3,'minDaysAtStep',7,'maxEvidenceAgeDays',14,'acceptedEffort',jsonb_build_array('easy','okay')),'steps',jsonb_build_array(jsonb_build_object('id','a','label','Start','plan',tests.plan(8)),jsonb_build_object('id','b','label','Next','plan',tests.plan(10)),jsonb_build_object('id','c','label','Final','plan',tests.plan(12))))$$;
insert into auth.sessions values(tests.id(103),tests.id(1)),(tests.id(104),tests.id(4));
update reda_plans set payload=tests.plan(8) where id=tests.id(22);
update reda_sessions set created_at=now()-interval '40 days',started_at=now()-interval '40 days',completed_at=now()-interval '40 days',status='completed';
select tests.ok(private.reda_validate_frame(tests.policy()),'complete frame accepted');
select tests.ok(not private.reda_validate_frame(tests.policy()-'validFrom'),'missing date rejected');
select tests.ok(not private.reda_validate_frame(tests.policy()-'schema'),'missing schema rejected');
select tests.ok(not private.reda_validate_frame(jsonb_set(tests.policy(),'{steps,1,plan}',tests.plan(8))),'identical prescription steps rejected');
set role authenticated;
select tests.login(2);
select tests.denied('select reda_approve_frame(tests.id(22),tests.policy())','42501','patient cannot approve frame');
select tests.login(1,'aal1',103);
select tests.denied('select reda_approve_frame(tests.id(22),tests.policy())','42501','MFA required for approval');
select tests.login(4,'aal2',104);
select tests.denied('select reda_approve_frame(tests.id(22),tests.policy())','42501','foreign clinician cannot approve');
select tests.login(1,'aal2',103);
select tests.denied('select reda_approve_frame(tests.id(22),tests.policy(),''automatic'')','42501','automatic execution disabled by default');
select tests.denied('select reda_approve_frame(tests.id(22),jsonb_set(tests.policy(),''{steps,0,plan}'',tests.plan(9)))','22023','approval bound to actual active prescription');
select set_config('tests.frame',(reda_approve_frame(tests.id(22),tests.policy())->>'id'),false);
reset role;
update reda_progression_frames set started_at=now()-interval '10 days' where id=current_setting('tests.frame')::uuid;
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,created_at,completed_at,payload)
 select tests.id(40+i),tests.id(500+i),tests.id(11),tests.id(22),2,'completed',now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),now()-make_interval(days=>10-2*i),'{"exercises":[{"exerciseId":"extension","status":"completed","roundsDone":1,"feedback":"okay"}]}'::jsonb from generate_series(1,3)i;
insert into reda_training_responses(request_id,session_id,patient_id,plan_id,plan_version,reported_by,created_at,answers)
 select tests.id(600+i),tests.id(40+i),tests.id(11),tests.id(22),2,tests.id(2),now()-make_interval(days=>9-2*i),tests.answer()||'{"environment":"same"}'::jsonb from generate_series(1,3)i;
set role authenticated;
select tests.login(2);
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(701))->>'action'='advance','server derives eligible evidence');
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(701))->>'applied'='false','shadow never mutates plan');
select tests.ok((select count(*)=1 from reda_engine_decisions where request_id=tests.id(701)),'decision request idempotent');
reset role;
update auth.users set banned_until=now()+interval '1 day' where id=tests.id(1);
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(700))->>'code'='clinician_authority','inactive clinician authority blocks evaluation');
reset role;
update auth.users set banned_until=null where id=tests.id(1);
update reda_sessions set payload=jsonb_set(payload,'{exercises,0,roundsDone}','0') where id=tests.id(41);
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(702))->>'code'='invalid_session','marked completion cannot hide missing rounds');
reset role;
update reda_sessions set payload=jsonb_set(payload,'{exercises,0,roundsDone}','1'),status='partial' where id=tests.id(41);
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(703))->>'code'='partial','partial activity does not authorize an increase');
reset role;
update reda_sessions set status='completed' where id=tests.id(41);
update reda_training_responses set answers=answers-'environment' where session_id=tests.id(43);
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(704))->>'code'='context','legacy answers do not imply unchanged environment');
reset role;
update reda_training_responses set answers=answers||'{"environment":"same"}'::jsonb where session_id=tests.id(43);
insert into reda_sessions(id,client_session_id,patient_id,plan_id,plan_version,status,started_at,completed_at,payload) values(tests.id(44),tests.id(544),tests.id(11),tests.id(21),1,'partial',now(),null,'{}');
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(705))->>'code'='open_session','an open older session blocks version switching');
reset role;
update reda_sessions set status='completed',completed_at=now()-interval '2 days' where id=tests.id(44);
insert into reda_training_responses(request_id,session_id,patient_id,plan_id,plan_version,reported_by,answers) values(tests.id(644),tests.id(44),tests.id(11),tests.id(21),1,tests.id(2),tests.answer()||'{"nextDay":"worse","environment":"same"}'::jsonb);
select set_config('tests.case',(select id::text from reda_review_cases where response_id=(select id from reda_training_responses where session_id=tests.id(44))),false);
set role authenticated;
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(706))->>'code'='pending_review','unresolved concern from old plan also blocks');
select tests.denied('select reda_handle_case(current_setting(''tests.case'')::uuid,''resolved'',''Self clearance'')','42501','patient cannot clear an exception');
select tests.login(1,'aal2',103);
select tests.ok(reda_handle_case(current_setting('tests.case')::uuid,'acknowledged','Seen')->>'status'='acknowledged','acknowledgement recorded');
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(707))->>'code'='pending_review','acknowledgement is not resolution');
select tests.denied('select reda_handle_case(current_setting(''tests.case'')::uuid,''resolved'','''')','22023','resolution requires a meaningful note');
select tests.ok(reda_handle_case(current_setting('tests.case')::uuid,'resolved','Fictional review completed, current plan retained.')->>'status'='resolved','clinician records explicit resolution');
reset role;
update private.reda_engine_settings set automatic_enabled=true;
set role authenticated;
select set_config('tests.frame',(reda_approve_frame(tests.id(22),tests.policy(),'automatic')->>'id'),false);
reset role;
update reda_progression_frames set started_at=now()-interval '10 days' where id=current_setting('tests.frame')::uuid;
set role authenticated;
select tests.login(2);
select set_config('tests.nextplan',reda_evaluate_progression(tests.id(11),tests.id(708))->>'result_plan_id',false);
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(708))->>'applied'='true','automatic mode atomically creates next version');
select tests.ok((select version=3 and payload=tests.plan(10) from reda_plans where id=current_setting('tests.nextplan')::uuid),'exact approved next prescription published');
select tests.ok((select count(*)=3 from reda_sessions where plan_id=tests.id(22) and id in (tests.id(41),tests.id(42),tests.id(43))),'historical sessions retain old plan');
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(709))->>'code'='context','new step starts with no inherited readiness');
select tests.ok(reda_dialogue_context(current_setting('tests.nextplan')::uuid)->>'enabled'='false','AI remains off independently');
select tests.denied('select reda_dialogue_context(tests.id(23))','42501','dialogue cannot read another patient plan');
select tests.ok(not ((reda_dialogue_context(current_setting('tests.nextplan')::uuid)->'plan') ?| array['patientName','clinicianNote','patient_id']),'dialogue excludes identity and free clinician notes');
reset role;
update private.reda_engine_settings set ai_enabled=true;
set role authenticated;
do $$begin for i in 1..20 loop perform reda_dialogue_context(current_setting('tests.nextplan')::uuid,true);end loop;end$$;
select tests.denied('select reda_dialogue_context(current_setting(''tests.nextplan'')::uuid,true)','54000','AI request budget enforced on the server');
select tests.login(1,'aal2',103);
select reda_revoke_frame(current_setting('tests.frame')::uuid);
select tests.ok(reda_evaluate_progression(tests.id(11),tests.id(710))->>'code'='no_frame','revocation immediately stops evaluation');
reset role;
set role service_role;
select reda_save_session_internal(tests.id(2),tests.id(801),current_setting('tests.nextplan')::uuid,'started',now()-interval '30 days',null,'{}');
select tests.ok((select started_at between now()-interval '5 seconds' and now() from reda_sessions where client_session_id=tests.id(801)),'session start uses server clock');
select reda_save_session_internal(tests.id(2),tests.id(801),current_setting('tests.nextplan')::uuid,'completed',now()-interval '30 days',now()-interval '20 days','{}');
select tests.ok((select completed_at between now()-interval '5 seconds' and now() from reda_sessions where client_session_id=tests.id(801)),'session completion uses server clock');
select tests.denied('select reda_save_session_internal(tests.id(2),tests.id(801),current_setting(''tests.nextplan'')::uuid,''partial'',now(),null,''{}'')','P0001','closed evidence cannot be reopened');
reset role;
select tests.ok((select count(*)=2 from reda_progression_frames where patient_id=tests.id(11)),'frame revisions retained');
select tests.ok((select count(*)=1 from reda_plans where patient_id=tests.id(11) and status='active'),'exactly one active plan remains');
update reda_plans set payload=tests.plan(8) where id=tests.id(23);
select tests.login(4,'aal2',104);
select reda_approve_frame(tests.id(23),tests.policy());
-- Service activation must retain access to the frame CHECK without exposing browser writes.
insert into reda_plans(id,patient_id,clinician_id,version,status,payload) values(tests.id(990),tests.id(12),tests.id(4),2,'draft',tests.plan(8));
set role service_role;
select reda_activate_plan_internal(tests.id(990),tests.id(4));
reset role;
select tests.ok((select status='active' from reda_plans where id=tests.id(990)),'existing service activation remains usable');
set role authenticated;
select tests.login(2);
select tests.denied('update reda_progression_frames set status=''revoked''','42501','browser cannot write frames');
select tests.denied('update reda_sessions set payload=''{}''','42501','browser cannot tamper with session evidence');
select tests.login(3,'aal1',102);
select tests.ok((select count(*)=0 from reda_engine_decisions),'other patient cannot read decisions');
select tests.login(2,'aal1',999);
select tests.denied('select reda_evaluate_progression(tests.id(11),tests.id(995))','42501','revoked login cannot run engine');
reset role;
