\ir ../../reda-2/secure/support-workflow.sql
\ir ../../reda-2/secure/activity-log.sql
-- Reuse only isolated fictional services. Clear prior conversation state through the real clinical API.
set role authenticated;select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(798001),'resolve_cases','Fictional previous conversation reviewed and closed.');
select set_config('tests.workflow_before',reda_dashboard_patient(tests.id(700003))->>'token',false);
select tests.login(9,'aal1',109);
select set_config('tests.workflow_session',reda_sync_session(tests.id(798002),tests.id(796000),'completed',now(),now(),'{"optionId":"less-rounds","exercises":[{"exerciseId":"extension","status":"completed","roundsDone":2,"feedback":"okay"}]}')::text,false);
select set_config('tests.workflow_reflection',reda_submit_session_reflection(current_setting('tests.workflow_session')::uuid,tests.id(798003),'{"barrier":"execution","support":"yes","exerciseId":"extension"}')::text,false);
select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='needs_review','new support request enters clinician work automatically');
select tests.ok(not(reda_patient_support(tests.id(700003)) ?| array['due_date','pending_signals','handling_note','assigned_to']),'patient status excludes private deadlines and notes');
select tests.ok(reda_submit_session_reflection(current_setting('tests.workflow_session')::uuid,tests.id(798003),'{"barrier":"execution","support":"yes","exerciseId":"extension"}')::text=current_setting('tests.workflow_reflection'),'retry retains one source');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'workflow'->>'due_date'=(now() at time zone 'Europe/Stockholm')::date::text,'automatic task due today in existing worklist');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'workflow'->>'phase'='needs_review','clinical workflow carries current phase');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_dashboard('','priority')->'patients')p where p->>'patient_id'=tests.id(700003)::text and p->'workflow'->>'phase'='needs_review'),'dashboard page includes workflow');
select tests.denied('select reda_dashboard_act(tests.id(700003),current_setting(''tests.workflow_before''),tests.id(798004),''resolve_cases'',''Old screen cannot resolve a new need.'')','40001','new automatic work invalidates stale approval');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(798005),'send_message','Fiktiv riktad fråga om vilken del av utförandet som är svår.',(now() at time zone 'Europe/Stockholm')::date+1);
select tests.login(9,'aal1',109);
select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='awaiting_patient','delivered question awaits patient');
select tests.ok(reda_patient_support(tests.id(700003))->>'reply_to'=tests.id(798005)::text,'status links to the actual answerable message');
select reda_patient_reply(tests.id(798005),tests.id(798006),'Jag förstår inte hur knät ska sträckas.');
select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='needs_review','patient reply reopens review');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(798007),'follow_up','Fiktiv uppföljning av frågan planerad.',(now() at time zone 'Europe/Stockholm')::date+1);
select tests.ok(reda_dashboard_patient(tests.id(700003))->'workflow'->>'phase'='scheduled','clinician schedules next step');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(798008),'complete_follow_up','Fiktiv kontakt genomförd men bedömningen återstår.');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'workflow'->>'phase'='needs_resolution','completed contact does not close unresolved help');
select tests.ok(reda_evaluate_progression(tests.id(700003),tests.id(798009))->>'code'='pending_review','unfinished support still blocks progression');
select reda_dashboard_act(tests.id(700003),reda_dashboard_patient(tests.id(700003))->>'token',tests.id(798010),'resolve_cases','Fiktiv instruktion genomgången och hjälpbehovet hanterat.');
select tests.login(9,'aal1',109);select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='handled','explicit clinical resolution closes the support flow');
select tests.login(2,'aal1',101);select tests.denied('select reda_patient_support(tests.id(700003))','42501','another patient cannot read status');
select tests.login(9,'aal1',999);select tests.denied('select reda_patient_support(tests.id(700003))','42501','revoked session cannot read status');
select tests.login(1,'aal1',103);select tests.workspace('dashboard-test');select tests.denied('select reda_dashboard_patient(tests.id(700003))','42501','clinical workflow requires MFA');
select tests.login(1,'aal2',103);select tests.workspace('clinic-b');select tests.denied('select reda_dashboard_patient(tests.id(700003))','42501','clinical workflow cannot cross workspaces');
reset role;
select tests.ok((select count(*)=1 from reda_audit_events where action='support_task_queued' and metadata->>'case_id'=(select id::text from reda_review_cases where reflection_id=(current_setting('tests.workflow_reflection')::jsonb->>'id')::uuid)),'one queue receipt despite retries');
select tests.ok((select count(*)=1 from private.reda_followups where patient_id=tests.id(700003)),'one worklist task per patient');
select tests.ok(not has_function_privilege('authenticated','private.reda_support_state(uuid)','execute'),'internal state helper is not callable');
select tests.ok(not has_function_privilege('anon','public.reda_patient_support(uuid)','execute'),'anonymous support read denied');
set role authenticated;select tests.login(9,'aal1',109);
select set_config('tests.workflow_neutral',reda_sync_session(tests.id(798020),tests.id(796000),'completed',now(),now(),'{"optionId":"less-rounds","exercises":[{"exerciseId":"extension","status":"completed","roundsDone":2,"feedback":"okay"}]}')::text,false);
select reda_submit_session_reflection(current_setting('tests.workflow_neutral')::uuid,tests.id(798021),'{"barrier":"none","support":"no","exerciseId":null}');
select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='handled','neutral feedback does not reopen a handled support request');
select set_config('tests.workflow_reopen',reda_sync_session(tests.id(798022),tests.id(796000),'completed',now(),now(),'{"optionId":"less-rounds","exercises":[{"exerciseId":"extension","status":"completed","roundsDone":2,"feedback":"okay"}]}')::text,false);
select reda_submit_session_reflection(current_setting('tests.workflow_reopen')::uuid,tests.id(798023),'{"barrier":"symptoms","support":"yes","exerciseId":null}');
select tests.ok(reda_patient_support(tests.id(700003))->>'phase'='needs_review','new symptom signal reopens handled work');
select tests.login(1,'aal2',103);select tests.workspace('dashboard-test');
select tests.ok(reda_dashboard_patient(tests.id(700003))->'workflow'->>'due_date'=(now() at time zone 'Europe/Stockholm')::date::text,'reopened work gets current date');
select tests.ok(exists(select 1 from jsonb_array_elements(reda_activity_log(tests.id(700003),'ei')->'events')e where e->>'title'='EI lade till en uppföljningsuppgift'),'automatic work has a real timeline receipt');
reset role;
select tests.ok((select count(*)=1 from private.reda_followups where patient_id=tests.id(700003)),'reopening never duplicates the patient worklist entry');
select tests.ok((select not automatic_enabled and not ai_enabled from private.reda_engine_settings),'clinical progression and external AI remain closed');
