/* Contact planning belongs to a plan version. No booking, automatic progression or clinical decision. */
(function(root){'use strict';
const modes={clinic:'På kliniken',remote:'På distans',hybrid:'Klinik och distans'},methods={clinic:'Besök på kliniken',video:'Videosamtal',phone:'Telefonsamtal'},labels={review1:'Första avstämningen',review2:'Andra avstämningen',closing:'Avslutande uppföljning',review:'Uppföljning'};
const clone=x=>JSON.parse(JSON.stringify(x));
function validDate(s){return typeof s==='string'&&/^20\d\d-\d{2}-\d{2}$/.test(s)&&!Number.isNaN(Date.parse(s+'T12:00:00Z'))&&new Date(s+'T12:00:00Z').toISOString().slice(0,10)===s}
function today(now=new Date()){return new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Stockholm',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(now))}
function shift(d,n){if(!validDate(d))throw Error('Ange ett giltigt startdatum.');return new Date(Date.parse(d+'T12:00:00Z')+n*86400000).toISOString().slice(0,10)}
function normalize(input={}){if(!Object.hasOwn(modes,input.mode||'clinic'))throw Error('Välj kontaktupplägg.');const mode=input.mode||'clinic',weeks=Number(input.weeks||0);if(![0,6,8].includes(weeks))throw Error('Välj löpande uppföljning, sex eller åtta veckor.');const checkpoints=(input.checkpoints||[]).map(p=>{if(!Object.hasOwn(labels,p.id)||!Object.hasOwn(methods,p.method))throw Error('Kontrollera avstämningens kontaktform.');return {id:p.id,date:String(p.date||''),method:p.method}});if(new Set(checkpoints.map(p=>p.id)).size!==checkpoints.length)throw Error('En avstämning får bara förekomma en gång.');return {schema:1,mode,weeks,startDate:String(input.startDate||''),assessment:{confirmed:input.assessment?.confirmed===true,date:String(input.assessment?.date||''),method:Object.hasOwn(methods,input.assessment?.method)?input.assessment.method:'clinic'},checkpoints}}
function issues(input,now){const p=normalize(input),errors=[],dated=p.checkpoints.filter(x=>x.date);for(const c of dated)if(!validDate(c.date))errors.push('Kontrollera datum för '+labels[c.id].toLowerCase()+'.');if(p.startDate&&!validDate(p.startDate))errors.push('Ange ett giltigt startdatum.');if(p.weeks){if(!validDate(p.startDate))errors.push('Ange periodens startdatum.');if(validDate(p.startDate)){const end=shift(p.startDate,p.weeks*7);for(const c of dated)if(c.date<p.startDate||c.date>end)errors.push('Avstämningarna ska ligga inom den valda perioden.')}const ds=['review1','review2','closing'].map(id=>p.checkpoints.find(c=>c.id===id)?.date).filter(Boolean);if(ds.some((d,i)=>i>0&&d<=ds[i-1]))errors.push('Avstämningarna ska ligga i ordning på olika datum.')}if(p.mode!=='clinic'){if(!p.assessment.confirmed)errors.push('Bekräfta att patienten är bedömd och att kontaktupplägget passar.');if(!validDate(p.assessment.date)||p.assessment.date>today(now))errors.push('Ange datum för genomförd bedömning.');if(validDate(p.startDate)&&validDate(p.assessment.date)&&p.assessment.date>p.startDate)errors.push('Bedömningen ska vara genomförd senast vid periodstart.')}return [...new Set(errors)]}
function suggest(startDate,weeks,method){if(![6,8].includes(Number(weeks))||!Object.hasOwn(methods,method))throw Error('Välj period och kontaktform.');return ['review1','review2','closing'].map((id,i)=>({id,date:shift(startDate,[14,28,Number(weeks)*7][i]),method}))}
function read(payload={}){if(payload.careJourney)return normalize(payload.careJourney);const date=payload.reviewDate||payload.review?.date||'';return normalize({checkpoints:date?[{id:'review',date,method:'clinic'}]:[]})}
function attach(plan,input){const next=clone(plan),path=normalize(input);next.careJourney=path;next.reviewDate=path.checkpoints.filter(c=>validDate(c.date)).sort((a,b)=>a.date.localeCompare(b.date))[0]?.date||'';return next}
function displayDate(d){return validDate(d)?`${d.slice(8,10)}/${d.slice(5,7)} ${d.slice(0,4)}`:'Datum bestäms tillsammans'}
function overview(payload,now){const p=read(payload),date=today(now),points=p.checkpoints.filter(c=>validDate(c.date)).sort((a,b)=>a.date.localeCompare(b.date)).map(c=>({...c,label:labels[c.id],contact:methods[c.method],dateLabel:displayDate(c.date),passed:c.date<date}));return {...p,label:modes[p.mode],endDate:p.weeks&&validDate(p.startDate)?shift(p.startDate,p.weeks*7):'',points,next:points.find(c=>c.date>=date)||null,unconfirmedPast:points.filter(c=>c.passed).length}}
root.RedaCare={modes,methods,labels,validDate,today,shift,normalize,issues,suggest,read,attach,displayDate,overview};if(typeof module==='object'&&module.exports)module.exports=root.RedaCare;
})(typeof window!=='undefined'?window:globalThis);
