/* Reda 2.4 · modular clinical exercise additions. Variants are options for the clinician, never automatic progression. */
(function(root){'use strict';const D=root.RedaData;if(!D)return;
const dose=(sets,reps,rest=60,hold=0,tempo=5)=>({sets,reps,rest,hold,tempo});
const addExercise=e=>{if(!D.exercises.some(x=>x.id===e.id))D.exercises.push(e);};
const addVariant=(exerciseId,v)=>{const e=D.exercises.find(x=>x.id===exerciseId);if(e&&!e.variants.some(x=>x.id===v.id))e.variants.push(v);};
addExercise({id:'bird_dog',name:'Bird dog',region:'Bål & höft',equipment:'Matta',purpose:'Del av en behandlarvald plan för bål- och höftkontroll.',variants:[{id:'leg',name:'Bensträckning',support:'Fyrfota',steps:['Stå på alla fyra i positionen ni gått igenom.','För ett ben bakåt med kontroll.','Återgå lugnt och växla sida.'],cue:'Kontroll före räckvidd.',dose:dose(2,8,45,0,6),pose:'abduction',tags:{load:1,floor:true}},{id:'opposite',name:'Motsatt arm och ben',support:'Fyrfota',steps:['Stå stabilt på alla fyra.','För motsatt arm och ben ut enligt ordination.','Återgå kontrollerat och växla sida.'],cue:'Behåll bålen stabil.',dose:dose(3,8,60,0,7),pose:'abduction',tags:{load:2,floor:true}}]});
/* Höftlyft: en sammanhängande familj från avlastad start till unilateral extern belastning. */
addVariant('bridge',{id:'elevated',name:'Högre utgångsläge',support:'Ryggliggande · anpassat underlag',steps:['Ligg på rygg med fötterna på det underlag ni valt.','Pressa genom fötterna och lyft bäckenet till ordinerad höjd.','Sänk långsamt tillbaka med båda fötterna kvar.'],cue:'Höjden på underlaget är en del av ordinationen.',dose:dose(2,8,45,0,6),pose:'bridge',tags:{load:0,floor:true}});
addVariant('bridge',{id:'band',name:'Två ben med band',support:'Ryggliggande · band',steps:['Placera bandet enligt instruktionen från besöket.','Lyft bäckenet och håll knäna i den position ni tränat.','Sänk kontrollerat utan att tappa bandets riktning.'],cue:'Bandet ger riktning och motstånd, inte ett krav på större rörelse.',dose:dose(3,10,60,0,7),pose:'bridge',tags:{load:3,floor:true,band:true}});
addVariant('bridge',{id:'loaded',name:'Två ben med extern belastning',support:'Ryggliggande · belastning',steps:['Placera den ordinerade belastningen säkert över bäckenet.','Lyft bäckenet kontrollerat med båda fötterna i underlaget.','Sänk långsamt och behåll kontrollen hela vägen.'],cue:'Använd endast den belastning som valts i planen.',dose:dose(3,8,75,0,7),pose:'bridge',tags:{load:4,floor:true}});
addVariant('bridge',{id:'single',name:'Enbens höftlyft',support:'Ryggliggande · ett ben',steps:['Ligg i utgångsläget ni gått igenom och avlasta det andra benet.','Lyft bäckenet med träningssidan utan att rotera.','Sänk lugnt tillbaka innan nästa repetition.'],cue:'Bäckenets kontroll är viktigare än lyfthöjden.',dose:dose(3,8,75,0,7),pose:'bridge',tags:{load:5,floor:true}});
addVariant('bridge',{id:'single_loaded',name:'Enbens med extern belastning',support:'Ryggliggande · ett ben · belastning',steps:['Placera ordinerad belastning och inta enbenspositionen.','Lyft bäckenet med kontroll på träningssidan.','Sänk långsamt och återställ positionen mellan repetitionerna.'],cue:'Detta är en behandlarvald belastningsvariant.',dose:dose(3,6,90,0,8),pose:'bridge',tags:{load:6,floor:true}});
/* Stolresning: praktisk kapacitet och senare extern belastning hålls som separata varianter. */
addVariant('chair',{id:'high',name:'Högre stol',support:'Hög sitthöjd · handstöd vid behov',steps:['Sitt på den högre sitthöjd ni valt.','Luta dig framåt och res dig med den hjälp som är ordinerad.','Sätt dig lugnt tillbaka på samma höjd.'],cue:'Sitthöjden är den huvudsakliga anpassningen.',dose:dose(2,6,60,0,6),pose:'chair-support',tags:{load:0}});
addVariant('chair',{id:'tempo',name:'Långsam nedsittning',support:'Stol utan handstöd',steps:['Res dig från stolen enligt din vanliga variant.','Stå stabilt innan du börjar sänka.','Sätt dig tillbaka långsamt och kontrollerat.'],cue:'Långsam väg ned, normal väg upp.',dose:dose(3,8,75,0,8),pose:'chair-free',tags:{load:3}});
addVariant('chair',{id:'loaded',name:'Med extern belastning',support:'Stol · ordinerad belastning',steps:['Håll belastningen på det sätt ni gått igenom.','Res dig från stolen med jämn kontroll.','Sätt dig tillbaka långsamt utan att släppa positionen.'],cue:'Belastning och sitthöjd bestäms vid uppföljning.',dose:dose(3,6,90,0,7),pose:'chair-free',tags:{load:4}});
/* Vad/Achilles: skilj tempo, unilateral kapacitet och extern belastning. */
addVariant('calf',{id:'ecc_both',name:'Två ben · långsam sänkning',support:'Stabilt stöd',steps:['Stå med båda fötterna i golvet och håll i stödet.','Lyft hälarna kontrollerat.','Sänk långsamt under den tid ni gått igenom.'],cue:'Den långsamma sänkningen är dosen.',dose:dose(3,10,60,0,8),pose:'calf-both',tags:{load:2}});
addVariant('calf',{id:'single_loaded',name:'Ett ben med extern belastning',support:'Stabilt stöd · belastning',steps:['Stå på träningssidan med stödet inom räckhåll.','Lyft hälen med den ordinerade belastningen.','Sänk långsamt tillbaka till start.'],cue:'Stödet får användas för balans även när belastningen ökar.',dose:dose(4,8,90,0,7),pose:'calf-single',tags:{load:5}});
/* Funktionell knäbelastning. */
addVariant('step_up',{id:'loaded',name:'Step-up med extern belastning',support:'Steg · ordinerad belastning',steps:['Placera hela foten på den steghöjd ni valt.','Res dig upp med den ordinerade belastningen.','Sänk tillbaka kontrollerat till startpositionen.'],cue:'Steghöjd och belastning ändras separat.',dose:dose(3,8,90,0,7),pose:'chair-free',tags:{load:4}});
addVariant('split_squat',{id:'loaded',name:'Split squat med extern belastning',support:'Delad position · belastning',steps:['Stå i den fotposition ni gått igenom.','Sänk till det ordinerade djupet med belastningen nära kroppen.','Res dig kontrollerat och återställ balansen.'],cue:'Djup och extern belastning är behandlarvalda.',dose:dose(3,6,90,0,7),pose:'chair-free',tags:{load:4}});
/* Axel: isometrisk ingång och belastad elevation hålls tydligt åtskilda. */
addVariant('rotation',{id:'iso',name:'Isometrisk utåtrotation',support:'Arm intill kroppen · vägg eller band',steps:['Placera armen i den position ni gått igenom.','Bygg upp ett jämnt tryck utan att röra armen.','Släpp trycket lugnt mellan hållen.'],cue:'Jämnt tryck utan synlig rörelse.',dose:dose(3,5,45,10,5),pose:'rotation',tags:{load:0}});
addVariant('scaption',{id:'mid',name:'Kontrollerat armlyft',support:'Stående · utan extern vikt',steps:['Stå stabilt och för armen i scapularplanet.','Lyft till den höjd ni valt vid undersökningen.','Sänk långsamt tillbaka.'],cue:'Höjden är individuell och behöver inte vara maximal.',dose:dose(3,10,60,0,6),pose:'rotation',tags:{load:2}});
root.RedaClinicalAddons={version:'2.4.0',progression:'clinician_only'};
})(typeof window!=='undefined'?window:globalThis);