import * as api from './secure-browser.mjs'
const $=id=>document.getElementById(id), C=window.RedaClinical, P=window.RedaPlanner
let selected=null,patients=[],plan=null,draft=null,mfaFactor=null
function err(e){$('authError').textContent=e?.message||String(e);$('authError').classList.remove('hidden')}
function clearErr(){$('authError').classList.add('hidden')}
function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function setAuth(show){$('auth').classList.toggle('hidden',!show);$('app').classList.toggle('hidden',show);$('logout').classList.toggle('hidden',show)}
function blueprints(){return Object.values(C?.blueprints||{})}
function fillBlueprints(){const el=$('blueprint');el.innerHTML=blueprints().map(b=>`<option value="${escape(b.id)}">${escape(b.name)}</option>`).join('')}
function renderPatients(){$('patientCount').textContent=`${patients.length} aktiva`;$('patients').innerHTML=patients.length?patients.map(p=>`<button class="patient ${selected?.id===p.id?'active':''}" data-patient="${p.id}" style="text-align:left;background:${selected?.id===p.id?'var(--soft)':'transparent'}"><b>${escape(p.display_name)}</b><span class="sub">${p.auth_user_id?'Ansluten':'Ej inbjuden'}</span></button>`).join(''):'<div class="muted">Inga patienter ännu.</div>';document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>selectPatient(b.dataset.patient))}
async function loadPatients(){patients=await api.listPatients();renderPatients()}
async function selectPatient(id){selected=patients.find(p=>p.id===id);draft=null;$('patientTitle').textContent=selected.display_name;$('noPatient').classList.add('hidden');$('editor').classList.remove('hidden');renderPatients();build();await renderFollowup()}
function build(){if(!selected)return;try{plan=P.buildProgram({blueprintId:$('blueprint').value,stage:$('stage').value,capacity:$('capacity').value,guidance:$('guidance').value,equipment:$('equipment').value,floorOK:$('floorOK').checked,band:$('band').checked,goal:$('goal').value.trim(),clinicianNote:$('note').value.trim(),reviewDate:$('reviewDate').value,patientName:selected.display_name});renderPlan()}catch(e){$('syncStatus').textContent='Kan inte bygga plan: '+e.message}}
function renderPlan(){const ex=plan?.exercises||[];$('planMeta').textContent=`${ex.length} övningar`;$('planSub').textContent=`${plan?.schedule?.days?.length||0} pass/vecka · ${plan?.blueprintName||''}`;$('planExercises').innerHTML=ex.map(x=>`<div class="exercise"><h3>${escape(x.name)}</h3><div class="sub">${escape(x.variantLabel||'')} · ${escape(x.dose?.label||'')}</div></div>`).join('');$('saveDraft').disabled=!ex.length;$('activate').disabled=!draft;$('syncStatus').textContent=draft?`Utkast v${draft.version} sparat`:'Inte sparad'}
async function saveDraft(){if(!selected||!plan)return;try{$('saveDraft').disabled=true;draft=await api.createDraft(selected.id,plan);$('syncStatus').textContent=`Utkast v${draft.version} sparat`;$('activate').disabled=false}catch(e){$('syncStatus').textContent='Kunde inte spara: '+e.message}finally{$('saveDraft').disabled=false}}
async function activate(){if(!draft||!selected)return;try{$('activate').disabled=true;$('syncStatus').textContent='Förbereder distribution…';let invited=false;if(!selected.auth_user_id){const email=$('patientEmail').value.trim();if(!email)throw new Error('Ange patientens e-post för inbjudan');await api.invitePatient(selected.id,email);selected.auth_user_id='invited';invited=true}$('syncStatus').textContent='Aktiverar planversion…';await api.activatePlan(draft.id);$('syncStatus').textContent=`Version ${draft.version} är aktiv${invited?' · inbjudan skickad':''}`;draft=null;await loadPatients();await renderFollowup()}catch(e){$('syncStatus').textContent='Inte färdig: '+e.message}finally{$('activate').disabled=!draft}}
async function renderFollowup(){if(!selected)return;try{const s=await api.patientSummary(selected.id),completed=s.sessions.filter(x=>x.status==='completed'),partial=s.sessions.filter(x=>x.status==='partial'||x.status==='started'),active=s.plans.find(x=>x.status==='active');$('followup').innerHTML=`<div class="row"><div><div class="metric">${completed.length}</div><div class="sub">genomförda pass</div></div><div><div class="metric">${partial.length}</div><div class="sub">påbörjade/delvisa</div></div><div><div class="metric">${active?'v'+active.version:'–'}</div><div class="sub">aktiv plan</div></div></div>${s.sessions.slice(0,5).map(x=>`<div class="exercise"><b>${escape(x.status)}</b><div class="sub">${new Date(x.started_at).toLocaleDateString('sv-SE')} · plan v${x.plan_version}</div></div>`).join('')||'<p class="muted">Ingen träningshistorik ännu.</p>'}`}catch(e){$('followup').textContent='Kunde inte läsa uppföljning: '+e.message}}
async function finishClinicianAuth(){clearErr();const a=await api.aal();if(a.currentLevel!=='aal2'){const f=await api.factors(),verified=f?.totp?.find(x=>x.status==='verified');if(verified){mfaFactor=verified.id;$('mfa').classList.remove('hidden');$('qr').classList.add('hidden');$('secret').textContent='Ange koden från din autentiseringsapp.';return}const enrolled=await api.enrollTotp();mfaFactor=enrolled.id;$('qr').src=enrolled.totp.qr_code;$('qr').classList.remove('hidden');$('secret').textContent='Skanna QR-koden med din autentiseringsapp och ange sedan koden.';$('mfa').classList.remove('hidden');return}await api.claimClinician();const profile=await api.clinicianProfile();if(profile?.role!=='clinician')throw new Error('Kontot saknar behandlarbehörighet');setAuth(false);await loadPatients()}
$('login').onclick=async()=>{try{clearErr();await api.signIn($('email').value.trim(),$('password').value);await finishClinicianAuth()}catch(e){err(e)}}
$('signup').onclick=async()=>{try{clearErr();await api.signUp($('email').value.trim(),$('password').value,window.REDA_BACKEND.clinicUrl);$('authError').textContent='Kontot är skapat. Bekräfta e-postadressen och logga sedan in. Endast förhandsgodkända behandlare får klinikbehörighet.';$('authError').className='success'}catch(e){err(e)}}
$('verifyMfa').onclick=async()=>{try{await api.verifyTotp(mfaFactor,$('mfaCode').value.trim());await finishClinicianAuth()}catch(e){err(e)}}
$('logout').onclick=async()=>{await api.signOut();location.reload()}
$('newPatient').onclick=async()=>{const name=prompt('Patientens namn');if(!name?.trim())return;try{const p=await api.createPatient(name.trim());await loadPatients();await selectPatient(p.id)}catch(e){alert('Kunde inte skapa patient: '+e.message)}}
$('saveDraft').onclick=saveDraft;$('activate').onclick=activate;$('refresh').onclick=renderFollowup
;['blueprint','stage','capacity','guidance','equipment','floorOK','band','goal','note','reviewDate'].forEach(id=>$(id).addEventListener(id==='goal'||id==='note'?'input':'change',()=>{draft=null;build()}))
fillBlueprints();setAuth(true);api.currentUser().then(u=>u&&finishClinicianAuth()).catch(()=>{})
