(function(){'use strict';const C=RedaCore,D=RedaData,M=RedaClinical,$=s=>document.querySelector(s),E=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const patients=[{id:'demo-1',name:'Anna Lind',plan:'Knä · patellofemoralt',adherence:'2/3 pass',review:'18 sep',flag:'åter snart'},{id:'demo-2',name:'Erik Holm',plan:'Axel · rotatorcuff',adherence:'3/3 pass',review:'25 sep',flag:''},{id:'demo-3',name:'Maj Berg',plan:'Knä · artros',adherence:'1/2 pass',review:'30 sep',flag:''}];let selected=patients[0];
let state={blueprint:'knee_pf',stage:'build',capacity:'standard',presentation:'standard',floor:true,band:true,goal:'Tillbaka till löpning',reviewDate:'',days:[1,3,5],note:''},plan=null;const stageLoad={gentle:1,build:2,loaded:3};
function chooseVariant(ex){const wanted=stageLoad[state.stage],vs=ex.variants,candidates0=vs.filter(v=>!(v.tags?.band&&state.band===false)&&!(v.tags?.floor&&state.floor===false));const candidates=candidates0.length?candidates0:vs;const cap=state.capacity==='supported'?0:state.capacity==='high'?candidates.length-1:Math.min(1,candidates.length-1);let chosen=candidates[cap]||candidates[0];if(candidates.some(v=>v.tags?.load))chosen=candidates.slice().sort((a,b)=>Math.abs((a.tags?.load||2)-wanted)-Math.abs((b.tags?.load||2)-wanted))[0];return chosen}
function scale(d){d=C.clone(d);if(state.stage==='gentle'){d.sets=Math.min(d.sets,2);d.reps=Math.min(d.reps,10);if(d.hold)d.hold=Math.min(d.hold,20)}if(state.stage==='loaded'){d.sets=Math.min(4,d.sets+1);d.reps=Math.min(20,d.reps+2)}return d}
function build(){const bp=M.blueprints[state.blueprint],p=C.template();p.title=bp.name;p.goal=state.goal.trim()||bp.goal;p.reviewDate=state.reviewDate;p.days=state.days.slice();p.message=M.presentation[state.presentation].intro+' Programmet är anpassat efter det vi gick igenom vid besöket.';p.safety='Följ den här nivån fram till uppföljningen. Progression beslutas av din behandlare.';p.items=[];for(const id of bp.slots){const ex=D.exercises.find(e=>e.id===id);if(!ex)continue;const vr=chooseVariant(ex);if(vr.tags?.floor&&state.floor===false)continue;if(vr.tags?.band&&state.band===false)continue;const sides=C.allowedSides(ex.id,vr.id),side=sides.includes('both')?'both':sides[0];const item=C.makeItem(ex.id,vr.id,side);item.dose=scale(item.dose);item.note=state.note.trim();p.items.push(item)}plan=C.validatePlan(p);return plan}
function renderPatients(q=''){const f=patients.filter(p=>(p.name+' '+p.plan).toLowerCase().includes(q.toLowerCase()));$('#patient-list').innerHTML=f.map(p=>`<button class="patient ${p.id===selected.id?'active':''}" data-patient="${p.id}"><strong>${E(p.name)}</strong>${p.flag?`<span class="flag">${E(p.flag)}</span>`:''}<small>${E(p.plan)} · ${E(p.adherence)}</small></button>`).join('')}
function renderHead(){$('#patient-head').innerHTML=`<div class="patient-title"><div><span class="eyebrow">Aktiv patient · demo</span><h1>${E(selected.name)}</h1><p>${E(selected.plan)} · ${E(selected.adherence)}</p></div><div class="meta">Uppföljning<br><strong>${E(selected.review)}</strong></div></div>`}
function renderBlueprints(){$('#blueprints').innerHTML=Object.entries(M.blueprints).map(([id,b])=>`<button data-choice="blueprint" data-value="${E(id)}">${E(b.name)}</button>`).join('')}
function renderPlan(){try{build();const bp=M.blueprints[state.blueprint];$('#plan-preview').innerHTML=`<span class="eyebrow">Planförslag</span><h2>${E(plan.title)}</h2><p class="goal">${E(plan.goal)}</p><div class="metrics"><div><b>${plan.items.length}</b><span>övningar</span></div><div><b>${C.minutes(plan)}</b><span>min ca</span></div><div><b>${plan.days.length}</b><span>pass/vecka</span></div></div>${plan.items.map((i,n)=>{const {e,v}=C.lookup(i.exercise,i.variant);return `<div class="exercise"><span>${n+1}</span><div><strong>${E(e.name)}</strong><small>${E(v.name)} · ${E(C.doseLabel(i))}</small></div></div>`}).join('')}<div class="review"><strong>Nästa kliniska steg</strong>${plan.reviewDate?'Återbesök '+E(plan.reviewDate)+'.':'Sätt datum för återbesök.'} Progression beslutas efter din utvärdering.</div>`;$('#status').textContent='Förslag uppdaterat · ej distribuerat'}catch(err){$('#plan-preview').innerHTML=`<p class="empty">${E(err.message)}</p>`}}
function render(){renderPatients($('#patient-search')?.value||'');renderHead();document.querySelectorAll('[data-choice]').forEach(b=>b.classList.toggle('active',state[b.dataset.choice]===b.dataset.value));document.querySelectorAll('[data-day]').forEach(b=>b.classList.toggle('active',state.days.includes(Number(b.dataset.day))));$('#goal').value=state.goal;$('#note').value=state.note;$('#review').value=state.reviewDate;$('#floor').checked=state.floor;$('#band').checked=state.band;renderPlan()}
function parse(){const t=$('#dictation').value.toLowerCase(),maps=[['knee_oa',/artros|knäartros/],['knee_tendon',/patellar|patellarsena|hopparknä/],['knee_pf',/patellofem|pfss|knä/],['shoulder_stiff',/frozen|stel axel|frusen/],['shoulder_load',/rotator|axel/],['hip_gtps',/gtps|trochanter|lateral höft|höft/],['achilles',/achilles|hälsena/],['elbow',/epikond|tennisarm|armbåge/],['neck',/nack/],['lumbar',/ländrygg|rygg/]];for(const [id,re] of maps)if(re.test(t)){state.blueprint=id;break}if(/träningsvan|gymvan|idrott/.test(t))state.presentation='concise';if(/ovan|otränad|mer guidning/.test(t))state.presentation='guided';if(/skonsam|reaktiv|tidig/.test(t))state.stage='gentle';if(/högre belastning|sen fas|återgång/.test(t))state.stage='loaded';if(/stöd|balanssvår/.test(t))state.capacity='supported';if(/hög kapacitet|stark/.test(t))state.capacity='high';if(/inte.*golv|ingen matta/.test(t))state.floor=false;if(/utan band|inget band/.test(t))state.band=false;const g=t.match(/mål[: ]+([^.;]+)/);if(g)state.goal=g[1].trim();render()}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.patient){selected=patients.find(p=>p.id===b.dataset.patient)||selected;render()}if(b.dataset.choice){state[b.dataset.choice]=b.dataset.value;render()}if(b.dataset.day){const d=Number(b.dataset.day);state.days=state.days.includes(d)?state.days.filter(x=>x!==d):state.days.concat(d);if(!state.days.length)state.days=[d];render()}if(b.id==='parse')parse();if(['activate','draft','new-patient'].includes(b.id))$('#modal').showModal()});
$('#patient-search').addEventListener('input',e=>renderPatients(e.target.value));['goal','note','review'].forEach(id=>$('#'+id).addEventListener('input',e=>{state[id==='review'?'reviewDate':id]=e.target.value;renderPlan()}));['floor','band'].forEach(id=>$('#'+id).addEventListener('change',e=>{state[id]=e.target.checked;renderPlan()}));renderBlueprints();render();})();