import {reflectionLines} from './patient-loop.mjs?v=2';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const labels={changed_symptoms:'Förändrade besvär eller funktion',changed_environment:'Ändrade förutsättningar',requested_contact:'Önskemål om kontakt',execution_help:'Hjälp med utförandet',training_barrier:'Hinder i träningsvardagen'},states={open:'Nytt',acknowledged:'Kvitterat',resolved:'Bedömt'};
export function mountClinicInbox(host,{api,onOpen,onHandled,onBusy=()=>{}}){
 if(!host||!api.clinicInbox)return {refresh:()=>{},destroy:()=>{}};let status='unresolved',code='all',offset=0,ticket=0,busy=false,destroyed=false;
 host.innerHTML='<section class="clinic-inbox"><div class="inbox-heading"><div><p class="eyebrow">Kliniköversikt</p><h2>Det som behöver dig</h2><p>Återkoppling från dina patienter, samlad på ett ställe.</p></div><button type="button" class="btn ghost" data-inbox-refresh>Uppdatera översikten</button></div><div data-inbox-counts class="inbox-counts"></div><div class="inbox-filters"><label>Status<select data-inbox-status><option value="unresolved">Att hantera</option><option value="open">Nya</option><option value="acknowledged">Kvitterade</option><option value="resolved">Bedömda</option></select></label><label>Orsak<select data-inbox-code><option value="all">Alla orsaker</option>'+Object.entries(labels).map(([k,l])=>'<option value="'+k+'">'+l+'</option>').join('')+'</select></label></div><p data-inbox-message role="status"></p><div data-inbox-list></div><div class="inbox-pages"><button type="button" class="btn ghost" data-page-prev>Föregående</button><span data-inbox-page></span><button type="button" class="btn ghost" data-page-next>Nästa</button></div><p data-inbox-reviews class="ei-footnote"></p><p class="ei-footnote">Förändrade besvär visas först, därefter ändrade förutsättningar, kontaktönskemål och utförande. Äldst först inom varje grupp. Det är en arbetsordning, inte medicinsk triage. Kvitterade ärenden väntar fortfarande på bedömning.</p></section>';
 const q=s=>host.querySelector(s);
 function disable(value){host.querySelectorAll('button,select,textarea').forEach(x=>x.disabled=value)}
 async function load(message=''){
  if(destroyed)return;const mine=++ticket;disable(true);q('[data-inbox-message]').textContent='Hämtar översikten…';q('[data-inbox-list]').replaceChildren();q('[data-inbox-counts]').replaceChildren();q('[data-inbox-reviews]').textContent='';q('[data-inbox-page]').textContent='';
  try{const d=await api.clinicInbox(status,code,offset);if(destroyed||mine!==ticket||!host.isConnected)return;
   if(offset>=d.total&&offset>0){offset=Math.max(0,Math.floor((d.total-1)/25)*25);return load(message)}
   q('[data-inbox-counts]').innerHTML=[['open','Nya'],['acknowledged','Kvitterade'],['resolved','Bedömda']].map(([k,l])=>'<div><strong>'+Number(d.counts[k])+'</strong><span>'+l+'</span></div>').join('');
   q('[data-inbox-list]').innerHTML=d.cases.map(c=>'<details class="inbox-case"><summary><span><b>'+esc(c.display_name)+'</b><small>'+esc(labels[c.code]||c.code)+'</small></span><span class="inbox-state">'+states[c.status]+'</span></summary><p>'+esc(new Date(c.created_at).toLocaleString('sv-SE'))+' · plan v'+Number(c.reflection?.plan_version||c.response?.plan_version||0)+(c.patient_status==='archived'?' · arkiverad patient':'')+'</p>'+(c.reflection?'<p><b>Direkt efter passet</b></p><p>'+reflectionLines(c.reflection).map(esc).join(' · ')+'</p>':'<dl class="runtime-case-answers">'+window.RedaTrainingResponse.questions.map(x=>'<dt>'+esc(x.title)+'</dt><dd>'+esc(x.options.find(([v])=>v===c.response?.answers?.[x.key])?.[1]||'Saknas')+'</dd>').join('')+'</dl>')+(c.handling_note?'<p>'+esc(c.handling_note)+'</p>':'')+(c.patient_status==='active'?'<button type="button" class="btn ghost" data-inbox-open="'+esc(c.patient_id)+'">Öppna patientens uppföljning</button>':'')+(c.status!=='resolved'?'<label>Bedömning eller åtgärd<textarea maxlength="1000" data-inbox-note="'+esc(c.id)+'"></textarea></label><button type="button" class="btn ghost" data-inbox-handle="'+esc(c.id)+'" data-state="acknowledged">Kvittera</button> <button type="button" class="btn primary" data-inbox-handle="'+esc(c.id)+'" data-state="resolved">Spara som bedömt</button>':'')+'</details>').join('')||(status==='unresolved'?'<p>Inga ärenden att hantera för det här filtret.</p>':'<p>Inga ärenden matchar filtret.</p>');
   q('[data-inbox-message]').textContent=message||'Översikten är uppdaterad. Inga meddelanden eller bokningar skickas härifrån.';q('[data-inbox-page]').textContent=d.total?`${offset+1}–${Math.min(offset+25,d.total)} av ${d.total}`:'0 ärenden';
   const r=d.reviews||{agree:0,disagree:0,uncertain:0};q('[data-inbox-reviews]').textContent=`Bedömda motorbeslut: ${r.agree} instämmer · ${r.disagree} avvikande bedömning · ${r.uncertain} osäkra. Varje beslut räknas en gång; detta visar inte motorns kvalitet för samtliga patienter.`;
   disable(false);q('[data-page-prev]').disabled=offset===0;q('[data-page-next]').disabled=offset+25>=d.total;
   host.querySelectorAll('[data-inbox-open]').forEach(b=>b.onclick=async()=>{if(busy||destroyed)return;busy=true;onBusy(true);disable(true);try{await onOpen(b.dataset.inboxOpen)}catch(e){if(destroyed)return;q('[data-inbox-message]').textContent=e.message}finally{busy=false;onBusy(false);if(destroyed)return;disable(false);q('[data-page-prev]').disabled=offset===0;q('[data-page-next]').disabled=offset+25>=d.total}});
   host.querySelectorAll('[data-inbox-handle]').forEach(b=>b.onclick=async()=>{if(busy||destroyed)return;busy=true;onBusy(true);disable(true);try{await api.handleCase(b.dataset.inboxHandle,b.dataset.state,q('[data-inbox-note="'+b.dataset.inboxHandle+'"]').value);await load('Ärendets status är sparad.');if(!destroyed)await onHandled?.()}catch(e){if(destroyed)return;q('[data-inbox-message]').textContent=e.message;disable(false);q('[data-page-prev]').disabled=offset===0;q('[data-page-next]').disabled=offset+25>=d.total}finally{busy=false;onBusy(false)}});
  }catch(e){if(destroyed||mine!==ticket)return;q('[data-inbox-message]').textContent='Översikten kunde inte hämtas. '+e.message;disable(false);q('[data-page-prev]').disabled=true;q('[data-page-next]').disabled=true}
 }
 q('[data-inbox-status]').onchange=e=>{status=e.target.value;offset=0;load()};q('[data-inbox-code]').onchange=e=>{code=e.target.value;offset=0;load()};q('[data-inbox-refresh]').onclick=()=>load();q('[data-page-prev]').onclick=()=>{offset=Math.max(0,offset-25);load()};q('[data-page-next]').onclick=()=>{offset+=25;load()};load();return {refresh:load,destroy(){destroyed=true;++ticket;host.replaceChildren()}};
}
