import * as api from './secure-browser.mjs'
const $=id=>document.getElementById(id), C=window.RedaClinical, P=window.RedaPlanner
let selected=null,patients=[],plan=null,draft=null,mfaFactor=null
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
const Care=window.RedaCare;
let selectionRequest=0,loadingPatient=false,working=false;
function setWorking(value){working=value;$('newPatient').disabled=value;$('logout').disabled=value;$('editor').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=value);document.querySelectorAll('[data-edit],[data-patient]').forEach(el=>el.disabled=value);$('saveDraft').disabled=value;$('activate').disabled=value}
function updatePlanText(){if(!plan||loadingPatient||working)return;plan={...plan,goal:$('goal').value.trim(),clinicianNote:$('note').value.trim(),presentation:$('guidance').value};invalidate();renderPlan()}
function careForm(){const weeks=Number($('careWeeks').value);return Care.normalize({mode:$('careMode').value,weeks,startDate:$('careStart').value,assessment:{confirmed:$('careAssessed').checked,date:$('assessmentDate').value,method:$('assessmentMethod').value},checkpoints:weeks?['review1','review2','closing'].map(id=>({id,date:$('care-'+id+'-date').value,method:$('care-'+id+'-method').value})):($('reviewDate').value?[{id:'review',date:$('reviewDate').value,method:$('careMode').value==='clinic'?'clinic':$('assessmentMethod').value}]:[])})}
function careVisibility(){const period=Number($('careWeeks').value)>0;$('carePackage').hidden=!period;$('singleReviewField').classList.toggle('hidden',period);$('careAssessment').hidden=$('careMode').value==='clinic'}
function fillCare(payload={}){const c=Care.read(payload);$('careMode').value=c.mode;$('careWeeks').value=String(c.weeks);$('careStart').value=c.startDate;$('careAssessed').checked=c.assessment.confirmed;$('assessmentDate').value=c.assessment.date;$('assessmentMethod').value=c.assessment.method;$('reviewDate').value=payload.reviewDate||'';for(const id of ['review1','review2','closing']){const p=c.checkpoints.find(x=>x.id===id);$('care-'+id+'-date').value=p?.date||'';$('care-'+id+'-method').value=p?.method||(c.mode==='clinic'?'clinic':'video')}careVisibility()}
function careProblems(){return plan?Care.issues(plan.careJourney||{}):[]}
function showCarePreview(){if(!plan){$('carePlanPreview').textContent='';return}const c=Care.overview(plan);$('carePlanPreview').innerHTML=`<strong>${esc(c.label)}${c.weeks?' · '+c.weeks+' veckor':''}</strong>`+(c.weeks?`${esc(Care.displayDate(c.startDate))}–${esc(Care.displayDate(c.endDate))}<br>`:'')+c.points.map(x=>`${esc(x.label)}: ${esc(x.dateLabel)} · ${esc(x.contact)}`).join('<br>');const problems=careProblems();$('careIssues').innerHTML=problems.length?'<b>Före aktivering</b>'+problems.map(x=>'<p>'+esc(x)+'</p>').join(''):''}
function updateCare(){careVisibility();if(!plan||loadingPatient||working)return;try{plan=Care.attach(plan,careForm());invalidate();renderPlan()}catch(e){delivery('<b>Kontrollera uppföljningen.</b><span>'+esc(e.message)+'</span>','error');$('activate').disabled=true}}

function err(e){$('authError').textContent=e?.message||String(e);$('authError').classList.remove('hidden')}function clearErr(){$('authError').classList.add('hidden')}function setAuth(show){$('auth').classList.toggle('hidden',!show);$('app').classList.toggle('hidden',show);$('logout').classList.toggle('hidden',show)}
function setStatus(text,type=''){$('syncStatus').textContent=text;$('syncStatus').className='save-state'+(type?' '+type:'')}
function delivery(text,type='success'){const el=$('deliveryStatus');el.className=`delivery-status ${type}`;el.innerHTML=text}
function clearDelivery(){$('deliveryStatus').className='delivery-status hidden';$('deliveryStatus').textContent=''}
function blueprints(){return Object.values(C?.blueprints||P?.blueprints||{})}function fillBlueprints(){const el=$('blueprint');el.innerHTML=blueprints().map(b=>`<option value="${esc(b.id||Object.keys(C.blueprints).find(k=>C.blueprints[k]===b))}">${esc(b.name)}</option>`).join('');if(!el.options.length)throw Error('Kliniska grundplaner kunde inte laddas.')}
function adviceText(){const preset=$('advicePreset').value,stage=$('stage').value;const map={quality:'Prioritera lugnt och kontrollerat utförande. Håll dig till dosen i planen och notera hur övningarna fungerar till återbesöket.',routine:'Försök få in passen enligt veckoplanen. Det viktigaste nu är regelbundenhet och att du håller dig till den ordinerade nivån.',confidence:'Belasta inom den nivå vi gått igenom och låt rörelsen kännas trygg och kontrollerad. Vi utvärderar nästa steg tillsammans vid uppföljningen.'};if(map[preset])return map[preset];if(preset==='custom')return $('note').value;return stage==='protected'?'Håll dig till den här nivån och prioritera lugnt, kontrollerat utförande. Vi utvärderar hur kroppen svarat vid uppföljningen.':stage==='higher'?'Följ den valda belastningen och håll samma kvalitet genom hela passet. Vi utvärderar nästa progression vid uppföljningen.':'Arbeta lugnt och kontrollerat enligt dosen i programmet. Vi utvärderar nästa steg tillsammans vid uppföljningen.'}
function applyAdvice(rebuild=false){if($('advicePreset').value!=='custom'){$('note').value=adviceText();$('note').dataset.auto='1'}else $('note').dataset.auto='0';if(rebuild===true||!plan){invalidate();build()}else updatePlanText()}
function invalidate(){draft=null;clearDelivery();setStatus('Ändringar ej aktiverade')}
function renderPatients(){$('patientCount').textContent=`${patients.length} aktiva`;$('patients').innerHTML=patients.length?patients.map(p=>`<button class="patient ${selected?.id===p.id?'active':''}" data-patient="${p.id}"><span class="patient-avatar">${esc((p.display_name||'?').trim().charAt(0).toUpperCase())}</span><span class="patient-copy"><b>${esc(p.display_name)}</b><small>${p.auth_user_id?'Ansluten':'Ny · ej ansluten'}</small></span></button>`).join(''):'<div class="muted">Inga patienter ännu.</div>';document.querySelectorAll('[data-patient]').forEach(b=>b.onclick=()=>selectPatient(b.dataset.patient))}
async function loadPatients(){patients=await api.listPatients();renderPatients()}
async function selectPatient(id){
 if(working)return;const ticket=++selectionRequest;selected=patients.find(p=>p.id===id);if(!selected)return;loadingPatient=true;plan=null;draft=null;clearDelivery();$('carePlanPreview').textContent='';$('progressionEditor').replaceChildren();$('careIssues').textContent='';$('planExercises').textContent='';$('planMeta').textContent='–';$('saveDraft').disabled=true;$('activate').disabled=true;
 $('patientTitle').textContent=selected.display_name;$('noPatient').classList.add('hidden');$('editor').classList.remove('hidden');$('patientEmail').value='';$('goal').value='';$('note').value='';$('advicePreset').value='auto';fillCare();
 for(const [field,value] of Object.entries({stage:'build',capacity:'standard',trainingHistory:'regular',goalProfile:'daily',guidance:'guided',equipment:'both'}))if($(field))$(field).value=value;
 $('floorOK').checked=true;$('band').checked=true;$('blueprint').selectedIndex=0;
 $('patientEmail').closest('.field').classList.toggle('connected-patient',!!selected.auth_user_id);$('patientEmail').placeholder=selected.auth_user_id?'Patienten är redan ansluten':'Behövs vid första anslutningen';renderPatients();setStatus('Hämtar patientens plan…');
 $('editor').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);
 try{
  const data=await api.patientSummary(id);if(ticket!==selectionRequest||selected?.id!==id)return;
  const active=data.plans.find(p=>p.status==='active'),saved=active?.payload;fillCare(saved||{});loadingPatient=false;
  $('editor').querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=false);
  if(saved?.schema===6&&Array.isArray(saved.exercises)){
   for(const field of ['blueprintId','stage','capacity','trainingHistory','goalProfile','equipment']){const target=field==='blueprintId'?'blueprint':field,value=saved.context?.[field]||saved[field];if($(target)&&value)$(target).value=value}
   $('guidance').value=saved.presentation||'guided';$('floorOK').checked=saved.context?.floorOK!==false;$('band').checked=saved.context?.band!==false;$('goal').value=saved.goal||'';$('note').value=saved.clinicianNote||'';$('advicePreset').value='custom';plan=Care.attach({...saved,patientName:selected.display_name},careForm());renderPlan();setStatus('Utgår från aktuell plan · v'+active.version);
  }else{applyAdvice();setStatus(selected.auth_user_id?'Ansluten patient':'Ny patient')}
  await renderFollowup(data);
 }catch(e){if(ticket===selectionRequest){setStatus('Planen kunde inte hämtas','warn');delivery('<b>Välj patienten igen för att försöka på nytt.</b><span>'+esc(e.message)+'</span>','error')}}
}
function build(){if(!selected||loadingPatient||working)return;try{plan=P.buildProgram({blueprintId:$('blueprint').value,stage:$('stage').value,capacity:$('capacity').value,trainingHistory:$('trainingHistory')?.value||'regular',goalProfile:$('goalProfile')?.value||'daily',guidance:$('guidance').value,equipment:$('equipment').value,floorOK:$('floorOK').checked,band:$('band').checked,goal:$('goal').value.trim(),clinicianNote:$('note').value.trim(),reviewDate:$('reviewDate').value,patientName:selected.display_name});plan=Care.attach(plan,careForm());renderPlan()}catch(e){plan=null;$('planMeta').textContent='–';$('planExercises').innerHTML='';setStatus('Planen behöver justeras','warn');$('saveDraft').disabled=true;$('activate').disabled=true;delivery(`<b>Kan inte bygga planen.</b><span>${esc(e.message)}</span>`,'error')}}
function tierLabel(t){return t==='performance'?'Performance':t==='advanced'?'Fördjupad':'Grundnivå'}
function renderPlan(){window.RedaProgressionEditor.render($('progressionEditor'),plan,next=>{if(working||loadingPatient)return;plan=next;invalidate();renderPlan()});const ex=plan?.exercises||[],labels={both:'Båda sidor, en i taget',left:'Vänster',right:'Höger',simultaneous:'Båda samtidigt'};$('planMeta').textContent=`${ex.length} övningar`;$('planSub').textContent=`${plan?.schedule?.days?.length||0} pass/vecka · ${plan?.blueprintName||''} · ${tierLabel(plan?.intelligenceTier)}`;$('planExercises').innerHTML=ex.map((x,i)=>`<div class="plan-exercise"><span>${i+1}</span><div><b>${esc(x.name)}</b><small>${esc(x.variantLabel||'')} · ${esc(x.dose?.label||'')}</small><small class="intelligence-note">${esc(x.why||'')}</small><details class="prescription-edit"><summary>Justera variant och dos${x.editedByClinician?' · anpassad':''}</summary><div class="dose-fields"><label>Variant<select data-edit="variantId" data-index="${i}">${P.alternatives(plan,i).map(v=>`<option value="${esc(v.id)}" ${v.id===x.variantId?'selected':''}>${esc(v.name)}</option>`).join('')}</select></label><label>Sida<select data-edit="side" data-index="${i}">${P.allowedSides(x.id,x.variantId).map(v=>`<option value="${v}" ${v===x.side?'selected':''}>${labels[v]}</option>`).join('')}</select></label>${[['sets','Omgångar',1,8],['reps','Repetitioner',1,100],['hold','Hålltid, sek',0,180],['rest','Vila, sek',0,600],['tempo','Rörelsecykel, sek',1,60]].map(([k,label,min,max])=>`<label>${label}<input type="number" min="${min}" max="${max}" data-edit="${k}" data-index="${i}" value="${Number(x.dose[k]||min)}"></label>`).join('')}<label>Ordinerad belastning<input data-edit="prescribedLoad" data-index="${i}" maxlength="100" placeholder="Valfritt, t.ex. vikt eller individuell intensitet" value="${esc(x.prescribedLoad||'')}"></label></div></details></div></div>`).join('');showCarePreview();const blocked=working||loadingPatient||!ex.length||!!plan.warnings?.length;$('saveDraft').disabled=blocked;$('activate').disabled=blocked||careProblems().length>0;$('activate').textContent=selected?.auth_user_id?'Aktivera för patient':'Aktivera & bjud in';if(plan.warnings?.length)delivery('<b>Förslaget är inte komplett.</b><span>'+plan.warnings.map(esc).join('<br>')+'</span>','error');document.querySelectorAll('[data-edit]').forEach(el=>el.onchange=()=>{try{plan=P.editExercise(plan,Number(el.dataset.index),{[el.dataset.edit]:el.value});invalidate();renderPlan()}catch(e){delivery('<b>Ändringen kunde inte sparas.</b><span>'+esc(e.message)+'</span>','error')}})}
async function saveDraft(){if(!selected||!plan||loadingPatient||working||plan.warnings?.length)return;setWorking(true);try{$('saveDraft').disabled=true;setStatus('Sparar…','working');draft=await api.createDraft(selected.id,plan);setStatus(`Sparad för senare · v${draft.version}`,'success');delivery('<b>Utkast sparat.</b><span>Planen är inte synlig för patienten ännu.</span>','neutral')}catch(e){setStatus('Kunde inte spara','warn');delivery(`<b>Utkastet sparades inte.</b><span>${esc(e.message)}</span>`,'error')}finally{setWorking(false);renderPlan()}}
async function activate(){if(!selected||!plan||loadingPatient||working||plan.warnings?.length)return;if(careProblems().length){showCarePreview();return}const button=$('activate'),save=$('saveDraft');let workingDraft=draft;setWorking(true);try{button.disabled=true;save.disabled=true;clearDelivery();if(!workingDraft){setStatus('Förbereder plan…','working');workingDraft=await api.createDraft(selected.id,plan)}let invited=false;if(!selected.auth_user_id){const email=$('patientEmail').value.trim();if(!email)throw Error('Ange patientens e-postadress för första anslutningen.');setStatus('Skapar patientåtkomst…','working');await api.invitePatient(selected.id,email);selected.auth_user_id='linked';invited=true}setStatus('Aktiverar…','working');await api.activatePlan(workingDraft.id);const version=workingDraft.version;draft=null;setStatus(`Aktiv · version ${version}`,'success');delivery(invited?`<b>✓ Plan v${version} är aktiverad.</b><span>Patientkontot är skapat och inbjudan har lämnats till e-posttjänsten.</span>`:`<b>✓ Plan v${version} är aktiverad.</b><span>Patienten är redan ansluten och ser den nya planen i Reda.</span>`,'success');const id=selected.id;await loadPatients();selected=patients.find(p=>p.id===id)||selected;renderPatients();await renderFollowup();button.textContent='Planen är aktiv ✓';button.textContent='Planen är aktiv ✓'}catch(e){setStatus('Inte färdig','warn');delivery(`<b>Aktiveringen stoppades.</b><span>${esc(e.message)}</span>`,'error');button.disabled=false}finally{setWorking(false);renderPlan()}}
let followupRequest=0;
async function renderFollowup(provided){
 const request=++followupRequest,patientId=selected?.id;
 $('followup').textContent=patientId?'Hämtar uppföljning…':'Välj en patient för att se uppföljning.';
 if(!patientId)return;
 try{
  const data=provided?.plans&&provided?.sessions?provided:await api.patientSummary(patientId);
  if(request!==followupRequest||selected?.id!==patientId)return;
  const published=data.plans.filter(p=>p.status!=='draft'&&p.activated_at);
  if(!published.length){$('followup').textContent='Ingen aktiverad plan att följa upp ännu.';return}
  const initial=published.find(p=>p.status==='active')||published[0];
  $('followup').innerHTML='<div class="follow-version"><label for="reviewVersion">Programversion</label><select id="reviewVersion">'+published.map(p=>`<option value="${esc(p.id)}" ${p.id===initial.id?'selected':''}>Version ${p.version}${p.status==='active'?' · aktuell':' · tidigare'}</option>`).join('')+'</select></div><div id="reviewSummary"></div>';
  const date=d=>d?d.slice(8,10)+'/'+d.slice(5,7)+' '+d.slice(0,4):'Ej bestämt';
  function draw(){
   const f=window.RedaFollowup.build({...data,planId:$('reviewVersion').value}),p=f.plan.payload,issues=f.exercises.filter(x=>x.heavy||x.skipped).sort((a,b)=>(b.heavy+b.skipped)-(a.heavy+a.skipped));
   let html=`<div class="review-context"><p class="eyebrow">Patientens mål · version ${f.plan.version}</p><h3>${esc(p.goal||'Inget mål angivet i planen.')}</h3><p>Planerad uppföljning: ${esc(date(p.reviewDate))}</p></div>`;
   const contact=Care.overview(p);html+=`<div class="care-overview"><p class="eyebrow">${esc(contact.label)}${contact.weeks?' · '+contact.weeks+' veckor':''}</p><p>Planerade kontakter för denna version. Tid och genomförande bekräftas separat.</p><ol class="care-timeline">${contact.points.map(x=>`<li><div><strong>${esc(x.label)}</strong><small>${esc(x.dateLabel)} · ${esc(x.contact)}${x.passed?' · datum passerat':''}</small></div></li>`).join('')||'<li>Ingen kontakt planerad ännu.</li>'}</ol></div>`;
   if(f.emptyPeriod){html+='<p class="review-empty">Planen har ännu inga hela avslutade dagar att följa upp.</p>'}
   else{
    html+=`<p class="review-period">${date(f.start)}–${date(window.RedaFollowup.shift(f.end,-1))} · högst 14 hela dagar för denna version.</p>`;
    if(issues.length)html+='<div class="review-issues"><h3>Ta upp vid avstämningen</h3>'+issues.map(x=>`<p><b>${esc(x.name)}</b>${x.variant?' · '+esc(x.variant):''}<br>${[x.heavy?x.heavy+' rapporter om för tungt':'',x.skipped?x.skipped+' överhoppade tillfällen':''].filter(Boolean).join(' · ')}</p>`).join('')+'</div>';
    html+=`<div class="follow-metrics"><div><strong>${f.completed}</strong><span>genomförda pass</span></div><div><strong>${f.partial}</strong><span>påbörjade/delvisa</span></div><div><strong>${f.hasSchedule&&!f.limited?f.fulfilled+' / '+f.scheduled:'–'}</strong><span>planerade dagar med genomfört pass</span></div></div>`;
    html+=`<p class="review-limit">${f.limited?'Underlaget kan vara ofullständigt: endast de 30 senaste passen är hämtade. Därför visas ingen jämförelse med planerade dagar.':!f.hasSchedule?'Planen saknar angivna träningsdagar. Därför visas ingen jämförelse med planerade dagar.':'Flera pass samma dag räknas som en träningsdag. '+(f.unplannedDays?f.unplannedDays+' träningsdagar ligger utanför de planerade dagarna.':'')} Saknad registrering betyder inte säkert att träningen uteblivit.</p>`;
    html+='<div class="review-exercises"><h3>Övning för övning</h3>'+f.exercises.map(x=>`<details><summary>${esc(x.name)}<span>${esc(x.variant)}${x.dose?' · '+esc(x.dose):''}</span></summary><dl>${[['Genomförd',x.completed],['Delvis',x.partial],['Överhoppad',x.skipped],['Lätt',x.easy],['Lagom',x.okay],['För tungt',x.heavy]].map(([label,n])=>`<div><dt>${label}</dt><dd>${n}</dd></div>`).join('')}</dl><p>Antal registrerade tillfällen under perioden. Skattning ändrar inte ordinationen.</p></details>`).join('')+'</div>';
    html+='<div class="activity-list">'+f.rows.slice(0,5).map(x=>`<div class="activity-row"><span class="activity-dot"></span><div><b>${esc(x.status==='completed'?'Genomfört':x.status==='partial'?'Delvis genomfört':x.status==='started'?'Påbörjat':x.status)}</b><small>${date(window.RedaFollowup.day(x.started_at))} · plan v${x.plan_version}</small></div></div>`).join('')+(f.rows.length?'':'<p class="review-empty">Inga registrerade pass för denna version under perioden.</p>')+'</div>';
   }
   html+=`<p class="review-limit">${f.todaySessions?f.todaySessions+' registrerade pass idag ingår inte i perioden. ':''}Planens aktiveringsdag och dagens ännu pågående dag ingår inte. Progression kräver din kliniska bedömning.</p>`;
   $('reviewSummary').innerHTML=html;
  }
  $('reviewVersion').onchange=draw;draw();
 }catch(e){if(request===followupRequest&&selected?.id===patientId)$('followup').textContent='Kunde inte läsa uppföljning: '+e.message}
}
function switchWorkTab(name){document.querySelectorAll('[data-worktab]').forEach(b=>b.classList.toggle('active',b.dataset.worktab===name));$('ordinationView').classList.toggle('hidden',name!=='ordination');$('followupView').classList.toggle('hidden',name!=='followup');if(name==='followup')renderFollowup()}
async function finishClinicianAuth(){clearErr();const a=await api.aal();if(a.currentLevel!=='aal2'){const f=await api.factors(),verified=f?.totp?.find(x=>x.status==='verified');if(verified){mfaFactor=verified.id;$('mfa').classList.remove('hidden');$('qr').classList.add('hidden');$('secret').textContent='Ange koden från din autentiseringsapp.';return}const enrolled=await api.enrollTotp();mfaFactor=enrolled.id;$('qr').src=enrolled.totp.qr_code;$('qr').classList.remove('hidden');$('secret').textContent='Skanna QR-koden och ange sedan koden.';$('mfa').classList.remove('hidden');return}await api.claimClinician();const profile=await api.clinicianProfile();if(profile?.role!=='clinician')throw Error('Kontot saknar behandlarbehörighet');setAuth(false);await loadPatients()}
$('login').onclick=async()=>{try{clearErr();await api.signIn($('email').value.trim(),$('password').value);await finishClinicianAuth()}catch(e){err(e)}};$('verifyMfa').onclick=async()=>{try{await api.verifyTotp(mfaFactor,$('mfaCode').value.trim());await finishClinicianAuth()}catch(e){err(e)}};$('logout').onclick=async()=>{await api.signOut();location.reload()};$('newPatient').onclick=async()=>{if(working)return;const name=prompt('Patientens namn');if(!name?.trim())return;try{const p=await api.createPatient(name.trim());await loadPatients();await selectPatient(p.id)}catch(e){alert('Kunde inte skapa patient: '+e.message)}};$('saveDraft').onclick=saveDraft;$('activate').onclick=activate;$('refresh').onclick=renderFollowup;$('advicePreset').onchange=()=>applyAdvice();$('note').oninput=()=>{$('advicePreset').value='custom';$('note').dataset.auto='0';updatePlanText()};document.querySelectorAll('[data-worktab]').forEach(b=>b.onclick=()=>switchWorkTab(b.dataset.worktab));['blueprint','capacity','trainingHistory','goalProfile','equipment','floorOK','band'].forEach(id=>$(id)?.addEventListener(id==='goal'?'input':'change',()=>{invalidate();build()}));$('stage').onchange=()=>{if($('advicePreset').value==='auto')applyAdvice(true);else{invalidate();build()}};
try{fillBlueprints();applyAdvice()}catch(e){console.error(e)}setAuth(true);api.currentUser().then(u=>u&&finishClinicianAuth()).catch(()=>{})
for(const id of ['careMode','careWeeks','careStart','careAssessed','assessmentDate','assessmentMethod','reviewDate',...['review1','review2','closing'].flatMap(id=>['care-'+id+'-date','care-'+id+'-method'])])$(id).addEventListener('change',()=>{if(id==='careMode'&&$('careMode').value!=='clinic'){for(const k of ['review1','review2','closing'])$('care-'+k+'-method').value='video';$('assessmentMethod').value='video'}updateCare()});
$('suggestContacts').onclick=()=>{try{const points=Care.suggest($('careStart').value,Number($('careWeeks').value),$('careMode').value==='clinic'?'clinic':'video');for(const p of points){$('care-'+p.id+'-date').value=p.date;$('care-'+p.id+'-method').value=p.method}updateCare()}catch(e){delivery('<b>Datumen kunde inte föreslås.</b><span>'+esc(e.message)+'</span>','error')}};

$('goal').addEventListener('input',updatePlanText);$('guidance').addEventListener('change',updatePlanText);
