import {createMovementLesson} from './movement-lesson.mjs?v=3';
import {mountExercisePlayer} from './exercise-player.mjs?v=1';
import {createExerciseCoach} from './exercise-coach.mjs?v=20260912-coach1';
import {helpSummary} from './exercise-help-model.mjs?v=20260912-coach1';
const $=id=>document.getElementById(id),S=window.RedaSession;
const examples=[
 {id:'chair',name:'Uppresning från stol',motionKey:'sit-to-stand.support',side:'simultaneous',support:'Stol med armstöd',instructions:['Placera fötterna stadigt framför stolen.','Luta överkroppen framåt och res dig med handstöd.','Sätt dig tillbaka kontrollerat.']},
 {id:'extension',name:'Benspark från stol',motionKey:'knee-extension.seated',side:'left',support:'Stol med ryggstöd',instructions:['Sitt med låret kvar mot stolen.','Sträck underbenet enligt rörelseomfånget i din plan.','Återgå till startläget.']},
 {id:'calf',name:'Tåhävning',motionKey:'calf-raise.bilateral',side:'simultaneous',support:'Stabilt handstöd framför kroppen',instructions:['Placera båda fötterna på golvet och ta stöd med händerna.','Lyft hälarna med framfoten kvar i golvet.','Sänk hälarna kontrollerat.']},
 {id:'bridge',name:'Höftlyft',motionKey:'bridge.bilateral',side:'simultaneous',support:'Matta på golvet',instructions:['Ligg på rygg med böjda knän och fötterna mot underlaget.','Lyft bäckenet enligt instruktionen i din plan.','Sänk tillbaka med skuldror och fötter kvar mot underlaget.']},
 {id:'step',name:'Step-up med stöd',motionKey:'step-up.supported',side:'left',support:'Stabilt steg och handstöd',instructions:['Placera den sida du tränar på steget.','Kliv upp med handstöd.','Återgå kontrollerat till startläget.']}
].map(x=>({...x,equipment:x.support,prescribedRange:'Följ det rörelseomfång du och behandlaren har gått igenom.',dose:{sets:2,reps:8,hold:0,rest:45,label:'2 omgångar · 8 repetitioner'}}));
let current=examples[0],session=null;const lesson=createMovementLesson($('movementLesson')),shell=mountExercisePlayer($('player'),{lesson});
const coach=createExerciseCoach($('exerciseCoach'),{preview:true,api:{submitExerciseHelp:async(s,id,rid,body)=>({id:rid,...body,exercise:current,exercise_name:current.name,plan_version:1,option_label:'Fiktivt exempel'})},onSaved:h=>{
 const host=$('guideResult');host.hidden=false;host.replaceChildren();const title=document.createElement('h3');title.textContent=h.outcome==='clear'?'Så skulle din återkoppling registreras':'Så skulle underlaget visas för behandlaren';host.append(title);const list=document.createElement('ul');for(const line of helpSummary(h)){const li=document.createElement('li');li.textContent=line;list.append(li)}host.append(list);
},onDemonstrate:(t,f,scroll)=>{lesson.showFrame(t===null?lesson.position():t,f);if(scroll){shell.closePanels();$('motionStudio').focus()}}});
function render(){const p=session.progress[0],rounds=S.rounds(current),active=rounds[Math.min(p.roundsDone,rounds.length-1)];$('player').dataset.complete=String(p.roundsDone>=rounds.length||p.status==='skipped');$('pos').textContent=(Number($('guideExercise').value)+1)+' av '+examples.length;$('sessionProgressText').textContent=p.roundsDone+' av '+rounds.length+' omgångar registrerade';$('sessionProgress').max=rounds.length;$('sessionProgress').value=p.roundsDone;$('exName').textContent=current.name;$('dose').textContent=current.dose.label;$('next').textContent='Nästa övning';$('next').disabled=p.roundsDone<rounds.length&&p.status!=='skipped';$('rounds').replaceChildren();rounds.forEach((r,i)=>{const b=document.createElement('button');b.className='round';b.type='button';b.dataset.round=String(i);b.disabled=i!==p.roundsDone;b.textContent='Omgång '+r.set+' klar';b.onclick=()=>{session=S.mark(session,0,i);render();if(session.progress[0].roundsDone<rounds.length)shell.startRest(current.dose.rest)};$('rounds').append(b)});lesson.setExercise(current,{exerciseSide:active?.side||current.side,contextId:'preview'});coach.setExercise({plan:{id:'example-'+current.id+'-'+current.side,version:1},exercise:current,sessionId:session.id});document.querySelectorAll('[data-effort]').forEach(b=>{b.setAttribute('aria-pressed',String(p.feedback===b.dataset.effort));b.onclick=()=>{p.feedback=b.dataset.effort;render()}});$('exerciseHelp').textContent=current.instructions.join(' ');$('exerciseWhy').textContent=current.prescribedRange;$('playerSaveStatus').textContent='Fiktivt pass · Ingenting sparas';}
function choose(){lesson.pause();shell.endRest();shell.closePanels();current={...examples[Number($('guideExercise').value)]};const bilateral=current.side==='simultaneous';$('guideSide').disabled=bilateral;$('guideSide').closest('label').hidden=bilateral;if(!bilateral)current.side=$('guideSide').value;$('guideResult').hidden=true;session=S.create([current],crypto.randomUUID(),new Date().toISOString());render();}
$('guideExercise').innerHTML=examples.map((x,i)=>`<option value="${i}">${x.name}</option>`).join('');$('guideExercise').onchange=choose;$('guideSide').onchange=choose;
$('next').onclick=()=>{$('guideExercise').value=String((Number($('guideExercise').value)+1)%examples.length);choose()};$('skip').onclick=()=>{shell.endRest();shell.closePanels();session.progress[0].status='skipped';render()};$('closePlayer').onclick=choose;choose();
