import {createMovementLesson} from './movement-lesson.mjs?v=4';
import {mountExercisePlayer} from './exercise-player.mjs?v=1';
import {createExercisePreview,renderExerciseOverview,renderPreparation,doseText} from './patient-journey.mjs?v=1';
import {createExerciseCoach} from './exercise-coach.mjs?v=20260912-coach1';
import {helpSummary} from './exercise-help-model.mjs?v=20260912-coach1';
const $=id=>document.getElementById(id),S=window.RedaSession;
const exercises=[
 {id:'chair',name:'Uppresning från stol',motionKey:'sit-to-stand.support',side:'simultaneous',support:'Stol med armstöd',why:'För att göra det lättare att komma upp från en stol i vardagen.',instructions:['Placera fötterna stadigt framför stolen.','Luta överkroppen framåt och res dig med handstöd.','Sätt dig tillbaka kontrollerat.']},
 {id:'extension',name:'Benspark från stol',motionKey:'knee-extension.seated',side:'left',support:'Stol med ryggstöd',why:'För att träna framsidan av låret med stöd från stolen.',instructions:['Sitt med låret kvar mot stolen.','Sträck underbenet enligt rörelseomfånget i din plan.','Återgå till startläget.']},
 {id:'calf',name:'Tåhävning',motionKey:'calf-raise.bilateral',side:'simultaneous',support:'Stabilt handstöd',why:'För att träna vaderna i stående med ett stabilt stöd.',instructions:['Placera båda fötterna på golvet och ta stöd med händerna.','Lyft hälarna med framfoten kvar i golvet.','Sänk hälarna kontrollerat.']}
].map(x=>({...x,equipment:x.support,prescribedRange:'Följ det rörelseomfång du och behandlaren har gått igenom.',dose:{sets:2,reps:8,hold:0,rest:45,label:'2 omgångar · 8 repetitioner'}}));
let session=null,index=0,finished=false,reflection=null;const events=[];
const preview=createExercisePreview(),lesson=createMovementLesson($('movementLesson')),shell=mountExercisePlayer($('player'),{lesson});
const current=()=>exercises[index];
function log(text){events.unshift({text,time:new Date()});renderLog()}
function renderLog(){const host=$('demoLog');host.replaceChildren();for(const e of events){const li=document.createElement('li');li.textContent=e.text;const t=document.createElement('small');t.textContent=e.time.toLocaleString('sv-SE',{day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'});li.append(t);host.append(li)}if(!events.length)host.textContent='Inga händelser ännu. När du provar passet visas dina markeringar här.'}
const coach=createExerciseCoach($('exerciseCoach'),{preview:true,api:{submitExerciseHelp:async(s,id,rid,body)=>({id:rid,...body,exercise:current(),exercise_name:current().name,plan_version:1,option_label:'Fiktivt exempel'})},onSaved:h=>{
 const host=$('guideResult');host.hidden=false;host.replaceChildren();const title=document.createElement('h3');title.textContent=h.outcome==='clear'?'Så skulle din återkoppling registreras':'Så skulle underlaget visas för behandlaren';host.append(title);const list=document.createElement('ul');for(const line of helpSummary(h)){const li=document.createElement('li');li.textContent=line;list.append(li)}host.append(list);log('Provat hjälp med '+current().name+'. Inget skickades.');
},onDemonstrate:(t,f,scroll)=>{lesson.showFrame(t===null?lesson.position():t,f);if(scroll){shell.closePanels();$('motionStudio').focus()}}});
function tab(name){lesson.pause();document.querySelectorAll('[data-tab]').forEach(b=>{b.classList.toggle('active',b.dataset.tab===name);if(b.dataset.tab===name)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});document.querySelectorAll('.tab').forEach(t=>t.classList.toggle('hidden',t.id!==name));window.scrollTo(0,0)}
function home(){
 const onPreview=x=>preview.open(x,{contextId:'example-plan-1'});
 renderExerciseOverview($('todayExercises'),{exercises,progress:session?.progress||[],onPreview});renderExerciseOverview($('programExercises'),{exercises,progress:session?.progress||[],onPreview});renderPreparation($('todayPreparation'),exercises);
 $('start').textContent=finished?'Prova passet igen':session?'Fortsätt passet':'Starta passet';$('todayTitle').textContent=finished?'Dagens pass är registrerat':session?'Fortsätt där du slutade':'Dagens träning';$('todayCard').dataset.dayState=finished?'done':session?'resume':'train';$('todayDetail').textContent=finished?'Du kan se dina markeringar och öppna övningarna igen.':session?'Dina markeringar finns kvar medan du provar exemplet.':'Tre övningar i din takt. Din ordination följer med genom hela passet.';
 $('followTitle').textContent=finished?'Du har provat ett helt pass.':'Inget avslutat pass i exemplet.';$('followDetail').textContent=reflection?'Du har lämnat återkoppling i exemplet. Inget har skickats.':finished?'Berätta vad som fungerade och vad som blev svårt.':'När du avslutar passet kan du lämna återkoppling.';$('followAction').textContent=finished&&!reflection?'Berätta hur det gick':'Till dagens plan';
}
function render(){const x=current(),p=session.progress[index],rounds=S.rounds(x),active=rounds[Math.min(p.roundsDone,rounds.length-1)];$('player').dataset.complete=String(p.roundsDone>=rounds.length||p.status==='skipped');$('pos').textContent=(index+1)+' av '+exercises.length;const done=session.progress.reduce((n,p)=>n+p.roundsDone,0),total=exercises.reduce((n,x)=>n+S.rounds(x).length,0);$('sessionProgressText').textContent=done+' av '+total+' omgångar registrerade';$('sessionProgress').max=total;$('sessionProgress').value=done;$('playerCurrentRound').textContent='Omgång '+Math.min(rounds.length,p.roundsDone+1)+' av '+rounds.length;$('exName').textContent=x.name;$('dose').textContent=doseText(x);$('next').textContent=index===exercises.length-1?'Avsluta pass':'Nästa övning';$('next').disabled=p.roundsDone<rounds.length&&p.status!=='skipped';$('rounds').replaceChildren();rounds.forEach((r,i)=>{const b=document.createElement('button');b.className='round';b.type='button';b.dataset.round=String(i);b.disabled=i!==p.roundsDone;b.textContent='Omgång '+r.set+' klar'+(r.side==='left'?' · vänster':r.side==='right'?' · höger':'');b.onclick=()=>{if(i!==session.progress[index].roundsDone)return;session=S.mark(session,index,i);render();if(session.progress[index].roundsDone<rounds.length)shell.startRest(x.dose.rest)};$('rounds').append(b)});lesson.setExercise(x,{exerciseSide:active?.side||x.side,contextId:'example-plan-1'});coach.setExercise({plan:{id:'example-plan-1',version:1},exercise:x,sessionId:session.id});document.querySelectorAll('[data-effort]').forEach(b=>{b.setAttribute('aria-pressed',String(p.feedback===b.dataset.effort));b.onclick=()=>{p.feedback=b.dataset.effort;render()}});$('exerciseHelp').textContent=x.instructions.join(' ');$('exerciseWhy').textContent=x.prescribedRange;$('playerSaveStatus').textContent='Exempel · inga uppgifter sparas';}
function leave(){lesson.pause();shell.closePanels();$('app').dataset.playerOpen='false';$('player').classList.add('hidden');home();window.scrollTo(0,0)}
function returnHome(){leave();$('todayCard').hidden=false;$('careNote').hidden=false;$('journeyFinish').hidden=true;$('demoReflection').hidden=true;tab('today');$('start').focus({preventScroll:true})}
function reflect(){leave();tab('today');$('todayCard').hidden=true;$('careNote').hidden=true;$('journeyFinish').hidden=true;$('demoReflection').hidden=false;$('demoReflection').querySelector('button').focus({preventScroll:true})}
$('start').onclick=()=>{preview.close();if(!session||finished){session=S.create(exercises,crypto.randomUUID(),new Date().toISOString());index=0;finished=false;reflection=null;log('Ett exempelpass påbörjades.');$('demoReflectionAnswer').hidden=true;$('doneReflection').hidden=true;document.querySelectorAll('[data-barrier]').forEach(b=>b.removeAttribute('aria-pressed'))}tab('today');$('journeyFinish').hidden=true;$('demoReflection').hidden=true;$('app').dataset.playerOpen='true';$('player').classList.remove('hidden');render();$('exName').focus({preventScroll:true});window.scrollTo(0,0)};
$('next').onclick=()=>{if($('next').disabled)return;lesson.pause();shell.endRest();shell.closePanels();log(current().name+': '+(session.progress[index].status==='skipped'?'överhoppad.':'registrerad.'));if(index<exercises.length-1){index++;$('guideResult').hidden=true;render();$('exName').focus({preventScroll:true});return}finished=true;session.completedAt=new Date().toISOString();leave();$('todayCard').hidden=true;$('careNote').hidden=true;$('journeyFinish').hidden=false;const done=session.progress.filter(p=>p.status==='completed').length;$('journeyFinish').querySelector('h2').textContent=done===exercises.length?'Passet är klart.':'Ditt pass är avslutat.';$('finishDetail').textContent=done+' av '+exercises.length+' övningar markerade som genomförda. Berätta gärna hur det fungerade.';log('Exempelpass avslutat. '+done+' av '+exercises.length+' övningar genomförda.');$('journeyFinish').querySelector('h2').focus({preventScroll:true});};
$('skip').onclick=()=>{shell.endRest();shell.closePanels();session.progress[index].status='skipped';render()};$('closePlayer').onclick=returnHome;$('returnToday').onclick=returnHome;$('showReflection').onclick=reflect;$('doneReflection').onclick=returnHome;$('followAction').onclick=()=>finished&&!reflection?reflect():returnHome();$('previewFirst').onclick=()=>preview.open(exercises[0],{contextId:'example-plan-1'});
for(const b of document.querySelectorAll('[data-tab]'))b.onclick=()=>{preview.close();if(b.dataset.tab==='today'){returnHome();return}tab(b.dataset.tab)};
for(const b of document.querySelectorAll('[data-barrier]'))b.onclick=()=>{reflection=b.dataset.barrier;document.querySelectorAll('[data-barrier]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('demoReflectionAnswer').hidden=false;$('doneReflection').hidden=false;$('demoReflectionAnswer').textContent=reflection==='none'?'I din egen plan sparas svaret som underlag för uppföljningen. I det här exemplet skickas inget.':reflection==='execution'?'Nästa steg är hjälp med den övning som var oklar. I din egen plan följer övning och planversion med till behandlaren när du ber om hjälp.':reflection==='symptoms'?'Förändrade besvär behöver bedömas av din behandlare. I det här exemplet skickas inget meddelande.':'I din egen plan kan uppföljningen hjälpa dig att hitta vad som fungerar i din vardag. Här provar du bara återkopplingen.';log('Återkoppling i exemplet: '+b.textContent+'.');home()};
home();renderLog();
