/* Reda 2.2 quick prescription console. All decisions remain clinician-controlled. */
(function(){'use strict';
const C=RedaCore,D=RedaData,M=RedaClinical,$=s=>document.querySelector(s),E=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={blueprint:'knee_pf',stage:'build',capacity:'standard',presentation:'standard',environment:'home',floor:true,band:true,goal:'',reviewDate:'',days:[1,3,5],note:''},plan=null;
const stageLoad={gentle:1,build:2,loaded:3};
function chooseVariant(ex){const wanted=stageLoad[state.stage],vs=ex.variants;let candidates=vs.filter(v=>!(v.tags?.band&&state.band===false)&&!(v.tags?.floor&&state.floor===false));if(!candidates.length)candidates=vs;const cap=state.capacity==='supported'?0:state.capacity==='high'?candidates.length-1:Math.min(1,candidates.length-1);let chosen=candidates[cap]||candidates[0];if(chosen.tags?.load){chosen=candidates.slice().sort((a,b)=>Math.abs((a.tags?.load||2)-wanted)-Math.abs((b.tags?.load||2)-wanted))[0];}return chosen;}
function scale(d){d=C.clone(d);if(state.stage==='gentle'){d.sets=Math.min(d.sets,2);d.reps=Math.min(d.reps,10);if(d.hold)d.hold=Math.min(d.hold,20);}if(state.stage==='loaded'){d.sets=Math.min(4,d.sets+1);d.reps=Math.min(20,d.reps+2);}return d;}
function build(){const bp=M.blueprints[state.blueprint];const p=C.template();p.title=bp.name;p.goal=state.goal.trim()||bp.goal;p.reviewDate=state.reviewDate;p.days=state.days.slice();p.message=M.presentation[state.presentation].intro+' Programmet är anpassat efter det vi gick igenom vid besöket.';p.safety='Följ den här nivån fram till uppföljningen. Ändra inte svårighetsgrad, belastning eller dos på egen hand. Vid osäkerhet, kontakta kliniken.';p.items=[];for(const id of bp.slots){const ex=D.exercises.find(e=>e.id===id);if(!ex)continue;const vr=chooseVariant(ex);if(vr.tags?.floor&&state.floor===false)continue;if(vr.tags?.band&&state.band===false)continue;const sides=C.allowedSides(ex.id,vr.id),side=sides.includes('both')?'both':sides[0];const item=C.makeItem(ex.id,vr.id,side);item.dose=scale(item.dose);item.note=state.note.trim();p.items.push(item);}if(!p.items.length)throw Error('Inga godkända övningar matchar valen. Öppna detaljredigering.');plan=C.validatePlan(p);return plan;}
function dateLabel(v){if(!v)return 'Inte satt';try{return new Intl.DateTimeFormat('sv-SE',{day:'numeric',month:'short'}).format(new Date(v+'T12:00:00'));}catch{return v;}}
function summary(){try{build();$('#status').textContent='Plan klar för granskning';$('#summary').innerHTML=`<div class="quick-summary-head"><div><span class="q-kicker">Färdigt förslag</span><h2>${E(plan.title)}</h2><p>${E(plan.goal)}</p></div><div class="q-metrics"><b>${plan.items.length}</b><span>övningar</span><b>${C.minutes(plan)}</b><span>min ca</span></div></div><div class="q-list">${plan.items.map((i,n)=>{const {e,v}=C.lookup(i.exercise,i.variant);return `<div class="q-ex"><span>${n+1}</span><div><strong>${E(e.name)}</strong><small>${E(v.name)} · ${E(C.doseLabel(i))}</small></div><button data-remove="${E(i.key)}" title="Ta bort">×</button></div>`}).join('')}</div><div class="q-review"><strong>Nästa kliniska steg</strong><p>${plan.reviewDate?'Återbesök '+E(dateLabel(plan.reviewDate))+'.':'Återbesök behöver planeras.'} Progression beslutas av behandlaren efter uppföljning.</p></div>`;}catch(e){$('#status').textContent=e.message;$('#summary').innerHTML='';}}
function render(){document.querySelectorAll('[data-choice]').forEach(b=>b.classList.toggle('active',state[b.dataset.choice]===b.dataset.value));document.querySelectorAll('[data-day]').forEach(b=>b.classList.toggle('active',state.days.includes(Number(b.dataset.day))));$('#goal').value=state.goal;$('#review').value=state.reviewDate;$('#note').value=state.note;$('#floor').checked=state.floor;$('#band').checked=state.band;summary();}
function parseDictation(){const t=$('#dictation').value.toLowerCase();const maps=[['knee_oa',/artros|knäartros/],['knee_tendon',/patellar|patellarsena|hopparknä/],['knee_pf',/patellofem|pfss|knä/],['shoulder_stiff',/frozen|stel axel|frusen/],['shoulder_load',/rotator|axel/],['hip_gtps',/gtps|trochanter|lateral höft|höft/],['achilles',/achilles|hälsena/],['elbow',/epikond|tennisarm|armbåge/],['neck',/nack/],['lumbar',/ländrygg|rygg/]];for(const [id,re] of maps)if(re.test(t)){state.blueprint=id;break;}if(/träningsvan|gymvan|idrott/.test(t))state.presentation='concise';if(/mycket guidning|ovan|otränad/.test(t))state.presentation='guided';if(/skonsam|irriterad|reaktiv|tidig/.test(t))state.stage='gentle';if(/hög belastning|sen fas|återgång|return to/.test(t))state.stage='loaded';if(/stöd|balanssvår/.test(t))state.capacity='supported';if(/hög kapacitet|stark/.test(t))state.capacity='high';if(/gym/.test(t))state.environment='gym';if(/ingen matta|inte golv|kan inte.*golv/.test(t))state.floor=false;if(/utan band|inget band/.test(t))state.band=false;const goal=t.match(/mål[: ]+([^.;]+)/);if(goal)state.goal=goal[1].trim();render();}
function share(){if(!plan)return;const url=new URL('index.html',location.href);url.hash='plan='+C.encodePlan(plan);navigator.clipboard?.writeText(url.href).then(()=>{$('#status').textContent='Testlänk kopierad. Ingen patientdata har skickats.';}).catch(()=>{$('#shareout').value=url.href;$('#shareout').hidden=false;});}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.choice){state[b.dataset.choice]=b.dataset.value;render();}if(b.dataset.day){const d=Number(b.dataset.day);state.days=state.days.includes(d)?state.days.filter(x=>x!==d):state.days.concat(d);if(!state.days.length)state.days=[d];render();}if(b.id==='parse')parseDictation();if(b.id==='share')share();if(b.dataset.remove&&plan){plan.items=plan.items.filter(i=>i.key!==b.dataset.remove);$('#summary').querySelector(`[data-remove="${CSS.escape(b.dataset.remove)}"]`)?.closest('.q-ex')?.remove();}});
['goal','review','note'].forEach(id=>$('#'+id).addEventListener('input',e=>{state[id==='review'?'reviewDate':id]=e.target.value;summary();}));['floor','band'].forEach(id=>$('#'+id).addEventListener('change',e=>{state[id]=e.target.checked;summary();}));render();
})();