/* Exercise Intelligence: shared, explainable presentation of the saved prescription.
 * No diagnosis, model call or patient-side prescription mutation.
 */
(function(root){'use strict';
const VERSION='1.0.0',goals={daily:'Vardag och funktion',strength:'Styrka och gym',run:'Löpning',sport:'Idrott',hyrox:'Hyrox'},capacity={supported:'Stöd och anpassat utförande',standard:'Grundutförande',high:'Hög praktisk kapacitet'},stages={protected:'Låg aktuell belastningstolerans',build:'Uppbyggnad',higher:'Högre belastning'},history={new:'Ny eller låg träningsvana',regular:'Van vid träning',rehab_experienced:'Har redan gjort grundrehab'},equipment={home:'Hemma',gym:'På gym',both:'Hemma och på gym'};
const weights=new Set(['leg_press','knee_extension_machine','cable_er','landmine_press','loaded_carry','standing_calf_loaded','seated_calf_loaded','lateral_step_down_loaded']);
function context(plan={}){const c=plan.context||{};return {goal:plan.goal||'',goalProfile:c.goalProfile||plan.goalProfile||'',capacity:c.capacity||'',stage:c.stage||'',history:c.trainingHistory||plan.trainingHistory||'',equipment:c.equipment||'',floorOK:c.floorOK,band:c.band}}
function overview(plan={}){const c=context(plan),axes=[['Mål',goals[c.goalProfile]],['Aktuell tolerans',stages[c.stage]],['Utförande',capacity[c.capacity]],['Träningsbakgrund',history[c.history]],['Miljö',equipment[c.equipment]]].filter(x=>x[1]).map(([label,value])=>({label,value}));
 const focus=c.stage==='protected'?'Den aktuella toleransen styr startnivån, även när du har stor träningsvana.':plan.intelligenceTier==='performance'?'Planen är vald med högre kapacitetskrav och ditt aktivitetsmål i åtanke.':plan.intelligenceTier==='advanced'?'Planen bygger vidare på den kapacitet och träningsbakgrund som angetts.':'Planen utgår från den nivå och det stöd som valts vid bedömningen.';
 return {version:VERSION,name:'Exercise Intelligence',goal:c.goal,axes,focus,contextKnown:axes.length>0,goalLabel:goals[c.goalProfile]||'Ditt individuella mål',constraints:[c.floorOK===false?'Övningar utan golvläge':null,c.band===false?'Övningar utan gummiband':null].filter(Boolean)};
}
function exercise(plan,x){const steps=(Array.isArray(x.instructions)?x.instructions:[]).filter(s=>typeof s==='string'&&s.trim());const equipmentText=x.equipment||'',support=x.support||'';return {why:x.why||x.prescription?.target||'',focus:x.focus||x.cue||'',steps:steps.length?steps:[x.instruction||x.cue].filter(Boolean),setup:[support,equipmentText].filter((s,i,a)=>s&&a.indexOf(s)===i),dose:x.dose?.label||'',side:{both:'Båda sidor, en i taget',left:'Vänster sida',right:'Höger sida',simultaneous:'Båda samtidigt'}[x.side]||'',rest:Number.isFinite(x.dose?.rest)?x.dose.rest:null,load:x.prescribedLoad||'',range:x.prescribedRange||'',source:x.editedByClinician?'Anpassad av behandlaren':'Från planförslaget',goal:plan.goal||''}}
function checks(plan={}){const items=[];for(const [index,x] of (plan.exercises||[]).entries()){
 if((weights.has(x.id)||x.id==='hip_thrust'&&x.variantId==='bilateral'||x.id==='rear_foot_split_squat'&&x.variantId==='loaded')&&!String(x.prescribedLoad||'').trim())items.push({index,code:'load',label:x.name,detail:'Ange individuell belastning eller intensitet. Bibliotekets exempel är inte en individuell ordination.'});
 if(!(x.instructions?.length||x.instruction))items.push({index,code:'instruction',label:x.name,detail:'Genomförandeinstruktion saknas i den sparade planen.'});
 }return items;
}
function clinicianHTML(plan,esc){const o=overview(plan),issues=checks(plan);return `<div class="ei-heading"><span class="ei-symbol" aria-hidden="true">↗</span><div><b>Exercise Intelligence</b><small>Utgångspunkt → övningsval → genomförande → återkoppling</small></div></div><p>${esc(o.focus)}</p><dl class="ei-axes">${o.axes.map(x=>`<div><dt>${esc(x.label)}</dt><dd>${esc(x.value)}</dd></div>`).join('')}</dl>${o.constraints.length?'<p>'+o.constraints.map(esc).join(' · ')+'</p>':''}${issues.length?`<div class="ei-checks"><b>Precisera innan planen delas</b>${issues.map(x=>`<p>${esc(x.label)}: ${esc(x.detail)}</p>`).join('')}</div>`:''}<p class="ei-footnote">Underlaget visar vad som är angivet i planen. Det ersätter inte din bedömning. Automatisk progression är fortsatt i testläge.</p>`}
root.RedaIntelligence={VERSION,goals,context,overview,exercise,checks,clinicianHTML};if(typeof module==='object'&&module.exports)module.exports=root.RedaIntelligence;
})(typeof window!=='undefined'?window:globalThis);
