import * as api from './secure-browser.mjs?v=20260911-runtime'
import {mountPlanHelp,decisionText} from './runtime-ui.mjs?v=1'
const $=id=>document.getElementById(id), F=window.RedaFigures, S=window.RedaSession, R=window.RedaRecovery
let helpExpanded=null,motionSlow=false,motionPlaying=false;
let state=null,plan=null,session=null,index=0,stopMotion=null, syncQueue=Promise.resolve(), unsynced=false, syncVersion=0, lastSynced=0, starting=false, recoveryBlocked=false, durable=false, previousSession=null
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function setAuth(show){$('auth').classList.toggle('hidden',!show);$('app').classList.toggle('hidden',show);$('logout').classList.toggle('hidden',show)}
function error(e){$('authSuccess').classList.add('hidden');$('authError').textContent=e?.message||String(e);$('authError').classList.remove('hidden')}
function exercises(){return plan?.payload?.exercises||[]}
const I=window.RedaIntelligence,TR=window.RedaTrainingResponse;
const responseForm=window.RedaResponseForm.create($('responseForm'),{submit:(sid,rid,answers)=>api.submitTrainingResponse(sid,rid,answers),onSaved:row=>{state.responses=[...(state.responses||[]).filter(x=>x.session_id!==row.session_id),row];renderResponsePrompt();evaluateNext()}});
function renderResponsePrompt(){const n=state.responseError?0:TR.due(state.sessions,state.responses).length;$('responsePrompt').classList.toggle('hidden',!n);$('responsePrompt').innerHTML=n?'<b>Hur svarade kroppen efter träningen?</b><br>Du kan lämna återkoppling på ett tidigare pass.<br><button type="button" class="btn ghost" id="openResponse">Svara på frågorna</button>':'';$('openResponse')?.addEventListener('click',()=>document.querySelector('[data-tab="follow"]').click())}
function renderIntelligence(){const o=I.overview(plan.payload);$('intelligenceContext').innerHTML='<p class="eyebrow">Din utgångspunkt</p><h3>'+esc(o.goalLabel)+'</h3><p>'+esc(o.contextKnown?o.focus:'Din behandlares sparade ordination visas nedan.')+'</p><details class="ei-plan-context"><summary>Vad planen tar hänsyn till</summary><dl class="ei-axes">'+o.axes.map(x=>'<div><dt>'+esc(x.label)+'</dt><dd>'+esc(x.value)+'</dd></div>').join('')+'</dl><p class="ei-footnote">Exercise Intelligence samlar förutsättningar, övningsval och återkoppling. Du följer alltid den aktuella ordinationen.</p></details>';responseForm.render(state);renderResponsePrompt()}
function pauseMotion(){stopMotion?.();stopMotion=null;motionPlaying=false;$('motionPlay').textContent=matchMedia('(prefers-reduced-motion: reduce)').matches?'Stilla visning':'Visa rörelsen'}
function motionFrame(t){pauseMotion();const x=exercises()[index];if(!x)return;$('motion').innerHTML=F.svg(motionKey(x),t,x.side||'simultaneous',x.name);document.querySelectorAll('[data-motion-frame]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.motionFrame)===t)))}
function playMotion(){if(motionPlaying){pauseMotion();return}const x=exercises()[index];if(!x)return;stopMotion=F.animate($('motion'),motionKey(x),{seconds:(x.dose?.tempo||5)*(motionSlow?2:1)});motionPlaying=true;$('motionPlay').textContent='Pausa rörelsen';document.querySelectorAll('[data-motion-frame]').forEach(b=>b.setAttribute('aria-pressed','false'))}
function renderExerciseHelp(x){const h=I.exercise(plan.payload,x),expanded=helpExpanded??plan.payload.presentation!=='trained';$('exerciseHelp').innerHTML='<button type="button" class="ei-help-toggle" id="helpToggle" aria-expanded="'+expanded+'">'+(expanded?'Visa kortare instruktion':'Visa steg för steg')+'</button>'+(expanded?'<p class="ei-setup">'+h.setup.map(esc).join(' · ')+'</p><ol class="ei-instructions">'+h.steps.map(s=>'<li>'+esc(s)+'</li>').join('')+'</ol>':'')+(h.rest!==null?'<p class="ei-setup">Ordinerad vila: '+h.rest+' sekunder mellan omgångarna.</p>':'');$('helpToggle').onclick=()=>{helpExpanded=!expanded;renderExerciseHelp(x)}}
function renderCare(){
 try{
  const c=window.RedaCare.overview(plan.payload),next=c.next;
  $('reviewText').textContent=next?`${next.label}: ${next.dateLabel} · ${next.contact}. Tid bekräftas separat. Din behandlare bedömer om planen ska ändras.`:c.unconfirmedPast?'De planerade datumen har passerat. Kontakta din behandlare för att bekräfta nästa avstämning.':'Ni kommer överens om nästa avstämning. Din behandlare bedömer nästa steg, på kliniken eller på distans.';
  $('careOverview').innerHTML=`<section class="care-overview"><p class="eyebrow">Ditt kontaktupplägg</p><h3>${esc(c.label)}${c.weeks?' · '+c.weeks+' veckor':''}</h3>${c.weeks?`<p>Planerad period: ${esc(window.RedaCare.displayDate(c.startDate))}–${esc(window.RedaCare.displayDate(c.endDate))}</p>`:''}<p>Här ser du kontakterna i din plan. Bokad tid och eventuell samtalslänk får du separat från Kansei.</p><ol class="care-timeline">${c.points.map((p,i)=>`<li><span class="care-num">${String(i+1).padStart(2,'0')}</span><div><strong>${esc(p.label)}</strong><small>${esc(p.dateLabel)} · ${esc(p.contact)}</small>${p.passed?'<small class="past-contact">Datum passerat · genomförande bekräftas med behandlaren</small>':''}</div></li>`).join('')||'<li><div><strong>Vi planerar nästa kontakt tillsammans.</strong><small>Inget datum är angivet i din plan ännu.</small></div></li>'}</ol><div class="care-preparation"><h4>Inför avstämningen</h4><p>Fundera på vilka övningar som fungerat, vad som varit svårt och hur det går med ditt mål. Dina registreringar är ett underlag när ni följer upp tillsammans.</p></div><p>En avstämning eller avslutad period ändrar inte träningsnivån automatiskt. Nästa steg beslutas med din behandlare.</p><a href="/kontakt/">Kontakta Kansei ↗</a></section>`;
 }catch{$('reviewText').textContent='Kontakta din behandlare för att bekräfta nästa uppföljning.';$('careOverview').innerHTML='<p class="muted">Kontaktplaneringen kunde inte visas. Kontakta Kansei för datum och kontaktform.</p>'}
}

function doseLabel(x){return x?.dose?.label||[x?.dose?.sets&&`${x.dose.sets} omgångar`,x?.dose?.reps&&`${x.dose.reps} repetitioner`].filter(Boolean).join(' · ')||'Följ ordinationen'}
function sets(x){return S.rounds(x).length}
function instruction(x){return x?.instruction||x?.instructions?.[0]||x?.steps?.[0]||x?.cue||'Följ rörelsen lugnt och kontrollerat enligt din ordination.'}
function motionKey(x){return x?.motionKey||x?.motion?.key||x?.figure||x?.variantId||x?.id}
function prescription(x){const p=x?.prescription;if(!p)return'';return `<div class="prescription-grid"><div><span>Tränar</span><b>${esc(p.target)}</b></div><div><span>Rörelse</span><b>${esc(p.rom)}</b></div><div><span>Tempo</span><b>${esc(p.tempo)}</b></div><div><span>Belastning</span><b>${esc(x.prescribedLoad||p.load)}</b></div></div><div class="measure-line"><span>Det vi kan följa</span><b>${esc(p.measure)}</b></div>`}
function whyBlock(x){const why=x?.why||'',focus=x?.focus||'',level=x?.challenge||'';if(!why&&!focus&&!level&&!x?.prescription)return'';return `<div class="exercise-context">${level?`<span class="level-pill">${esc(level)}</span>`:''}${why?`<div><b>Varför den här är med</b><p>${esc(why)}</p></div>`:''}${prescription(x)}${focus?`<div><b>Ditt fokus</b><p>${esc(focus)}</p></div>`:''}</div>`}
function renderHome(){const xs=exercises();$('patientName').textContent=state.patient.display_name;$('version').textContent=plan.version;$('exerciseCount').textContent=xs.length;$('todayMeta').textContent=`Aktuell plan · ${plan.payload?.schedule?.days?.length||''} planerade pass/vecka`;$('intro').textContent=plan.payload?.goal?`Målet med den här perioden: ${plan.payload.goal}`:'Det här är den plan du och din behandlare har gått igenom.';renderCare();renderIntelligence();const helpPlan=plan;mountPlanHelp($('planHelp'),{api,plan,isCurrent:()=>plan===helpPlan,onResponse:()=>document.querySelector('[data-tab=follow]').click()});$('programList').innerHTML=xs.map((x,i)=>`<div class="exercise program-exercise"><div class="exercise-topline"><span>${String(i+1).padStart(2,'0')}</span><span>${esc(x.challenge||'Individuell nivå')}</span></div><h3>${esc(x.name)}</h3><div class="sub">${esc(x.variantLabel||'')} · ${esc(doseLabel(x))}</div>${whyBlock(x)}</div>`).join('');renderHistory()}
function renderHistory(){const rows=state.sessions||[];$('history').innerHTML=rows.length?rows.map(s=>`<div class="exercise"><b>${s.status==='completed'?'Genomfört':s.status==='partial'?'Delvis genomfört':s.status==='started'?'Påbörjat':'Planerad vila'}</b><div class="sub">${new Date(s.started_at).toLocaleDateString('sv-SE')} · plan v${s.plan_version}</div></div>`).join(''):'<p class="muted">Ingen träningshistorik ännu.</p>'}
async function bootstrap(){
 state=await api.patientBootstrap();plan=state.plan;
 const restored=R.choose(plan,state.sessions,R.read(localStore(),state.userId));
 if(restored.discard)R.clear(localStore(),state.userId);
 recoveryBlocked=!!restored.blocked;previousSession=restored.previous||null;$('closePrevious').classList.toggle('hidden',!previousSession);session=restored.session||null;index=restored.index||0;
 renderHome();setAuth(false);$('start').disabled=recoveryBlocked;
 $('start').textContent=session&&!session.completedAt?'Fortsätt påbörjat pass':'Starta passet';
 $('sync').textContent=restored.message||(session?'Ditt påbörjade pass är återställt.':'Synkad med kliniken');
 if(restored.retry)await sync(session.status,session.completedAt);
} 
function localStore(){try{return window.localStorage}catch{return null}}
function persist(){if(session&&state?.userId)durable=R.write(localStore(),state.userId,plan,session,index)}
function progressPayload(){return {exercises:session.progress.map(p=>({exerciseId:p.exerciseId,status:p.status,roundsDone:p.roundsDone,feedback:p.feedback})),clientUpdatedAt:new Date().toISOString()}}
async function sync(status,completedAt=null){session.status=status;session.completedAt=completedAt;const data={clientSessionId:session.id,status,startedAt:session.startedAt,completedAt,payload:progressPayload()},planId=plan.id, version=++syncVersion;unsynced=true;persist();$('sync').textContent=durable?'Sparat på enheten · synkar med kliniken…':'Sparar passet…';syncQueue=syncQueue.then(async()=>{try{await api.saveSession(planId,data);lastSynced=version;unsynced=lastSynced<syncVersion;if(!unsynced)R.clear(localStore(),state.userId);$('retrySync').classList.add('hidden');$('sync').textContent=unsynced?'Sparar passet…':'Synkad med kliniken';return true}catch(e){unsynced=true;$('retrySync').classList.remove('hidden');$('sync').textContent=durable?'Sparat på den här enheten. Synkas när anslutningen fungerar.':'Passet är inte sparat. Behåll sidan öppen och försök igen.';return false}});return syncQueue}
async function start(){const xs=exercises();if(!xs.length||starting||recoveryBlocked)return;starting=true;$('start').disabled=true;try{if(session?.completedAt&&unsynced){$('sync').textContent='Synka det avslutade passet innan du börjar ett nytt.';return}if(!session||session.completedAt){await evaluateNext();session=S.create(exercises(),crypto.randomUUID(),new Date().toISOString());index=0;await sync('started')} $('start').textContent='Fortsätt passet';$('player').classList.remove('hidden');showExercise()}finally{starting=false;$('start').disabled=recoveryBlocked}}
function showExercise(){pauseMotion();const x=exercises()[index],p=session.progress[index];$('pos').textContent=`${index+1} av ${exercises().length}`;$('exName').textContent=x.name;$('dose').textContent=doseLabel(x)+(x.side==='both'?' per sida':x.side==='left'?' · vänster':x.side==='right'?' · höger':'')+(x.prescribedLoad?' · '+x.prescribedLoad:'');$('instruction').textContent=instruction(x);$('exerciseWhy').innerHTML=whyBlock(x);renderExerciseHelp(x);$('rounds').innerHTML=S.rounds(x).map((r,i)=>`<button class="btn ${i<p.roundsDone?'primary':'soft'} round" data-round="${i}" ${i!==p.roundsDone?'disabled':''}>${i<p.roundsDone?'✓ ':''}Omgång ${r.set}${r.side==='left'?' · vänster':r.side==='right'?' · höger':''}</button>`).join('');document.querySelectorAll('[data-effort]').forEach(b=>{b.setAttribute('aria-pressed',String(b.dataset.effort===p.feedback));b.onclick=async()=>{if(session.completedAt)return;p.feedback=b.dataset.effort;showExercise();await sync('partial')}});const key=motionKey(x);$('motion').innerHTML=F?.svg?F.svg(key,0,x.side||'simultaneous',x.name):'↕';document.querySelectorAll('[data-motion-frame]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.motionFrame==='0')));document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>markRound(Number(b.dataset.round)));$('next').disabled=p.roundsDone<sets(x)&&p.status!=='skipped';$('next').textContent=index===exercises().length-1?'Avsluta pass':'Nästa övning'}
async function markRound(i){if(session?.completedAt)return;session=S.mark(session,index,i);showExercise();await sync('partial')}
async function skip(){if(session?.completedAt)return;const p=session.progress[index];p.status='skipped';showExercise();await sync('partial')}
async function next(){if(session?.completedAt)return;if(index<exercises().length-1){index++;showExercise();if(unsynced)persist();return}$('next').disabled=true;const all=session.progress.every(p=>p.status==='completed'),doneAt=new Date().toISOString();const saved=await sync(all?'completed':'partial',doneAt);stopMotion?.();$('player').classList.add('hidden');$('start').textContent='Starta nytt pass';if(saved){try{state=await api.patientBootstrap();plan=state.plan;renderHome();$('sync').textContent=all?'Passet är sparat och synkat':'Passet är sparat som delvis genomfört'}catch(e){$('sync').textContent='Passet är sparat, men historiken kunde inte uppdateras.'}}}
async function pause(){if(!session||session.completedAt)return;$('player').classList.add('hidden');stopMotion?.();await sync(session.progress.some(p=>p.roundsDone||p.status==='skipped')?'partial':'started')}
$('magicLink').onclick=async()=>{try{const email=$('email').value.trim();if(!email)throw new Error('Ange din e-postadress');$('magicLink').disabled=true;$('authError').classList.add('hidden');await api.sendPatientMagicLink(email);$('authSuccess').textContent='Klart. Öppna mejlet från Reda och tryck på länken för att öppna ditt program.';$('authSuccess').classList.remove('hidden')}catch(e){error(e)}finally{$('magicLink').disabled=false}}
$('logout').onclick=async()=>{if(responseForm.isBusy()){$('sync').textContent='Vänta tills återkopplingen har sparats eller ett felmeddelande visas.';return}if(unsynced){$('sync').textContent='Synka passet innan du loggar ut.';return}R.clear(localStore(),state?.userId);await api.signOut();location.reload()};$('start').onclick=start;$('skip').onclick=skip;$('next').onclick=next;$('closePlayer').onclick=pause
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{if(b.dataset.tab!=='today')pauseMotion();document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.tab))})
setAuth(true);api.currentUser().catch(e=>{if(e?.name==='AuthSessionMissingError')return null;throw e}).then(async u=>{if(u)await bootstrap()}).catch(error)
async function retry(){if(!session)return;const finished=!!session.completedAt;if(await sync(session.status,session.completedAt)){if(finished){try{await bootstrap()}catch{$('sync').textContent='Passet är sparat. Ladda om sidan för att uppdatera planen.'}}}}
$('retrySync').onclick=retry;window.addEventListener('beforeunload',e=>{if(unsynced&&!durable){e.preventDefault();e.returnValue=''}});

window.addEventListener('online',()=>{if(unsynced&&session)retry()});

$('closePrevious').onclick=async()=>{
 if(!previousSession)return;
 $('closePrevious').disabled=true;
 try{const {planId,...old}=previousSession,items=old.payload?.exercises||[];
  await api.saveSession(planId,{...old,status:items.length&&items.every(p=>p.status==='completed')?'completed':'partial',completedAt:new Date().toISOString()});
  R.clear(localStore(),state.userId);await bootstrap();
 }catch(e){$('sync').textContent='Det föregående passet kunde inte sparas. Dina markeringar är kvar; försök igen när du har anslutning.'}
 finally{$('closePrevious').disabled=false}
};

$('motionPlay').onclick=playMotion;$('motionSlow').onclick=()=>{motionSlow=!motionSlow;$('motionSlow').setAttribute('aria-pressed',String(motionSlow));if(motionPlaying){pauseMotion();playMotion()}};document.querySelectorAll('[data-motion-frame]').forEach(b=>b.onclick=()=>motionFrame(Number(b.dataset.motionFrame)));document.addEventListener('visibilitychange',()=>{if(document.hidden)pauseMotion()});

if(matchMedia('(prefers-reduced-motion: reduce)').matches){$('motionPlay').disabled=true;$('motionSlow').disabled=true;$('motionPlay').textContent='Stilla visning';}

let evaluating=false,pendingEvaluation=null,evaluationTask=null;
function evaluateNext(){if(evaluationTask)return evaluationTask;evaluationTask=runEvaluation().finally(()=>{evaluationTask=null});return evaluationTask}
async function runEvaluation(){
 if(!api.evaluateProgression||!state||evaluating||unsynced||recoveryBlocked||(session&&!session.completedAt))return;
 evaluating=true;const patientId=state.patient.id;pendingEvaluation=pendingEvaluation||crypto.randomUUID();
 try{const d=await api.evaluateProgression(patientId,pendingEvaluation);pendingEvaluation=null;if(state.patient.id!==patientId)return;
  if(d.applied&&d.result_plan_id){session=null;await bootstrap()}
  $('engineDecision').hidden=d.code==='no_frame';$('engineDecisionText').textContent=decisionText(d);
 }catch{$('engineDecision').hidden=false;$('engineDecisionText').textContent='Nästa steg kunde inte kontrolleras. Din aktuella ordination visas fortfarande. Försök igen när anslutningen fungerar.'}
 finally{evaluating=false}
}
$('checkNextStep').onclick=evaluateNext;
