import {parsePatientFile,mappedPatient,importFields} from './patient-import.mjs?v=1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const sources={manual:'Manuellt registrerad',bokadirekt:'Bokadirekt',easypractice:'EasyPractice',other:'Annat system'};
export function openPatientIntake({api,patientId=null,onBusy,onSaved,onOpen}){
 const dialog=document.createElement('dialog'),previous=document.activeElement;let alive=true,saving=false,ticket=0,revision=0,pending=null,duplicates=null,file=null;
 dialog.className='patient-intake';dialog.setAttribute('aria-labelledby','intakeTitle');
 dialog.innerHTML=`<div class="intake-top"><div><p class="eyebrow">${patientId?'Patientuppgifter':'Patientstart'}</p><h2 id="intakeTitle">${patientId?'Det viktigaste om patienten':'Rätt patient. En tydlig start.'}</h2></div><button class="btn ghost" data-close aria-label="Stäng patientstart">Stäng</button></div>
 ${patientId?'':`<nav class="intake-tabs" aria-label="Lägg till patient"><button data-mode="manual" aria-pressed="true">Ny patient</button><button data-mode="find" aria-pressed="false">Sök i Reda</button><button data-mode="file" aria-pressed="false">Hämta från fil</button></nav>`}
 <p data-message role="status" aria-live="polite"></p>
 <section data-panel="find" hidden><label>Sök bland dina patienter<input data-find type="search" placeholder="Namn, e-post, telefon eller kund-ID" autocomplete="off" maxlength="100"></label><div data-found></div></section>
 <section data-panel="file" hidden><h3>Välj en person ur en export</h3><p>Öppna en CSV-fil från ditt boknings- eller journalsystem. Granska kolumnerna och välj den patient du vill ta in.</p><label>Källsystem<select data-file-source><option value="bokadirekt">Bokadirekt</option><option value="easypractice">EasyPractice</option><option value="other">Annat system</option></select></label><label>CSV-fil, UTF-8 · högst 2 MB<input data-file type="file" accept=".csv,.tsv,text/csv,text/tab-separated-values"></label><p class="intake-hint">Filimport är en engångsöverföring. En löpande koppling till Bokadirekt eller journalen är ännu inte ansluten.</p><div data-mapping></div><div data-file-people></div></section>
 <form data-panel="manual"><div class="intake-fields"><label class="intake-wide">Fullständigt namn <span class="intake-required">Obligatoriskt</span><input name="name" required minlength="2" maxlength="120" autocomplete="off" placeholder="För- och efternamn"></label><label>E-post<input name="email" type="email" maxlength="254" autocomplete="off" placeholder="namn@exempel.se"></label><label>Telefon<input name="phone" type="tel" maxlength="40" autocomplete="off" placeholder="070 123 45 67"></label></div>
 <div class="intake-section"><h3>Vad vill vi hjälpa personen med?</h3><div class="intake-fields"><label class="intake-wide">Behandlingsfokus<input name="focus" maxlength="120" placeholder="Exempel: vänster knä, besvär i trappor"></label><label class="intake-wide">Patientens mål<input name="goal" maxlength="240" placeholder="Exempel: kunna gå i trappor utan att hålla i räcket"></label><label class="intake-wide">Att känna till inför nästa kontakt<textarea name="handover" maxlength="240" rows="2" placeholder="En kort, relevant notering som ska synas direkt i överblicken."></textarea></label><label>Planerad kontakt<input name="next_contact" type="date"></label><p class="intake-hint">Datumet visas i din arbetslista. Det skapar ingen bokning.</p></div></div>
 <details data-origin><summary>Källa och referens</summary><div class="intake-fields"><label>Källsystem<select name="source">${Object.entries(sources).map(([v,l])=>`<option value="${v}">${l}</option>`).join('')}</select></label><label>Kund-ID i källsystemet<input name="external_id" maxlength="100" placeholder="Valfritt externt ID"></label></div><p class="intake-hint">Källan visar var uppgifterna hämtats. Den innebär ingen aktiv synkronisering.</p></details>
 <p class="intake-hint">Kontaktuppgifter och mål kan kompletteras senare. Ingen patientinbjudan skickas när du sparar.</p><div data-duplicates></div><div class="intake-footer"><button type="button" class="btn ghost" data-cancel>Avbryt</button><button class="btn primary" type="submit" data-save>${patientId?'Spara patientuppgifter':'Skapa patient & förbered plan'}</button></div></form>`;
 document.body.append(dialog);const q=s=>dialog.querySelector(s),form=q('form'),message=(s,error=false)=>{if(!alive)return;q('[data-message]').textContent=s;q('[data-message]').setAttribute('role',error?'alert':'status')};
 const values=()=>Object.fromEntries(new FormData(form));
 const fill=p=>{for(const el of form.elements)if(el.name)el.value=p[el.name]??(el.name==='source'?'manual':'')};
 function close(){if(saving)return;alive=false;++ticket;file=null;dialog.close();dialog.remove();onBusy?.(false);previous?.focus()}
 function mode(value){++ticket;dialog.querySelectorAll('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==value);dialog.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===value)));message('');if(value==='find')q('[data-find]').focus();else if(value==='manual')form.elements.name.focus()}
 function chosen(row){close();onOpen?.(row)}
 dialog.addEventListener('cancel',e=>{e.preventDefault();close()});q('[data-close]').onclick=close;q('[data-cancel]').onclick=close;
 dialog.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>mode(b.dataset.mode));
 let searchTimer;
 q('[data-find]').oninput=()=>{clearTimeout(searchTimer);const query=q('[data-find]').value.trim(),t=++ticket;q('[data-found]').replaceChildren();if(query.length<2)return;searchTimer=setTimeout(async()=>{if(!alive||t!==ticket)return;message('Söker…');try{const result=await api.dashboard(query,'all',0);if(!alive||t!==ticket)return;message(result.total?`${result.total} träffar. Visar högst 25.`:'Ingen träff. Du kan lägga till en ny patient.');q('[data-found]').innerHTML=result.patients.map(p=>`<button class="intake-person" data-existing="${esc(p.patient_id)}"><b>${esc(p.display_name)}</b><span>${esc(p.care_focus||'Fokus saknas')} · ${p.patient_status==='archived'?'Arkiverad':p.plan_id?'Aktiv plan':'Ingen aktiv plan'}</span><small>Öppna befintlig patient →</small></button>`).join('');q('[data-found]').querySelectorAll('button').forEach(b=>b.onclick=()=>chosen(result.patients.find(p=>p.patient_id===b.dataset.existing)))}catch(e){if(alive&&t===ticket)message(e.message,true)}},250)};
 function filePeople(){if(!file)return;const search=(q('[data-file-search]')?.value||'').toLocaleLowerCase('sv-SE');const selected=[];let total=0;file.rows.forEach((row,i)=>{const p=mappedPatient(row,file.mapping);if([p.name,p.email,p.phone,p.external_id].join(' ').toLocaleLowerCase('sv-SE').includes(search)){total++;if(selected.length<25)selected.push({p,i})}});q('[data-file-people]').innerHTML=`<p>${total} träffar i filen. Visar högst 25.</p>`+selected.map(({p,i})=>`<button class="intake-person" data-file-row="${i}" ${!p.name?'disabled':''}><b>${esc(p.name||'Namn saknas. Kontrollera kolumnvalet.')}</b><span>${esc([p.email,p.phone,p.external_id].filter(Boolean).join(' · '))}</span><small>Granska denna patient →</small></button>`).join('');q('[data-file-people]').querySelectorAll('[data-file-row]').forEach(b=>b.onclick=()=>{fill({...mappedPatient(file.rows[Number(b.dataset.fileRow)],file.mapping),source:q('[data-file-source]').value});mode('manual');q('[data-origin]').open=true;duplicates=null;q('[data-duplicates]').replaceChildren();message('Uppgifterna är hämtade från filen. Granska och komplettera innan du sparar.')})}
 q('[data-file]').onchange=async()=>{const f=q('[data-file]').files?.[0],t=++ticket;file=null;q('[data-mapping]').replaceChildren();q('[data-file-people]').replaceChildren();if(!f)return;try{if(f.size>2_000_000)throw Error('Välj en fil på högst 2 MB.');const content=await f.text();if(!alive||t!==ticket)return;file=parsePatientFile(content);q('[data-mapping]').innerHTML=`<details open><summary>Kontrollera kolumnerna · ${file.rows.length} personer i filen</summary><div class="intake-fields">${Object.entries(importFields).map(([key,label])=>`<label>${label}<select data-map="${key}"><option value="-1">Hämta inte</option>${file.headers.map((h,i)=>`<option value="${i}" ${file.mapping[key]===i?'selected':''}>${esc(h||'Kolumn '+(i+1))}</option>`).join('')}</select></label>`).join('')}</div></details><label>Sök personen i filen<input data-file-search type="search" placeholder="Namn, e-post, telefon eller kund-ID" autocomplete="off"></label>`;q('[data-mapping]').querySelectorAll('[data-map]').forEach(el=>el.onchange=()=>{file.mapping[el.dataset.map]=Number(el.value);filePeople()});q('[data-file-search]').oninput=filePeople;filePeople();message('Bara uppgifterna för den person du väljer sparas i Reda.')}catch(e){message(e.message,true)}};
 function drawDuplicates(result){duplicates=result;q('[data-duplicates]').innerHTML=`<div class="intake-duplicate"><h3>Kontrollera om patienten redan finns</h3><p>Namn, kontaktuppgifter eller kund-ID matchar en befintlig patient. Ingen ny patient har skapats.</p>${result.matches.map((p,i)=>`<button type="button" class="intake-person" data-match="${i}"><b>${esc(p.display_name)}</b><span>${esc([p.email,p.phone].filter(Boolean).join(' · '))}</span><small>${p.exact_source?'Samma kund-ID i källsystemet. ':''}Öppna befintlig patient →</small></button>`).join('')}${result.matches.some(p=>p.exact_source)?'<p>Detta kund-ID finns redan. Öppna den befintliga patienten eller rätta uppgifterna.</p>':'<label class="intake-check"><input type="checkbox" data-distinct>Jag har kontrollerat träffarna. Detta är en annan person.</label>'}</div>`;q('[data-duplicates]').querySelectorAll('[data-match]').forEach(b=>b.onclick=()=>chosen(result.matches[Number(b.dataset.match)]));q('[data-duplicates]').scrollIntoView({block:'nearest'})}
 form.addEventListener('input',()=>{if(saving)return;if(duplicates){duplicates=null;q('[data-duplicates]').replaceChildren()}pending=null});
 // A deliberate duplicate confirmation is not a patient-field change.
 q('[data-duplicates]').addEventListener('input',e=>e.stopPropagation());
 form.onsubmit=async e=>{e.preventDefault();if(saving||!form.reportValidity())return;const input={patientId,profile:values(),revision,duplicateToken:q('[data-distinct]')?.checked?duplicates?.duplicate_token:null};
  const signature=JSON.stringify(input);if(pending?.signature!==signature)pending={signature,requestId:crypto.randomUUID()};saving=true;dialog.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);message('Sparar patientuppgifterna…');
  try{if(!api.savePatientProfile)throw Error('Patientstarten kunde inte laddas. Uppdatera sidan och försök igen.');const result=await api.savePatientProfile({...input,requestId:pending.requestId});if(!alive)return;if(result.status==='duplicates'){pending=null;drawDuplicates(result);message('Granska träffarna innan du går vidare.',true)}else{saving=false;close();await onSaved?.(result);return}}
  catch(e){if(alive){message(e.message,true);if(e.code==='40001'){q('[data-save]').dataset.stale='true';message(e.message+' Dina ändringar finns kvar här för jämförelse.',true)}}}
  finally{saving=false;if(alive){dialog.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=false);q('[data-save]').disabled=q('[data-save]').dataset.stale==='true'}}
 };
 dialog.showModal();onBusy?.(true);
 if(patientId){form.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);message('Hämtar patientuppgifterna…');api.patientProfile(patientId).then(p=>{if(!alive)return;revision=p.revision;fill(p);message('');form.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=false)}).catch(e=>message(e.message,true)).finally(()=>{saving=false})}else form.elements.name.focus();
 return {close};
}
