const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={person:'<circle cx="12" cy="8" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',gear:'<path d="m9 3-1 3-3 1v3l-2 2 2 2v3l3 1 1 3h6l1-3 3-1v-3l2-2-2-2V7l-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',card:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h3"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3M12 17h.01"/>',exit:'<path d="M9 4H4v16h5M10 12h11m-4-4 4 4-4 4"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',chevron:'<path d="m8 10 4 4 4-4"/>'};
const glyph=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]||''}</svg>`;
const sections=[['general','Allmänt','gear'],['profile','Min profil','person'],['billing','Köp & abonnemang','card'],['data','Mina uppgifter','shield'],['help','Hjälp & kontakt','help']];
export function createPatientAccount({header,logout=null,preview=false,onPlan=()=>{},onHistory=()=>{},onHelp=null,kind='clinic'}={}){
 let account={name:'Mitt konto',email:'',signedIn:false,kind},current='general';
 const actions=document.createElement('div');actions.className='patient-top-actions';actions.innerHTML=`<button class="account-gear" type="button" aria-label="Inställningar" aria-haspopup="dialog">${glyph('gear')}</button><button class="account-trigger" type="button" aria-label="Öppna kontomenyn" aria-haspopup="dialog" aria-expanded="false"><span class="account-avatar">${glyph('person')}</span>${glyph('chevron')}</button>`;header.append(actions);
 const menu=document.createElement('dialog');menu.className='account-menu';menu.setAttribute('aria-label','Kontomeny');menu.innerHTML=`<div class="account-menu-identity"><span class="account-avatar">${glyph('person')}</span><div><b data-account-name>Mitt konto</b><span data-account-kind></span></div></div><button type="button" data-settings="profile">${glyph('person')}Min profil</button><button type="button" data-settings="general">${glyph('gear')}Inställningar</button><button type="button" data-settings="billing">${glyph('card')}Köp & abonnemang</button><button type="button" data-settings="data">${glyph('shield')}Mina uppgifter</button><button type="button" data-settings="help">${glyph('help')}Hjälp & kontakt</button><div class="account-menu-end"></div>`;document.body.append(menu);if(logout){logout.classList.add('account-logout');logout.innerHTML=glyph('exit')+'Logga ut';menu.querySelector('.account-menu-end').append(logout);logout.addEventListener('click',()=>menu.close())}else menu.querySelector('.account-menu-end').remove();
 const settings=document.createElement('dialog');settings.className='patient-settings';settings.setAttribute('aria-labelledby','patientSettingsTitle');settings.innerHTML=`<header class="settings-header"><div><span class="settings-eyebrow">Reda · ditt konto</span><h2 id="patientSettingsTitle">Inställningar</h2></div><button class="settings-close" type="button" aria-label="Stäng inställningar">${glyph('close')}</button></header><div class="settings-layout"><nav class="settings-nav" aria-label="Inställningskategorier">${sections.map(([id,label,icon])=>`<button type="button" data-section="${id}">${glyph(icon)}<span>${label}</span></button>`).join('')}</nav><label class="settings-category"><span>Visa inställningar för</span><select aria-label="Inställningskategori">${sections.map(([id,label])=>`<option value="${id}">${label}</option>`).join('')}</select></label><div class="settings-content"><section id="settingsPanel" aria-labelledby="settingsSectionTitle"></section></div></div>`;document.body.append(settings);
 const panel=settings.querySelector('#settingsPanel'),trigger=actions.querySelector('.account-trigger'),gear=actions.querySelector('.account-gear');let returnTo=gear;
 function closeOutside(dialog,e){if(e.target!==dialog)return;const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close()}
 menu.addEventListener('click',e=>closeOutside(menu,e));settings.addEventListener('click',e=>closeOutside(settings,e));menu.addEventListener('close',()=>trigger.setAttribute('aria-expanded','false'));settings.addEventListener('close',()=>returnTo?.focus({preventScroll:true}));
 trigger.onclick=()=>{trigger.setAttribute('aria-expanded','true');menu.showModal()};gear.onclick=()=>open('general',gear);settings.querySelector('.settings-close').onclick=()=>settings.close();
 menu.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>{menu.close();open(b.dataset.settings,trigger)});settings.querySelectorAll('[data-section]').forEach(b=>b.onclick=()=>{current=b.dataset.section;render()});settings.querySelector('.settings-category select').onchange=e=>{current=e.target.value;render();settings.querySelector('.settings-content').scrollTop=0};
 function choice(key,value,label,extra=''){const active=window.RedaPreferences.get()[key]===value;return `<button type="button" data-pref="${key}" data-value="${value}" aria-pressed="${active}" ${extra}>${label}</button>`}
 function render(){
  settings.querySelector('.settings-category select').value=current;
  settings.querySelectorAll('[data-section]').forEach(b=>{if(b.dataset.section===current)b.setAttribute('aria-current','page');else b.removeAttribute('aria-current')});
  const title=sections.find(s=>s[0]===current)?.[1]||'Allmänt';let content='';
  if(current==='general')content=`<div class="settings-group"><h4>Utseende</h4><p>Välj det som känns bäst för dina ögon.</p><div class="theme-choices" role="group" aria-label="Tema">${[['dark','Mörkt'],['light','Ljust'],['system','Följ enheten']].map(([v,l])=>choice('theme',v,`<span class="theme-swatch theme-${v}" aria-hidden="true"><i></i><b></b><em></em></span><span>${l}</span>`)).join('')}</div></div><div class="settings-group"><h4>Textstorlek</h4><div class="settings-segments" role="group" aria-label="Textstorlek">${choice('text','standard','Standard')}${choice('text','large','Större text')}</div></div><div class="settings-group"><h4>Övningsvisning</h4><div class="settings-segments" role="group" aria-label="Övningsvisning">${choice('motion','system','Följ enheten')}${choice('motion','still','Stillbilder')}</div><p>Med stillbilder väljer du själv startläge, rörelsens mitt eller slutläge under Instruktion.</p></div><p class="settings-note" data-preference-status role="status">Dina val sparas i den här webbläsaren.</p>`;
  if(current==='profile')content=`<div class="settings-profile"><span class="account-avatar">${glyph('person')}</span><div><b>${esc(account.name)}</b><span>${preview?'Visningsexempel':account.signedIn?(account.kind==='clinic'?'Plan via klinik':'Eget Reda-konto'):'Inte inloggad'}</span></div></div><dl class="settings-facts"><div><dt>Namn</dt><dd>${esc(account.signedIn||preview?account.name:'Visas när du loggar in')}</dd></div>${account.email?`<div><dt>E-post för inloggning</dt><dd>${esc(account.email)}</dd></div>`:''}<div><dt>Inloggning</dt><dd>${preview?'Du provar utan konto':'Säker länk till din e-post'}</dd></div></dl><p>${account.kind==='clinic'?'Behöver dina kontaktuppgifter rättas? Kontakta kliniken som gav dig planen.':'Kontakta Reda om du behöver hjälp med ditt konto.'}</p><button class="settings-action" type="button" data-contact>Hjälp med mitt konto</button>`;
  if(current==='billing')content=`<div class="settings-empty">${glyph('card')}<h4>Köp och abonnemang</h4><p>Betalningar är ännu inte anslutna i Reda.</p><p>När du köper direkt i Reda samlas ditt abonnemang och dina kvitton här. Betalningar till din klinik hanteras separat.</p></div><button type="button" class="settings-action" data-contact>Fråga om en betalning</button>`;
  if(current==='data')content=`<div class="settings-group"><h4>Din plan och din träning</h4><p>Öppna din aktuella plan eller se det som registrerats i historiken.</p><div class="settings-links"><button type="button" data-open-plan>Öppna min plan <span aria-hidden="true">›</span></button><button type="button" data-open-history>Öppna min historik <span aria-hidden="true">›</span></button></div></div><div class="settings-group"><h4>Uppgifter och integritet</h4><p>Vill du få en kopia av dina uppgifter, rätta något eller få hjälp att avsluta ditt konto? Kontakta ${account.kind==='clinic'?'din klinik':'Reda'} så att din begäran kan hanteras.</p><button type="button" class="settings-action" data-contact>Kontakta oss om mina uppgifter</button></div><p class="settings-note">Temaval och läsinställningar sparas på den här enheten.</p>`;
  if(current==='help')content=`<div class="settings-group"><h4>Hjälp i ditt pass</h4><p>Tryck på Hjälp i övningen om något känns oklart. Då följer rätt övning och ordination med.</p><details><summary>Hur ser jag rörelsen?</summary><p>Öppna en övning och tryck på Visa. Visningen stannar efter ett varv. Under Instruktion kan du läsa i din takt, se en del eller välja en stillbild.</p></details><details><summary>Hur sparas träningen?</summary><p>Markera en omgång när du har gjort den. Du ser sparstatus under passet. Om synkningen misslyckas kan du försöka igen när anslutningen fungerar.</p></details><details><summary>Hur ändras min plan?</summary><p>${account.kind==='clinic'?'Din behandlare ansvarar för upplägget och dess progression. Dina svar hjälper behandlaren att följa upp och bedöma nästa steg.':'Öppna Min plan för att se ditt aktuella upplägg. Kontakta Reda om du behöver hjälp.'}</p></details></div><button class="settings-action" type="button" data-contact>Kontakta ${account.kind==='clinic'?'min klinik':'Reda'}</button><p class="settings-note">${preview?'Visningsexempel. Inga patientuppgifter skickas eller sparas.':'Meddelanden i appen bevakas inte i realtid.'}</p>`;
  panel.innerHTML=`<h3 id="settingsSectionTitle">${title}</h3>${content}`;
  panel.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{const selector=`[data-pref="${b.dataset.pref}"][data-value="${b.dataset.value}"]`,saved=window.RedaPreferences.set({[b.dataset.pref]:b.dataset.value});render();panel.querySelector(selector)?.focus({preventScroll:true});panel.querySelector('[data-preference-status]').textContent=saved?'Ditt val är sparat i den här webbläsaren.':'Valet används nu, men kunde inte sparas på enheten.'});
  panel.querySelectorAll('[data-contact]').forEach(b=>b.onclick=()=>{settings.close();if(onHelp)onHelp();else window.location.assign('/kontakt/')});
  panel.querySelector('[data-open-plan]')?.addEventListener('click',()=>{settings.close();onPlan()});panel.querySelector('[data-open-history]')?.addEventListener('click',()=>{settings.close();onHistory()});
 }
 function open(section='general',opener=gear){returnTo=opener;current=section;render();settings.showModal();settings.querySelector('.settings-content').scrollTop=0}
 function update(next){account={...account,...next};menu.querySelector('[data-account-name]').textContent=account.name;menu.querySelector('[data-account-kind]').textContent=preview?'Visningsexempel':account.signedIn?(account.kind==='clinic'?'Via din klinik':'Eget konto'):'Välkommen till Reda';if(settings.open&&current!=='general')render()}
 function preferenceChange(){if(!settings.open||current!=='general')return;const focused=document.activeElement,pref=focused?.dataset.pref,value=focused?.dataset.value;render();if(pref)panel.querySelector(`[data-pref="${pref}"][data-value="${value}"]`)?.focus({preventScroll:true})}
 window.addEventListener('reda:preferences',preferenceChange);
 update({name:preview?'Prova Reda':'Mitt konto'});
 return {open,update,close(){menu.close();settings.close()},destroy(){window.removeEventListener('reda:preferences',preferenceChange);actions.remove();menu.remove();settings.remove()}};
}
