const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={person:'<circle cx="12" cy="8" r="3.5"/><path d="M5 21v-2a7 7 0 0 1 14 0v2"/>',gear:'<path d="m9 3-1 3-3 1v3l-2 2 2 2v3l3 1 1 3h6l1-3 3-1v-3l2-2-2-2V7l-3-1-1-3Z"/><circle cx="12" cy="12" r="3"/>',card:'<rect x="3" y="5" width="18" height="14" rx="3"/><path d="M3 10h18M7 15h3"/>',shield:'<path d="m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6Z"/><path d="m8 12 3 3 5-6"/>',help:'<circle cx="12" cy="12" r="9"/><path d="M9 9a3 3 0 1 1 5 2c-2 1-2 2-2 3M12 17h.01"/>',exit:'<path d="M9 4H4v16h5M10 12h11m-4-4 4 4-4 4"/>',close:'<path d="m6 6 12 12M18 6 6 18"/>',chevron:'<path d="m8 10 4 4 4-4"/>'};
const glyph=k=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[k]||''}</svg>`;
const sections=[['profile','Konto & integritet','person'],['general','Anpassa Reda','gear'],['help','Hjälp & kontakt','help']];
export function createPatientAccount({header,logout=null,preview=false,onExerciseHelp=null,kind='clinic'}={}){
 let account={name:'Mitt konto',email:'',signedIn:false,hasPlan:false,kind},current='general';
 const actions=document.createElement('div');actions.className='patient-top-actions';actions.innerHTML=`<button class="account-trigger" type="button" aria-label="Öppna kontomenyn" aria-haspopup="dialog" aria-expanded="false"><span class="account-avatar">${glyph('person')}</span><span>Mitt konto</span>${glyph('chevron')}</button>`;header.append(actions);
 const menu=document.createElement('dialog');menu.className='account-menu';menu.setAttribute('aria-label','Kontomeny');menu.innerHTML=`<div class="account-menu-identity"><span class="account-avatar">${glyph('person')}</span><div><b data-account-name>Mitt konto</b><span data-account-kind></span></div></div>${sections.map(([id,label,icon])=>`<button type="button" data-settings="${id}">${glyph(icon)}<span>${label}</span><span class="account-menu-arrow" aria-hidden="true">›</span></button>`).join('')}<div class="account-menu-end"></div>`;document.body.append(menu);if(logout){logout.classList.add('account-logout');logout.innerHTML=glyph('exit')+'Logga ut';menu.querySelector('.account-menu-end').append(logout);logout.addEventListener('click',()=>menu.close())}else menu.querySelector('.account-menu-end').remove();
 const settings=document.createElement('dialog');settings.className='patient-settings';settings.setAttribute('aria-labelledby','patientSettingsTitle');settings.innerHTML=`<header class="settings-header"><button class="settings-back" type="button" aria-label="Tillbaka till kontomenyn"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m14 6-6 6 6 6"/></svg></button><div><span class="settings-eyebrow">Mitt konto</span><h2 id="patientSettingsTitle" tabindex="-1"></h2></div><button class="settings-close" type="button" aria-label="Stäng inställningar">${glyph('close')}</button></header><div class="settings-content"><section id="settingsPanel"></section></div>`;document.body.append(settings);
 const panel=settings.querySelector('#settingsPanel'),trigger=actions.querySelector('.account-trigger');
 function closeOutside(dialog,e){if(e.target!==dialog)return;const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close()}
 menu.addEventListener('click',e=>closeOutside(menu,e));settings.addEventListener('click',e=>closeOutside(settings,e));menu.addEventListener('close',()=>trigger.setAttribute('aria-expanded','false'));settings.addEventListener('close',()=>{if(menu.open)menu.querySelector(`[data-settings="${current}"]`)?.focus({preventScroll:true});else if(document.activeElement===document.body)trigger.focus({preventScroll:true})});
 function openMenu(){trigger.setAttribute('aria-expanded','true');menu.showModal();menu.querySelector(`[data-settings="${current}"]`)?.focus({preventScroll:true})}
 trigger.onclick=openMenu;settings.querySelector('.settings-close').onclick=()=>settings.close();settings.querySelector('.settings-back').onclick=()=>{settings.close();openMenu()};
 menu.querySelectorAll('[data-settings]').forEach(b=>b.onclick=()=>{menu.close();open(b.dataset.settings)});
 function choice(key,value,label,extra=''){const active=window.RedaPreferences.get()[key]===value;return `<button type="button" data-pref="${key}" data-value="${value}" aria-pressed="${active}" ${extra}>${label}</button>`}
 function render(){
  settings.querySelector('#patientSettingsTitle').textContent=sections.find(s=>s[0]===current)?.[1]||'Anpassa Reda';let content='';
  if(current==='general')content=`<div class="settings-group"><h3>Utseende</h3><p>Välj det som känns bäst för dina ögon.</p><div class="theme-choices" role="group" aria-label="Tema">${[['dark','Mörkt'],['light','Ljust'],['system','Följ enheten']].map(([v,l])=>choice('theme',v,`<span class="theme-swatch theme-${v}" aria-hidden="true"><i></i><b></b><em></em></span><span>${l}</span>`)).join('')}</div></div><div class="settings-group"><h3>Textstorlek</h3><div class="settings-segments" role="group" aria-label="Textstorlek">${choice('text','standard','Standard')}${choice('text','large','Större text')}</div></div><div class="settings-group"><h3>Övningsvisning</h3><div class="settings-segments" role="group" aria-label="Övningsvisning">${choice('motion','system','Följ enheten')}${choice('motion','still','Stillbilder')}</div><p>Med stillbilder väljer du själv startläge, rörelsens mitt eller slutläge under Instruktion.</p></div><p class="settings-note" data-preference-status role="status">Dina val sparas i den här webbläsaren.</p>`;
  if(current==='profile')content=`<div class="settings-profile"><span class="account-avatar">${glyph('person')}</span><div><b>${esc(account.name)}</b><span>${preview?'Visningsexempel':account.signedIn?(account.kind==='clinic'?'Plan via klinik':'Eget Reda-konto'):'Inte inloggad'}</span></div></div><dl class="settings-facts"><div><dt>Namn</dt><dd>${esc(account.signedIn||preview?account.name:'Visas när du loggar in')}</dd></div>${account.email?`<div><dt>E-post för inloggning</dt><dd>${esc(account.email)}</dd></div>`:''}<div><dt>Inloggning</dt><dd>${preview?'Du provar utan konto':'Säker länk till din e-post'}</dd></div></dl><div class="settings-group"><h3>Dina uppgifter</h3><p>Behöver något rättas, vill du få en kopia av dina uppgifter eller få hjälp att avsluta kontot? Kontakta ${account.kind==='clinic'?'kliniken som gav dig planen':'Reda'}.</p><a class="settings-action" href="/kontakt/">Kontakt och hjälp med kontot <span aria-hidden="true">↗</span></a></div><p class="settings-note">${preview?'Här visas en fiktiv profil. Inga patientuppgifter skickas eller sparas.':'Din plan och träningshistorik finns i appens huvudmeny.'} Temaval och läsinställningar sparas i den här webbläsaren.</p>`;
  if(current==='help')content=`${onExerciseHelp&&(preview||account.hasPlan)?`<div class="settings-group"><h3>Frågor om en övning?</h3><p>Välj övningen så ser du rätt instruktion, sida och dos. Under passet finns Hjälp vid varje övning.</p><button class="settings-action" type="button" data-exercise-help>Välj övning att få hjälp med <span aria-hidden="true">›</span></button></div>`:''}<div class="settings-group"><h3>Snabba svar</h3><details><summary>Hur ser jag rörelsen?</summary><p>Öppna en övning och tryck på Visa. Visningen stannar efter ett varv. Under Instruktion kan du läsa i din takt, se en del eller välja en stillbild.</p></details><details><summary>Kan jag pausa ett pass?</summary><p>Ja. Gå tillbaka till dagens plan med pilen i passets övre hörn. Tryck på Fortsätt passet när du är redo.</p></details><details><summary>Har min träning sparats?</summary><p>${preview?'Det här är ett exempel. Dina markeringar finns kvar medan du provar, men sparas inte när du lämnar eller laddar om sidan.':'Under passet ser du om träningen har synkats med kliniken. Om sparningen misslyckas finns dina markeringar kvar på enheten. Använd Försök igen när anslutningen fungerar och vänta med att logga ut tills passet är synkat.'}</p></details><details><summary>Vem ändrar min plan?</summary><p>${account.kind==='clinic'?'Din behandlare ansvarar för upplägget. Din återkoppling hjälper behandlaren att bedöma nästa steg.':'Kontakta Reda om du behöver hjälp med ditt upplägg.'}</p></details></div><a class="settings-action" href="/kontakt/">Kontakta Kansei <span aria-hidden="true">↗</span></a><p class="settings-note">Kontaktuppgifter öppnas på Kanseis webbplats. Meddelanden i appen bevakas inte i realtid.</p>`;
  panel.innerHTML=content;
  panel.querySelectorAll('[data-pref]').forEach(b=>b.onclick=()=>{const selector=`[data-pref="${b.dataset.pref}"][data-value="${b.dataset.value}"]`,saved=window.RedaPreferences.set({[b.dataset.pref]:b.dataset.value});render();panel.querySelector(selector)?.focus({preventScroll:true});panel.querySelector('[data-preference-status]').textContent=saved?'Ditt val är sparat i den här webbläsaren.':'Valet används nu, men kunde inte sparas på enheten.'});
  panel.querySelector('[data-exercise-help]')?.addEventListener('click',()=>{settings.close();onExerciseHelp()});
 }
 function open(section='general'){current=sections.some(s=>s[0]===section)?section:'general';render();if(!settings.open)settings.showModal();settings.querySelector('.settings-content').scrollTop=0;settings.querySelector('h2').focus({preventScroll:true})}
 function update(next){account={...account,...next};menu.querySelector('[data-account-name]').textContent=account.name;menu.querySelector('[data-account-kind]').textContent=preview?'Visningsexempel':account.signedIn?(account.kind==='clinic'?'Via din klinik':'Eget konto'):'Välkommen till Reda';if(settings.open&&current!=='general')render()}
 function preferenceChange(){if(!settings.open||current!=='general')return;const focused=document.activeElement,pref=focused?.dataset.pref,value=focused?.dataset.value;render();if(pref)panel.querySelector(`[data-pref="${pref}"][data-value="${value}"]`)?.focus({preventScroll:true})}
 window.addEventListener('reda:preferences',preferenceChange);
 update({name:preview?'Prova Reda':'Mitt konto'});
 return {open,update,close(){menu.close();settings.close()},destroy(){window.removeEventListener('reda:preferences',preferenceChange);actions.remove();menu.remove();settings.remove()}};
}
