import * as api from './secure-browser.mjs'
const $=id=>document.getElementById(id), F=window.RedaFigures
let state=null,plan=null,session=null,index=0,stopMotion=null
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))
function setAuth(show){$('auth').classList.toggle('hidden',!show);$('app').classList.toggle('hidden',show);$('logout').classList.toggle('hidden',show)}
function error(e){$('authError').textContent=e?.message||String(e);$('authError').classList.remove('hidden')}
function exercises(){return plan?.payload?.exercises||[]}
function reviewDate(){return plan?.payload?.reviewDate||plan?.payload?.review?.date||''}
function doseLabel(x){return x?.dose?.label||[x?.dose?.sets&&`${x.dose.sets} omgångar`,x?.dose?.reps&&`${x.dose.reps} repetitioner`].filter(Boolean).join(' · ')||'Följ ordinationen'}
function sets(x){return Math.max(1,Number(x?.dose?.sets||x?.dose?.rounds||1))}
function instruction(x){return x?.instruction||x?.instructions?.[0]||x?.steps?.[0]||x?.cue||'Följ rörelsen lugnt och kontrollerat enligt din ordination.'}
function motionKey(x){return x?.motionKey||x?.motion?.key||x?.figure||x?.variantId||x?.id}
function renderHome(){const xs=exercises();$('patientName').textContent=state.patient.display_name;$('version').textContent=plan.version;$('exerciseCount').textContent=xs.length;$('todayMeta').textContent=`Aktuell plan · ${plan.payload?.schedule?.days?.length||''} planerade pass/vecka`;$('intro').textContent=plan.payload?.goal?`Målet med den här perioden: ${plan.payload.goal}`:'Det här är den plan du och din terapeut har gått igenom.';const d=reviewDate();if(d)$('reviewText').textContent=`Följ den här planen fram till återbesöket ${new Date(d+'T12:00:00').toLocaleDateString('sv-SE')}. Då utvärderar ni tillsammans om övning, belastning eller dos ska ändras.`;$('programList').innerHTML=xs.map((x,i)=>`<div class="exercise"><div class="eyebrow">${i+1} av ${xs.length}</div><h3>${esc(x.name)}</h3><div class="sub">${esc(x.variantLabel||'')} · ${esc(doseLabel(x))}</div><p>${esc(instruction(x))}</p></div>`).join('');renderHistory()}
function renderHistory(){const rows=state.sessions||[];$('history').innerHTML=rows.length?rows.map(s=>`<div class="exercise"><b>${s.status==='completed'?'Genomfört':s.status==='partial'?'Delvis genomfört':s.status==='started'?'Påbörjat':'Planerad vila'}</b><div class="sub">${new Date(s.started_at).toLocaleDateString('sv-SE')} · plan v${s.plan_version}</div></div>`).join(''):'<p class="muted">Ingen träningshistorik ännu.</p>'}
async function bootstrap(){state=await api.patientBootstrap();plan=state.plan;renderHome();setAuth(false);$('sync').textContent='Synkad med kliniken'}
function progressPayload(){return {exercises:session.progress.map(p=>({exerciseId:p.exerciseId,status:p.status,roundsDone:p.roundsDone})),clientUpdatedAt:new Date().toISOString()}}
async function sync(status,completedAt=null){session.status=status;session.completedAt=completedAt;try{await api.saveSession(plan.id,{clientSessionId:session.id,status,startedAt:session.startedAt,completedAt,payload:progressPayload()});$('sync').textContent='Synkad med kliniken'}catch(e){$('sync').textContent='Inte synkad ännu · försöker igen vid nästa ändring';console.warn(e)}}
async function start(){const xs=exercises();if(!xs.length)return;session={id:crypto.randomUUID(),startedAt:new Date().toISOString(),status:'started',progress:xs.map(x=>({exerciseId:x.id||x.variantId||x.name,status:'pending',roundsDone:0}))};index=0;await sync('started');$('player').classList.remove('hidden');showExercise()}
function showExercise(){stopMotion?.();const x=exercises()[index],p=session.progress[index];$('pos').textContent=`${index+1} av ${exercises().length}`;$('exName').textContent=x.name;$('dose').textContent=doseLabel(x);$('instruction').textContent=instruction(x);$('rounds').innerHTML=Array.from({length:sets(x)},(_,i)=>`<button class="btn ${i<p.roundsDone?'primary':'soft'} round" data-round="${i}">${i<p.roundsDone?'✓':'Omgång '+(i+1)}</button>`).join('');const key=motionKey(x);$('motion').innerHTML=F?.svg?F.svg(key,0,x.side||'simultaneous',x.name):'↕';if(F?.animate)stopMotion=F.animate($('motion'),key,{seconds:5});document.querySelectorAll('[data-round]').forEach(b=>b.onclick=()=>markRound(Number(b.dataset.round)));$('next').disabled=p.roundsDone<sets(x)&&p.status!=='skipped';$('next').textContent=index===exercises().length-1?'Avsluta pass':'Nästa övning'}
async function markRound(i){const p=session.progress[index];p.roundsDone=Math.max(p.roundsDone,i+1);p.status=p.roundsDone>=sets(exercises()[index])?'completed':'partial';showExercise();await sync('partial')}
async function skip(){const p=session.progress[index];p.status='skipped';showExercise();await sync('partial')}
async function next(){if(index<exercises().length-1){index++;showExercise();return}const all=session.progress.every(p=>p.status==='completed'),doneAt=new Date().toISOString();await sync(all?'completed':'partial',doneAt);stopMotion?.();$('player').classList.add('hidden');state=await api.patientBootstrap();renderHome();$('sync').textContent=all?'Passet är sparat och synkat':'Passet är sparat som delvis genomfört'}
async function pause(){if(!session)return;$('player').classList.add('hidden');stopMotion?.();await sync(session.progress.some(p=>p.roundsDone||p.status==='skipped')?'partial':'started')}
$('login').onclick=async()=>{try{await api.signIn($('email').value.trim(),$('password').value);await bootstrap()}catch(e){error(e)}}
$('savePassword').onclick=async()=>{try{await api.setPassword($('newPassword').value);$('setPassword').classList.add('hidden');await bootstrap()}catch(e){error(e)}}
$('logout').onclick=async()=>{await api.signOut();location.reload()};$('start').onclick=start;$('skip').onclick=skip;$('next').onclick=next;$('closePlayer').onclick=pause
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('.tab').forEach(x=>x.classList.toggle('hidden',x.id!==b.dataset.tab))})
setAuth(true);api.currentUser().then(async u=>{if(!u)return;if(u.user_metadata?.reda_invited===true){$('setPassword').classList.remove('hidden');return}await bootstrap()}).catch(()=>{})
