/* Reda planner · live curated planner. No automatic progression. */
(function(root){'use strict';const D=root.RedaData,C=root.RedaCore,clone=x=>JSON.parse(JSON.stringify(x));
const legacy={chair:{id:'chair',name:'Ben · vardagsfunktion',why:'Styrka, kontroll och balans för vardagens belastning.',slots:['chair','extension','calf','balance']},hip:{id:'hip',name:'Höft · grundplan',why:'Höftstyrka och kontroll med alternativ för golv eller stående.',slots:['bridge','abduction','chair']},shoulder:{id:'shoulder',name:'Axel · grundplan',why:'Kontrollerad belastning för axel och skuldror.',slots:['row','rotation']}};
const legacyVariants={chair:{supported:'support',standard:'free',high:'free'},extension:{supported:'easy',standard:'pause',high:'pause'},calf:{supported:'both',standard:'both',high:'single'},balance:{supported:'support',standard:'light',high:'light'},bridge:{supported:'low',standard:'pause',high:'pause'},abduction:{supported:'support',standard:'build',high:'build'},row:{supported:'light',standard:'light',high:'build'},rotation:{supported:'light',standard:'light',high:'build'}};
function scale(d,stage){d=clone(d);if(stage==='gentle'){d.sets=Math.min(d.sets,2);d.reps=Math.min(d.reps,10);if(d.hold)d.hold=Math.min(d.hold,20)}if(stage==='loaded'){d.sets=Math.min(4,d.sets+1);d.reps=Math.min(20,d.reps+2);if(d.hold)d.hold=Math.min(60,d.hold+10)}return d}
function assemble(o={}){const bp=legacy[o.blueprint]||legacy.chair,capacity=['supported','standard','high'].includes(o.capacity)?o.capacity:'standard',stage=['gentle','build','loaded'].includes(o.stage)?o.stage:'build';let ids=bp.slots.slice();if(o.floor===false)ids=ids.filter(x=>x!=='bridge');if(o.band===false)ids=ids.filter(x=>!['row','rotation'].includes(x));const p=C.template(o.blueprint);p.title=bp.name;p.goal=o.goal||p.goal;p.reviewDate=o.reviewDate||'';p.message='Programmet är anpassat efter det vi gick igenom vid besöket. Följ den här nivån fram till uppföljningen.';p.safety='Följ den ordinerade nivån och de individuella råd du fått. Ändra inte belastning eller svårighetsgrad på egen hand. Vid osäkerhet, kontakta kliniken.';p.items=ids.map(id=>{const e=D.exercises.find(x=>x.id===id),v=legacyVariants[id]?.[capacity]||e.variants[0].id,i=C.makeItem(id,v,C.allowedSides(id,v)[0]);i.dose=scale(i.dose,stage);return i});return C.validatePlan(p)}
function liveBlueprints(){const src=root.RedaClinical?.blueprints||legacy;return Object.fromEntries(Object.entries(src).map(([id,b])=>[id,{id,name:b.name||id,slots:b.slots||[],advancedSlots:b.advancedSlots||[],performanceSlots:b.performanceSlots||[],goal:b.goal||b.why||''}]))}
function liveContext(o){if(typeof document==='undefined')return o;return {...o,trainingHistory:o.trainingHistory||document.getElementById('trainingHistory')?.value||'regular',goalProfile:o.goalProfile||document.getElementById('goalProfile')?.value||'daily'}}
function load(v,i,n){const x=Number(v?.tags?.load);return Number.isFinite(x)?x:(n<=1?1:1+(i/(n-1))*4)}function compatible(v,o){const t=v?.tags||{},impactGoal=['run','sport'].includes(o.goalProfile);return !(o.floorOK===false&&t.floor)&&!(o.band===false&&t.band)&&!(o.equipment==='home'&&t.gym)&&!(!impactGoal&&t.impact)}
function choose(e,o){let vs=(e?.variants||[]).filter(v=>compatible(v,o));if(!vs.length)return null;const cap={supported:1,standard:2.5,high:4}[o.capacity]??2.5,stage={protected:-.75,build:0,higher:.75}[o.stage]??0,experience={new:-.5,regular:0,rehab_experienced:.75}[o.trainingHistory]??0,target=Math.max(0,cap+stage+experience);return vs.map((v,i)=>({v,d:Math.abs(load(v,i,vs.length)-target)})).sort((a,b)=>a.d-b.d)[0].v}
function doseLabel(d){return d?`${d.sets} ${d.sets===1?'omgång':'omgångar'} × ${d.hold?d.hold+' sekunder':d.reps+' repetitioner'}`:'Följ ordinationen'}function advice(o){return (o.stage==='protected'?'Håll dig till den här nivån och prioritera lugnt, kontrollerat utförande.':o.stage==='higher'?'Följ den valda belastningen och håll samma kvalitet genom hela passet.':'Arbeta lugnt och kontrollerat enligt dosen i programmet.')+' Vi utvärderar nästa steg vid uppföljningen.'}
function challenge(v,e){const n=load(v,0,e?.variants?.length||1);return n>=5?'Performance / hög kapacitet':n>=3.5?'Styrka / högre belastning':n>=2?'Uppbyggande nivå':'Kontroll & tolerans'}
function slotSet(bp,o){const experienced=o.trainingHistory==='rehab_experienced',performance=['run','sport'].includes(o.goalProfile)&&o.capacity==='high'&&o.stage==='higher';if(performance&&bp.performanceSlots?.length)return {slots:bp.performanceSlots,tier:'performance'};if((experienced||o.capacity==='high'||o.stage==='higher')&&o.stage!=='protected'&&bp.advancedSlots?.length)return {slots:bp.advancedSlots,tier:'advanced'};return {slots:bp.slots,tier:'foundation'}}
function buildProgram(input={}){const o=liveContext(input),all=liveBlueprints(),bp=all[o.blueprintId]||Object.values(all)[0];if(!bp)throw Error('Ingen klinisk grundplan är tillgänglig.');const picked=slotSet(bp,o),exercises=[],warnings=[];for(const id of picked.slots){const e=D.exercises.find(x=>x.id===id);if(!e){warnings.push('Saknad övning: '+id);continue}const v=choose(e,o);if(!v){warnings.push(e.name+': ingen variant matchar valda förutsättningar.');continue}const d=clone(v.dose||{sets:2,reps:8,rest:60,hold:0,tempo:5});exercises.push({id:e.id,variantId:v.id,name:e.name,variantLabel:v.name||'',side:allowedSides(e.id,v.id)[0],dose:{...d,label:doseLabel(d)},instruction:(v.steps||[])[0]||v.cue||'',instructions:clone(v.steps||[]),cue:v.cue||'',motionKey:v.pose||`${e.id}.${v.id}`,support:v.support||'',equipment:e.equipment||'',why:v.why||e.purpose||bp.goal,focus:v.focus||v.cue||'',challenge:challenge(v,e),prescription:v.prescription?clone(v.prescription):null,qualityVersion:v.qualityVersion||0})}if(!exercises.length)throw Error('De valda förutsättningarna lämnar ingen godkänd övning. Ändra miljö, nivå eller grundplan.');return {schema:6,context:clone(o),warnings,blueprintId:bp.id,blueprintName:bp.name,intelligenceTier:picked.tier,trainingHistory:o.trainingHistory||'regular',goalProfile:o.goalProfile||'daily',goal:(o.goal||'').trim()||bp.goal,clinicianNote:(o.clinicianNote||'').trim()||advice(o),reviewDate:o.reviewDate||'',patientName:o.patientName||'',presentation:o.guidance||'guided',schedule:{days:[1,3,5]},exercises}}

function allowedSides(id,variant){const unilateral=['rear_foot_split_squat','single_leg_squat_box','cable_er','loaded_carry','lateral_step_down_loaded','step_up','step_down'];return unilateral.includes(id)||['single','elevated'].includes(variant)&&['standing_calf_loaded','hip_thrust','leg_press','landmine_press','cable_er'].includes(id)?['both','left','right']:C.allowedSides(id,variant)}
function alternatives(plan,index){const x=plan.exercises[index],e=D.exercises.find(e=>e.id===x.id);return (e?.variants||[]).filter(v=>compatible(v,plan.context||{})).map(v=>({id:v.id,name:v.name}))}
function editExercise(plan,index,change){const next=clone(plan),x=next.exercises[index];if(!x)throw Error('Övningen saknas');const e=D.exercises.find(e=>e.id===x.id);if(change.variantId&&change.variantId!==x.variantId){const v=e?.variants.find(v=>v.id===change.variantId&&compatible(v,next.context||{}));if(!v)throw Error('Varianten passar inte de valda förutsättningarna.');Object.assign(x,{variantId:v.id,variantLabel:v.name,dose:clone(v.dose),side:allowedSides(e.id,v.id)[0],instructions:clone(v.steps||[]),instruction:(v.steps||[])[0]||v.cue||'',cue:v.cue||'',focus:v.focus||v.cue||'',support:v.support||'',why:v.why||e.purpose||'',motionKey:v.pose,prescription:v.prescription?clone(v.prescription):null,challenge:challenge(v,e)});delete x.prescribedLoad}
if(change.side){if(!allowedSides(x.id,x.variantId).includes(change.side))throw Error('Sidan stämmer inte med övningsvarianten.');x.side=change.side}
for(const [key,min,max] of [['sets',1,8],['reps',1,100],['hold',0,180],['rest',0,600],['tempo',1,60]])if(change[key]!==undefined){const n=Number(change[key]);if(!Number.isInteger(n)||n<min||n>max)throw Error('Kontrollera doseringen: '+key);x.dose[key]=n}
if(change.prescribedLoad!==undefined)x.prescribedLoad=String(change.prescribedLoad).trim().slice(0,100);x.dose.label=doseLabel(x.dose);x.editedByClinician=true;return next}

root.RedaPlanner={allowedSides,alternatives,editExercise,blueprints:legacy,liveBlueprints,buildProgram,assemble};
})(typeof window!=='undefined'?window:globalThis);