/* Reda planner · live curated planner. No automatic progression. */
(function(root){'use strict';const D=root.RedaData,C=root.RedaCore,clone=x=>JSON.parse(JSON.stringify(x));
const legacy={chair:{id:'chair',name:'Ben · vardagsfunktion',why:'Styrka, kontroll och balans för vardagens belastning.',slots:['chair','extension','calf','balance']},hip:{id:'hip',name:'Höft · grundplan',why:'Höftstyrka och kontroll med alternativ för golv eller stående.',slots:['bridge','abduction','chair']},shoulder:{id:'shoulder',name:'Axel · grundplan',why:'Kontrollerad belastning för axel och skuldror.',slots:['row','rotation']}};
const legacyVariants={chair:{supported:'support',standard:'free',high:'free'},extension:{supported:'easy',standard:'pause',high:'pause'},calf:{supported:'both',standard:'both',high:'single'},balance:{supported:'support',standard:'light',high:'light'},bridge:{supported:'low',standard:'pause',high:'pause'},abduction:{supported:'support',standard:'build',high:'build'},row:{supported:'light',standard:'light',high:'build'},rotation:{supported:'light',standard:'light',high:'build'}};
function scale(d,stage){d=clone(d);if(stage==='gentle'){d.sets=Math.min(d.sets,2);d.reps=Math.min(d.reps,10);if(d.hold)d.hold=Math.min(d.hold,20)}if(stage==='loaded'){d.sets=Math.min(4,d.sets+1);d.reps=Math.min(20,d.reps+2);if(d.hold)d.hold=Math.min(60,d.hold+10)}return d}
function assemble(o={}){const bp=legacy[o.blueprint]||legacy.chair,capacity=['supported','standard','high'].includes(o.capacity)?o.capacity:'standard',stage=['gentle','build','loaded'].includes(o.stage)?o.stage:'build';let ids=bp.slots.slice();if(o.floor===false)ids=ids.filter(x=>x!=='bridge');if(o.band===false)ids=ids.filter(x=>!['row','rotation'].includes(x));const p=C.template(o.blueprint);p.title=bp.name;p.goal=o.goal||p.goal;p.reviewDate=o.reviewDate||'';p.message='Programmet är anpassat efter det vi gick igenom vid besöket. Följ den här nivån fram till uppföljningen.';p.safety='Följ den ordinerade nivån och de individuella råd du fått. Ändra inte belastning eller svårighetsgrad på egen hand. Vid osäkerhet, kontakta kliniken.';p.items=ids.map(id=>{const e=D.exercises.find(x=>x.id===id),v=legacyVariants[id]?.[capacity]||e.variants[0].id,i=C.makeItem(id,v,C.allowedSides(id,v)[0]);i.dose=scale(i.dose,stage);return i});return C.validatePlan(p)}
function liveBlueprints(){const src=root.RedaClinical?.blueprints||legacy;return Object.fromEntries(Object.entries(src).map(([id,b])=>[id,{id,name:b.name||id,slots:b.slots||[],advancedSlots:b.advancedSlots||[],performanceSlots:b.performanceSlots||[],goal:b.goal||b.why||''}]))}
function load(v,i,n){const x=Number(v?.tags?.load);return Number.isFinite(x)?x:(n<=1?1:1+(i/(n-1))*4)}function compatible(v,o){const t=v?.tags||{},impactGoal=['run','sport'].includes(o.goalProfile);return !(o.floorOK===false&&t.floor)&&!(o.band===false&&t.band)&&!(o.equipment==='home'&&t.gym)&&!(!impactGoal&&t.impact)}
function choose(e,o){let vs=(e?.variants||[]).filter(v=>compatible(v,o));if(!vs.length)vs=(e?.variants||[]).filter(v=>!(o.equipment==='home'&&v?.tags?.gym));if(!vs.length)return null;const cap={supported:1,standard:2.5,high:4}[o.capacity]??2.5,stage={protected:-.75,build:0,higher:.75}[o.stage]??0,experience={new:-.5,regular:0,rehab_experienced:.75}[o.trainingHistory]??0,target=Math.max(0,cap+stage+experience);return vs.map((v,i)=>({v,d:Math.abs(load(v,i,vs.length)-target)})).sort((a,b)=>a.d-b.d)[0].v}
function doseLabel(d){return d?`${d.sets} ${d.sets===1?'omgång':'omgångar'} × ${d.hold?d.hold+' sekunder':d.reps+' repetitioner'}`:'Följ ordinationen'}function advice(o){return (o.stage==='protected'?'Håll dig till den här nivån och prioritera lugnt, kontrollerat utförande.':o.stage==='higher'?'Följ den valda belastningen och håll samma kvalitet genom hela passet.':'Arbeta lugnt och kontrollerat enligt dosen i programmet.')+' Vi utvärderar nästa steg vid återbesöket.'}
function challenge(v,e){const n=load(v,0,e?.variants?.length||1);return n>=5?'Performance / hög kapacitet':n>=3.5?'Styrka / högre belastning':n>=2?'Uppbyggande nivå':'Kontroll & tolerans'}
function slotSet(bp,o){const experienced=o.trainingHistory==='rehab_experienced',performance=['run','sport'].includes(o.goalProfile)&&o.capacity==='high'&&o.stage==='higher';if(performance&&bp.performanceSlots?.length)return {slots:bp.performanceSlots,tier:'performance'};if((experienced||o.capacity==='high'||o.stage==='higher')&&o.stage!=='protected'&&bp.advancedSlots?.length)return {slots:bp.advancedSlots,tier:'advanced'};return {slots:bp.slots,tier:'foundation'}}
function buildProgram(o={}){const all=liveBlueprints(),bp=all[o.blueprintId]||Object.values(all)[0];if(!bp)throw Error('Ingen klinisk grundplan är tillgänglig.');const picked=slotSet(bp,o),exercises=[];for(const id of picked.slots){const e=D.exercises.find(x=>x.id===id);if(!e)continue;const v=choose(e,o);if(!v)continue;const d=clone(v.dose||{sets:2,reps:8,rest:60,hold:0,tempo:5});exercises.push({id:e.id,variantId:v.id,name:e.name,variantLabel:v.name||'',side:'simultaneous',dose:{...d,label:doseLabel(d)},instruction:(v.steps||[])[0]||v.cue||'',instructions:clone(v.steps||[]),cue:v.cue||'',motionKey:v.pose||`${e.id}.${v.id}`,support:v.support||'',equipment:e.equipment||'',why:v.why||e.purpose||bp.goal,focus:v.focus||v.cue||'',challenge:challenge(v,e),prescription:v.prescription?clone(v.prescription):null,qualityVersion:v.qualityVersion||0})}if(!exercises.length)throw Error('De valda förutsättningarna lämnar ingen godkänd övning. Ändra miljö, nivå eller grundplan.');return {schema:5,blueprintId:bp.id,blueprintName:bp.name,intelligenceTier:picked.tier,trainingHistory:o.trainingHistory||'regular',goalProfile:o.goalProfile||'daily',goal:(o.goal||'').trim()||bp.goal,clinicianNote:(o.clinicianNote||'').trim()||advice(o),reviewDate:o.reviewDate||'',patientName:o.patientName||'',presentation:o.guidance||'guided',schedule:{days:[1,3,5]},exercises}}
root.RedaPlanner={blueprints:legacy,liveBlueprints,buildProgram,assemble};
})(typeof window!=='undefined'?window:globalThis);