/* Preparing a path never publishes a prescription or changes the approved runtime frame. */
(function(root){'use strict';
const E=root.RedaProgression,P=root.RedaPlanner,X=root.RedaPaths,clone=x=>JSON.parse(JSON.stringify(x)),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(host,plan,onChange){
 if(!host)return;if(!plan?.exercises?.length){host.replaceChildren();return}
 const saved=plan.progressionDraft,base=clone(plan);delete base.progressionDraft;
 if(saved){try{E.validate(saved)}catch{host.innerHTML='<div class="progression-author"><p>Det sparade ramutkastet kan inte läsas. Ordinationen ligger kvar.</p><button type="button" class="btn ghost">Ta bort felaktigt ramutkast</button></div>';host.querySelector('button').onclick=()=>onChange(base);return}}
 const current=!saved||E.binding(base)===E.binding(saved.steps[0].plan);
 if(!current){host.innerHTML='<section class="progression-author"><h3>Ramen behöver förnyas</h3><p>Ordinationen, målet eller förutsättningarna har ändrats sedan ramen skapades. Börja från den aktuella planen.</p><button type="button" class="btn ghost">Börja om med aktuell ordination</button></section>';host.querySelector('button').onclick=()=>onChange(base);return}
 let steps=saved?clone(saved.steps):[{id:'current',label:'Nuvarande ordination',plan:base}],next=clone(steps.at(-1).plan);
 host.innerHTML=`<details class="progression-author" ${saved?'open':''}><summary>Förbered patientens väg framåt <span>${saved?'Sparat ramutkast · '+saved.steps.length+' steg':'Utgå från ordinationen och lägg till nästa steg'}</span></summary><p>Varje steg innehåller en fullständig ordination. Du väljer ändringarna och villkoren. Sparad ram granskas och godkänns separat under Uppföljning.</p><ol data-path-steps class="path-steps"></ol><button type="button" class="btn ghost" data-remove-step>Ta bort sista steget</button><section class="path-compose"><h4>Nästa steg</h4><label for="pathExercise">Övning att justera</label><select id="pathExercise">${base.exercises.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('')}</select><div data-path-fields class="form-grid"></div><div data-path-preview></div><div class="field"><label for="pathLabel">Namn på steget</label><input id="pathLabel" maxlength="100" placeholder="T.ex. mer belastning med samma kontroll"></div><div class="field"><label for="pathReason">Varför det här steget?</label><textarea id="pathReason" maxlength="500" placeholder="Knyt ändringen till patientens mål och det ni har bedömt."></textarea></div><button type="button" class="btn ghost" data-add-step>Lägg till steg</button></section><h4>Villkor för att gå vidare</h4><p>Villkoren gäller vid varje övergång. Nya pass och nya svar krävs på varje nivå.</p><div class="form-grid">${[['pathDays','Uppföljda träningsdagar som krävs',1,30,saved?.rules.minSuccessfulDays],['pathMinDays','Minst antal dagar på nivån',1,60,saved?.rules.minDaysAtStep],['pathEvidenceDays','Underlag högst antal dagar gammalt',1,60,saved?.rules.maxEvidenceAgeDays]].map(([id,label,min,max,value])=>`<div class="field"><label for="${id}">${label}</label><input type="number" id="${id}" min="${min}" max="${max}" value="${value||''}" placeholder="Ange själv"></div>`).join('')}<div class="field"><label for="pathFrom">Ramens startdatum</label><input type="date" id="pathFrom" value="${esc(saved?.validFrom||'')}"></div><div class="field"><label for="pathUntil">Ramens slutdatum</label><input type="date" id="pathUntil" value="${esc(saved?.validUntil||'')}"></div><div class="field"><label for="pathEffort">Träningssvar som stödjer nästa steg</label><select id="pathEffort"><option value="">Välj träningssvar</option><option value="easy">Lätt</option><option value="easy,okay">Lätt eller lagom</option></select></div></div><p>Kontrollerat utförande, uppföljt svar dagen efter och aktuella förutsättningar krävs också. Förändrade besvär leder till bedömning.</p><button type="button" class="btn primary" data-save-path>Spara ramen i planutkastet</button> <button type="button" class="btn ghost" data-remove-path>Ta bort ramutkast</button><p data-path-error role="alert"></p><p data-path-status role="status"></p><a href="/reda-2/progression-lab.html" target="_blank" rel="noopener">Prova motorn med fiktiva fall ↗</a></details>`;
 const q=s=>host.querySelector(s),$=id=>q('#'+id);$('pathEffort').value=saved?.rules.acceptedEffort.join(',')||'';
 function guard(fn){q('[data-path-error]').textContent='';try{fn()}catch(e){q('[data-path-error]').textContent=e.message}}
 function drawSteps(){q('[data-path-steps]').innerHTML=steps.map((s,i)=>'<li><b>'+esc(s.label)+'</b>'+(i?X.html(steps[i-1].plan,s.plan,esc):'<p>Den aktuella ordinationen är utgångspunkt.</p>')+(s.rationale?'<p>'+esc(s.rationale)+'</p>':'')+'</li>').join('');q('[data-remove-step]').disabled=steps.length<2;q('[data-add-step]').disabled=steps.length>=12}
 function preview(){q('[data-path-preview]').innerHTML=X.html(steps.at(-1).plan,next,esc)}
 function fields(){const i=Number($('pathExercise').value),x=next.exercises[i];q('[data-path-fields]').innerHTML='<div class="field"><label for="pathVariant">Variant</label><select id="pathVariant" data-axis="variantId">'+P.alternatives(next,i).map(v=>'<option value="'+esc(v.id)+'" '+(v.id===x.variantId?'selected':'')+'>'+esc(v.name)+'</option>').join('')+'</select></div>'+[['sets','Omgångar',1,8],['reps','Repetitioner',1,100],['hold','Hålltid (sek)',0,180],['rest','Vila (sek)',0,600],['tempo','Rörelsecykel (sek)',1,60]].map(([k,l,min,max])=>'<div class="field"><label for="path-'+k+'">'+l+'</label><input id="path-'+k+'" data-axis="'+k+'" type="number" required min="'+min+'" max="'+max+'" value="'+x.dose[k]+'" '+((k==='hold'&&!x.dose.hold)||(k==='reps'&&x.dose.hold)?'disabled':'')+'></div>').join('')+[['prescribedLoad','Ordinerad belastning',100],['prescribedRange','Ordinerat rörelseomfång',160]].map(([k,l,max])=>'<div class="field"><label for="path-'+k+'">'+l+'</label><input id="path-'+k+'" data-axis="'+k+'" maxlength="'+max+'" value="'+esc(x[k]||'')+'" placeholder="'+(k==='prescribedRange'?esc(x.prescription?.rom||'Ange individuellt'):'Ange individuellt')+'"></div>').join('');q('[data-path-fields]').querySelectorAll('[data-axis]').forEach(el=>el.onchange=()=>guard(()=>{if(el.type==='number'&&el.value==='')throw Error('Ange ett värde för dosen.');next=P.editExercise(next,i,{[el.dataset.axis]:el.value});if(el.dataset.axis==='variantId')fields();preview()}))}
 $('pathExercise').onchange=fields;
 q('[data-add-step]').onclick=()=>guard(()=>{if(![...q('[data-path-fields]').querySelectorAll('input')].every(el=>el.checkValidity()))throw Error('Kontrollera värdena i steget.');steps=X.append(steps,next,$('pathLabel').value,$('pathReason').value);next=clone(steps.at(-1).plan);$('pathLabel').value='';$('pathReason').value='';drawSteps();fields();preview();q('[data-path-status]').textContent='Steget är tillagt. Spara ramen när alla steg och villkor är klara.'});
 q('[data-remove-step]').onclick=()=>{if(steps.length<2)return;steps.pop();next=clone(steps.at(-1).plan);drawSteps();fields();preview()};
 q('[data-remove-path]').onclick=()=>onChange(base);
 q('[data-save-path]').onclick=()=>guard(()=>{if(X.changes(steps.at(-1).plan,next).length||$('pathLabel').value.trim()||$('pathReason').value.trim())throw Error('Lägg till det påbörjade steget innan du sparar ramen.');const policy=E.compile({id:saved?.id||'path-'+crypto.randomUUID(),revision:(saved?.revision||0)+1,validFrom:$('pathFrom').value,validUntil:$('pathUntil').value,rules:{minSuccessfulDays:Number($('pathDays').value),minDaysAtStep:Number($('pathMinDays').value),maxEvidenceAgeDays:Number($('pathEvidenceDays').value),acceptedEffort:$('pathEffort').value.split(',')},steps});onChange({...base,progressionDraft:policy})});
 drawSteps();fields();preview();
}
root.RedaProgressionEditor={render};
})(window);
