/* Complete clinician-authored prescriptions, with an explicit diff at every transition. */
(function(root){'use strict';
const clone=x=>JSON.parse(JSON.stringify(x));
const axes=[['variantId','Variant',x=>x.variantLabel||x.variantId],['side','Sida',x=>({both:'Båda, en i taget',left:'Vänster',right:'Höger',simultaneous:'Båda samtidigt'}[x.side])],...['sets','reps','hold','rest','tempo'].map((k,i)=>[k,['Omgångar','Repetitioner','Hålltid (sek)','Vila (sek)','Rörelsecykel (sek)'][i],x=>x.dose?.[k]]),['prescribedLoad','Belastning',x=>x.prescribedLoad||'Ej preciserad'],['prescribedRange','Rörelseomfång',x=>x.prescribedRange||x.prescription?.rom||'Enligt instruktion']];
function changes(before,after){const out=[];for(const x of after.exercises){const old=before.exercises.find(y=>y.id===x.id);if(!old){out.push({exercise:x.name,axis:'Övning',before:'Ingår inte',after:x.name});continue}for(const [key,label,value] of axes){const a=value(old),b=value(x);if(a!==b)out.push({exercise:x.name,axis:label,before:String(a??''),after:String(b??'')})}}for(const x of before.exercises)if(!after.exercises.some(y=>y.id===x.id))out.push({exercise:x.name,axis:'Övning',before:x.name,after:'Ingår inte'});return out}
function append(steps,plan,label,rationale){if(steps.length>=12)throw Error('Ramen kan innehålla högst tolv steg.');if(!changes(steps.at(-1).plan,plan).length)throw Error('Gör en faktisk ändring innan du lägger till steget.');if(!label.trim()||label.length>100)throw Error('Ge steget ett namn på högst 100 tecken.');if(rationale.trim().length<5||rationale.length>500)throw Error('Beskriv varför det här steget passar patientens mål (5–500 tecken).');const p=clone(plan);delete p.progressionDraft;return [...clone(steps),{id:'step-'+crypto.randomUUID(),label:label.trim(),rationale:rationale.trim(),plan:p}]}
function html(before,after,esc){const rows=changes(before,after);return rows.length?'<div class="path-diff-scroll"><table class="path-diff"><thead><tr><th>Ändring</th><th>Från</th><th>Till</th></tr></thead><tbody>'+rows.map(r=>'<tr><th>'+esc(r.exercise)+'<small>'+esc(r.axis)+'</small></th><td>'+esc(r.before)+'</td><td>'+esc(r.after)+'</td></tr>').join('')+'</tbody></table></div>':'<p>Ingen ändring av ordinationen ännu.</p>'}
root.RedaPaths={changes,append,html};if(typeof module==='object'&&module.exports)module.exports=root.RedaPaths;
})(typeof window!=='undefined'?window:globalThis);
