/* Clinician draft preparation. Serialized with a plan; never consumed by patient playback. */
(function(root){'use strict';
const E=root.RedaProgression,P=root.RedaPlanner,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function render(host,plan,onChange){
 if(!host)return;if(!plan){host.replaceChildren();return}
 const saved=plan.progressionDraft,base={...plan};delete base.progressionDraft;
 const current=saved&&E.binding(base)===E.binding(saved.steps?.[0]?.plan||{});
 host.innerHTML=`<details class="progression-author" ${saved?'open':''}><summary>Förbered nästa steg <span>Utvecklingsläge</span></summary><p>Här förbereder du en ram för motorn. Den sparas med planen men körs inte för patienten. Villkoren behöver klinisk granskning och säker serverhantering före aktivering.</p>${saved?`<div class="progression-saved" role="status"><b>${current?'Ram sparad som utkast':'Ramen behöver förnyas'}</b><p>${current?esc(saved.steps[1].label)+' · '+saved.rules.minSuccessfulDays+' uppföljda träningsdagar, minst '+saved.rules.minDaysAtStep+' dagar på nivån.':'Ordinationen, målet eller förutsättningarna har ändrats. Skapa om ramen från den aktuella planen.'}</p><button type="button" class="btn ghost" data-remove-path>Ta bort ramutkast</button></div>`:''}<div class="form-grid"><div class="field"><label for="pathExercise">Övning</label><select id="pathExercise">${base.exercises.map((x,i)=>`<option value="${i}">${esc(x.name)}</option>`).join('')}</select></div><div class="field"><label for="pathAxis">Vad ändras i nästa steg?</label><select id="pathAxis"><option value="reps">Repetitioner</option><option value="sets">Omgångar</option><option value="hold">Hålltid, sekunder</option></select></div><div class="field"><label for="pathTarget">Nästa ordinerade värde</label><input type="number" id="pathTarget" min="1" max="100" placeholder="Ange själv"></div><div class="field"><label for="pathDays">Uppföljda träningsdagar som krävs</label><input type="number" id="pathDays" min="1" max="30" placeholder="Ange själv"></div><div class="field"><label for="pathMinDays">Minst antal dagar på nivån</label><input type="number" id="pathMinDays" min="1" max="60" placeholder="Ange själv"></div><div class="field"><label for="pathEvidenceDays">Underlag högst antal dagar gammalt</label><input type="number" id="pathEvidenceDays" min="1" max="60" placeholder="Ange själv"></div><div class="field"><label for="pathFrom">Ramens startdatum</label><input type="date" id="pathFrom"></div><div class="field"><label for="pathUntil">Ramens slutdatum</label><input type="date" id="pathUntil"></div><div class="field"><label for="pathEffort">Träningssvar som stödjer nästa steg</label><select id="pathEffort"><option value="easy">Lätt</option><option value="easy,okay">Lätt eller lagom</option></select></div></div><p class="care-help">Motorn kräver också kontrollerat utförande, uppföljt svar dagen efter och svar om övrig träning. Försämring leder till bedömning. Inga universella smärtgränser är förifyllda.</p><p id="pathCurrent" class="care-help"></p><button type="button" class="btn ghost" data-save-path>Lägg ramen i planutkastet</button><p data-path-error role="alert"></p><a class="text-link" href="/reda-2/progression-lab.html" target="_blank" rel="noopener">Prova motorn med fiktiva fall ↗</a></details>`;
 const $=id=>host.querySelector('#'+id),status=host.querySelector('[data-path-error]');
 function showCurrent(){const x=base.exercises[Number($('pathExercise').value)],axis=$('pathAxis').value;const ranges={reps:[1,100],sets:[1,8],hold:[0,180]};$('pathTarget').min=ranges[axis][0];$('pathTarget').max=ranges[axis][1];$('pathCurrent').textContent='Nuvarande ordination: '+x.dose.label+'. Värde som ändras: '+x.dose[axis]+'.';}
 $('pathExercise').onchange=showCurrent;$('pathAxis').onchange=showCurrent;showCurrent();
 host.querySelector('[data-remove-path]')?.addEventListener('click',()=>onChange(base));
 host.querySelector('[data-save-path]').onclick=()=>{try{
  const index=Number($('pathExercise').value),axis=$('pathAxis').value;if(!$('pathTarget').value)throw Error('Ange nästa ordinerade värde.');
  if((axis==='reps'&&base.exercises[index].dose.hold>0)||(axis==='hold'&&base.exercises[index].dose.hold===0))throw Error('Behåll övningens dosform. Repetitionsövningar ändras i repetitioner; hållövningar i hålltid.');
  const next=P.editExercise(base,index,{[axis]:Number($('pathTarget').value)}),x=next.exercises[index],policy=E.compile({id:saved?.id||'path-'+crypto.randomUUID(),revision:(saved?.revision||0)+1,validFrom:$('pathFrom').value,validUntil:$('pathUntil').value,rules:{minSuccessfulDays:Number($('pathDays').value),minDaysAtStep:Number($('pathMinDays').value),maxEvidenceAgeDays:Number($('pathEvidenceDays').value),acceptedEffort:$('pathEffort').value.split(',')},steps:[{id:'current',label:'Nuvarande ordination',plan:base},{id:'next',label:x.name+' · '+x.dose.label,plan:next}]});
  onChange({...base,progressionDraft:policy});
 }catch(e){status.textContent=e.message}};
}
root.RedaProgressionEditor={render};
})(window);
