/* Six short, explicit questions. In-memory editing, server-confirmed success, no offline health-data copy. */
(function(root){'use strict';const R=root.RedaTrainingResponse,esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function create(host,{submit,onSaved,demo=false}){
 let ctx={},selected=null,answers={},step=0,busy=false,requestId=null,account=null,receipt=null,error='',opened=false;
 function render(next){if(next){if(account!==next.userId){selected=null;answers={};step=0;receipt=null;requestId=null;opened=false}account=next.userId;ctx=next}
  if(ctx.responseError){host.innerHTML='<div class="card ei-response-form"><h3>Återkopplingen kunde inte hämtas</h3><p>Du kan fortsätta med din träning. Ladda om sidan för att försöka hämta svaren igen.</p></div>';return}
  const due=R.due(ctx.sessions,ctx.responses),candidate=due.find(s=>s.id===selected?.id)||due[0];if(candidate?.id!==selected?.id){selected=candidate||null;answers={};step=0;requestId=null;opened=false;error=''}
  const received=receipt?`<div class="ei-receipt" role="status"><b>${demo?'Du har provat återkopplingen.':'Din återkoppling är sparad.'}</b><p>${demo?'Dina val finns bara i den här visningen.':'Svaret hör till passet '+esc(R.day(receipt.sessionDate))+', plan v'+receipt.plan_version+'.'}</p>${['review','contact'].includes(R.signal(receipt.answers).kind)?'<p>Kontakta Kansei om du behöver hjälp eller en ny bedömning. Svaren bevakas inte i realtid.</p><a href="/kontakt/">Kontakta kliniken ↗</a>':''}</div>`:'';
  if(!selected){host.innerHTML=received+(ctx.sessions?.length?'<div class="card ei-response-form"><p class="eyebrow">Efter träningen</p><h3>Hur kroppen svarar är en del av planen.</h3><p>Från dagen efter ett avslutat pass kan du lämna en kort återkoppling här. Redan sparade svar behöver du inte fylla i igen.</p></div>':'');return}
  const q=R.questions[step];host.innerHTML=received+`<section class="card ei-response-form"><p class="eyebrow">Efter träningen · plan v${Number(selected.plan_version)}</p><h3>${opened?esc(q.title):'Hur fungerade träningen för dig?'}</h3><p class="ei-response-date">Passet ${esc(R.day(selected.completed_at))} · ${selected.status==='partial'?'delvis genomfört':'genomfört'}</p>${opened?`<p class="ei-question-count">Fråga ${step+1} av ${R.questions.length}</p>${q.help?'<p>'+esc(q.help)+'</p>':''}<fieldset><legend class="sr-only">${esc(q.title)}</legend>${q.options.map(([v,label])=>`<button type="button" data-answer="${v}" aria-pressed="${answers[q.key]===v}" ${busy?'disabled':''}>${esc(label)}</button>`).join('')}</fieldset><div class="ei-form-nav"><button type="button" class="btn ghost" data-back ${busy?'disabled':''}>${step?'Tillbaka':'Senare'}</button><button type="button" class="btn primary" data-forward ${busy||!answers[q.key]?'disabled':''}>${busy?'Sparar…':step===R.questions.length-1?(demo?'Visa exemplet':'Spara återkoppling'):'Nästa fråga'}</button></div>`:'<p>Berätta hur kroppen svarade och om något var svårt. Du får en fråga i taget och kan svara att du är osäker.</p><button type="button" class="btn primary" data-open>Svara på frågorna</button>'}<p class="ei-form-error" role="alert">${esc(error)}</p><p class="ei-footnote">${demo?'Fiktivt exempel. Dina val skickas inte till kliniken och sparas inte.':'Kliniken kan läsa sparade svar. Återkopplingen bevakas inte i realtid och ändrar inte ordinationen.'}</p></section>`;
  host.querySelector('[data-open]')?.addEventListener('click',()=>{opened=true;render()});host.querySelector('[data-back]')?.addEventListener('click',()=>{if(busy)return;if(step)step--;else opened=false;error='';render()});
  host.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{if(busy)return;answers[q.key]=b.dataset.answer;requestId=null;error='';render();host.querySelector('[data-forward]')?.focus({preventScroll:true})});
  host.querySelector('[data-forward]')?.addEventListener('click',async()=>{if(busy||!answers[q.key])return;if(step<R.questions.length-1){step++;render();host.querySelector('fieldset button')?.focus({preventScroll:true});return}
   const payload=R.normalize(answers),sid=selected.id,owner=account,sessionDate=selected.completed_at;requestId=requestId||crypto.randomUUID();busy=true;render();
   try{const row=await submit(sid,requestId,payload);if(account!==owner)return;if(!row?.id||row.session_id!==sid)throw Error('Sparningen kunde inte bekräftas. Försök igen.');R.normalize(row.answers);receipt={...row,sessionDate};ctx={...ctx,responses:[...(ctx.responses||[]).filter(r=>r.session_id!==sid),row]};selected=null;onSaved?.(row)}catch(e){if(account===owner)error=e.message||'Svaret kunde inte sparas. Dina val finns kvar här; försök igen.'}finally{busy=false;if(account===owner)render()}
  });
 }
 return {render,isBusy:()=>busy};
}
root.RedaResponseForm={create};
})(window);
