import { createClient } from 'https://esm.sh/@supabase/supabase-js@2.116.0?bundle'
const cfg=window.REDA_BACKEND
if(!cfg?.url||!cfg?.publishableKey) throw new Error('Reda backend saknas')
export const db=createClient(cfg.url,cfg.publishableKey,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})
export async function currentUser(){const {data:{user},error}=await db.auth.getUser();if(error)throw error;return user}
export async function signIn(email,password){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error}
export async function signUp(){throw new Error('Nya behandlarkonton skapas endast av Reda-administratör.')}
export async function sendPatientMagicLink(email){const {error}=await db.auth.signInWithOtp({email:String(email||'').trim().toLowerCase(),options:{emailRedirectTo:cfg.patientUrl,shouldCreateUser:false}});if(error)throw error}
export async function signOut(){await db.auth.signOut()}
export async function aal(){const {data,error}=await db.auth.mfa.getAuthenticatorAssuranceLevel();if(error)throw error;return data}
export async function factors(){const {data,error}=await db.auth.mfa.listFactors();if(error)throw error;return data}
export async function enrollTotp(){const {data,error}=await db.auth.mfa.enroll({factorType:'totp',friendlyName:'Reda klinik'});if(error)throw error;return data}
export async function verifyTotp(factorId,code){const {data,error}=await db.auth.mfa.challengeAndVerify({factorId,code});if(error)throw error;return data}
export async function claimClinician(){const {data,error}=await db.functions.invoke('claim-clinician');if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function clinicianProfile(){const u=await currentUser();if(!u)return null;const {data,error}=await db.from('reda_profiles').select('role,display_name').eq('user_id',u.id).maybeSingle();if(error)throw error;return data}
export async function listPatients(){const u=await currentUser();const {data,error}=await db.from('reda_patients').select('id,display_name,status,updated_at,auth_user_id').eq('clinician_id',u.id).eq('status','active').order('updated_at',{ascending:false});if(error)throw error;return data||[]}
export async function createPatient(displayName){const u=await currentUser();const {data,error}=await db.from('reda_patients').insert({clinician_id:u.id,display_name:String(displayName).trim()}).select('id,display_name').single();if(error)throw error;return data}
export async function patientSummary(patientId){const [plans,sessions]=await Promise.all([db.from('reda_plans').select('id,version,status,activated_at,created_at,payload').eq('patient_id',patientId).order('version',{ascending:false}),db.from('reda_sessions').select('id,client_session_id,plan_id,status,started_at,completed_at,plan_version,payload').eq('patient_id',patientId).order('started_at',{ascending:false}).limit(30)]);if(plans.error)throw plans.error;if(sessions.error)throw sessions.error;return {plans:plans.data||[],sessions:sessions.data||[]}}
export async function createDraft(patientId,payload){const u=await currentUser();const {data:last,error:lErr}=await db.from('reda_plans').select('version').eq('patient_id',patientId).order('version',{ascending:false}).limit(1);if(lErr)throw lErr;const version=(last?.[0]?.version||0)+1;const {data,error}=await db.from('reda_plans').insert({patient_id:patientId,clinician_id:u.id,version,status:'draft',payload}).select('id,version').single();if(error)throw error;return data}
export async function activatePlan(planId){const {data,error}=await db.functions.invoke('activate-plan',{body:{plan_id:planId}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function invitePatient(patientId,email){const {data,error}=await db.functions.invoke('invite-patient',{body:{patient_id:patientId,email}});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
export async function patientBootstrap(){const u=await currentUser();if(!u)throw new Error('Logga in först');const {data:patient,error:pErr}=await db.from('reda_patients').select('id,display_name').eq('auth_user_id',u.id).eq('status','active').single();if(pErr)throw pErr;const {data:plan,error}=await db.from('reda_plans').select('id,version,payload,activated_at').eq('patient_id',patient.id).eq('status','active').single();if(error)throw error;const {data:sessions,error:sErr}=await db.from('reda_sessions').select('id,client_session_id,plan_id,status,started_at,completed_at,plan_version,payload').eq('patient_id',patient.id).order('started_at',{ascending:false}).limit(30);if(sErr)throw sErr;return {userId:u.id,patient,plan,sessions:sessions||[]}}
export async function saveSession(planId,session){const body={client_session_id:session.clientSessionId,plan_id:planId,status:session.status,started_at:session.startedAt,completed_at:session.completedAt||null,payload:session.payload||{}};const {data,error}=await db.functions.invoke('save-session',{body});if(error)throw error;if(data?.error)throw new Error(data.error);return data}
