-- Multi-clinic unit layer inside an organization.
create table public.reda_units(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.reda_organizations(id),name text not null check(length(trim(name)) between 1 and 100),slug text not null,status text not null default 'active' check(status in('active','disabled')),created_at timestamptz not null default now(),unique(organization_id,slug),unique(id,organization_id));
create table public.reda_unit_memberships(unit_id uuid not null,organization_id uuid not null,user_id uuid not null,role text not null check(role in('unit_admin','clinician','viewer')),status text not null default 'active' check(status in('active','revoked')),created_at timestamptz not null default now(),primary key(unit_id,user_id),foreign key(unit_id,organization_id)references public.reda_units(id,organization_id),foreign key(organization_id,user_id)references public.reda_memberships(organization_id,user_id));
alter table public.reda_patients add column unit_id uuid;alter table public.reda_patients add constraint reda_patient_unit_binding foreign key(unit_id,organization_id) references public.reda_units(id,organization_id);
create index reda_units_org on public.reda_units(organization_id,status,name);create index reda_unit_members_user on public.reda_unit_memberships(organization_id,user_id,status);create index reda_patients_unit_clinician on public.reda_patients(organization_id,unit_id,clinician_id,status,updated_at desc);
alter table public.reda_units enable row level security;alter table public.reda_unit_memberships enable row level security;revoke all on public.reda_units,public.reda_unit_memberships from public,anon,authenticated;
create policy "unit rpc only" on public.reda_units for all to authenticated using(false)with check(false);create policy "unit membership rpc only" on public.reda_unit_memberships for all to authenticated using(false)with check(false);
create function private.reda_can_manage_units(org uuid,actor uuid)returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.reda_memberships where organization_id=org and user_id=actor and status='active' and role in('owner','admin'))$$;
create function private.reda_units()returns jsonb language plpgsql stable security definer set search_path='' as $$declare actor uuid:=private.reda_live_actor();org uuid:=private.reda_request_organization();begin if not private.reda_is_clinician_aal2() then raise exception using errcode='42501',message='MFA krävs.';end if;return coalesce((select jsonb_agg(jsonb_build_object('id',u.id,'name',u.name,'slug',u.slug,'status',u.status,'members',(select count(*)from public.reda_unit_memberships m where m.unit_id=u.id and m.status='active'),'patients',(select count(*)from public.reda_patients p where p.unit_id=u.id and p.status='active'))order by u.name)from public.reda_units u where u.organization_id=org),'[]'::jsonb);end$$;
create function public.reda_units()returns jsonb language sql stable security invoker set search_path='' as $$select private.reda_units()$$;revoke all on function private.reda_units(),public.reda_units() from public,anon,authenticated;grant execute on function private.reda_units(),public.reda_units() to authenticated;
